const fs=require('node:fs');const assert=require('node:assert/strict');const esbuild=require('esbuild');const {chromium}=require('playwright');
(async()=>{
const executable=process.env.HSM_CHROMIUM_PATH;
const result=await esbuild.build({entryPoints:['tests/special-record/browser-entry.tsx'],bundle:true,write:false,format:'iife',jsx:'automatic',loader:{'.css':'empty','.module.css':'empty'},plugins:[{name:'isolated-surrounding-features',setup(b){b.onResolve({filter:/^\.\/(teacher-special-lessons|student-learning-history|class-learning-board|schedule-reminders|guardian-push-toggle|report-comment-reactions|hansalmae-icons)$/},args=>({path:args.path,namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:`export const TeacherSpecialLessons=()=>null, StudentLearningHistory=()=>null, ExamCategoryModal=()=>null, ScheduleReminderList=()=>null,DevicePushToggle=()=>null,CommentReactionBar=()=>null,HansalmaeIcon=()=>null;const load=async()=>{},toggle=async()=>{};export const useScheduleReminders=()=>null,useReportCommentReactions=()=>({reactions:{},reacting:null,load,toggle});`,loader:'js'}));}}]});
const browser=await chromium.launch({executablePath:executable,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.setContent('<div id="root"></div>');await page.addScriptTag({content:result.outputFiles[0].text});
const content=page.locator('.learning-individual-content textarea');await content.fill('내 입력');await page.evaluate(()=>window.remote('다른 창 입력'));await page.getByRole('button',{name:'임시저장',exact:true}).click();await page.getByRole('button',{name:'최신 내용 비교'}).click();await page.getByRole('dialog').waitFor();await page.getByLabel('내 입력',{exact:false}).check();await page.getByRole('button',{name:'선택한 내용 적용'}).click();assert.equal(await content.inputValue(),'내 입력');await page.getByRole('button',{name:'임시저장',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.learning-board-error'));
await page.evaluate(()=>{window.saveDelay=250;});await content.fill('저장 시작');await page.getByRole('button',{name:'임시저장',exact:true}).click();await content.fill('저장 중 추가 입력');await page.waitForTimeout(350);assert.equal(await content.inputValue(),'저장 중 추가 입력');
await page.getByRole('button',{name:'출석',exact:true}).click();await page.waitForFunction(()=>window.changes.length===1);assert.deepEqual(await page.evaluate(()=>window.changes[0]),{studentId:'a',status:null});assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.name==='staff_special_edit_snapshot').length),2);
await page.evaluate(()=>{window.calls=[];window.renderNotifications('teacher');});await page.waitForFunction(()=>window.calls.length===1);assert.deepEqual(await page.evaluate(()=>window.calls.map(c=>c.name)),['staff_report_comment_inbox']);await page.waitForTimeout(5200);assert.equal(await page.evaluate(()=>window.calls.length),2);
await page.evaluate(()=>{window.calls=[];window.renderNotifications('guardian');});await page.waitForFunction(()=>window.calls.length===2);assert.deepEqual((await page.evaluate(()=>window.calls.map(c=>c.name))).sort(),['family_notification_center','family_report_reply_inbox']);assert.deepEqual(errors,[]);console.log('Browser PASS: conflict dialog, pending edits, targeted attendance, hidden header suppression, teacher 5-second polling, guardian role queries');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
