// Actual editor, synthetic students, mocked RPCs: never contacts production.
const fs=require('node:fs'),assert=require('node:assert/strict'),esbuild=require('esbuild');
const {chromium}=require(process.env.HSM_PLAYWRIGHT_MODULE||'playwright');
(async()=>{
const entry=`import React from 'react';import {createRoot} from 'react-dom/client';import {TeacherSpecialLessons} from './app/teacher-special-lessons';
const students=[{id:'a',name:'가상 학생 A',lessonKind:'additional'},{id:'b',name:'가상 학생 B',lessonKind:'makeup'}];const date=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());const session={id:'s',date,startTime:'14:00',endTime:'15:30',kind:'additional',subjectId:'english',subject:'영어',teacherId:'t',teacherName:'가상 선생님',room:'101',students};window.calls=[];window.saved=0;const query={select(){return this},eq(){return this},order(){return this},then(resolve){resolve({data:[{id:'english',name:'영어',main_subject:'영어'}]})}};const supabase={from:()=>query,rpc:async(name,args)=>{window.calls.push({name,args});if(name==='staff_teacher_special_lessons')return {data:[session]};if(name==='staff_special_lesson_student_options')return {data:[...students,{id:'c',name:'가상 학생 C'}]};if(name==='staff_special_absence_options')return {data:[{source:'regular',sourceId:'absence',date:'2026-09-18',title:'영어 결석'}]};if(name==='staff_save_mixed_special_lesson'){window.saved++;return {data:'s'}}throw Error('Unexpected RPC '+name)}};const root=createRoot(document.getElementById('root'));window.render=(edit=true)=>root.render(<TeacherSpecialLessons key={Math.random()} supabase={supabase} profile={{id:'t',role:'admin'}} editorSessionId={edit?'s':undefined} onEditorSaved={()=>{}}/>);window.render();`;
await esbuild.build({stdin:{contents:entry,resolveDir:process.cwd(),loader:'tsx'},bundle:true,outfile:'/tmp/hsm-mixed-ui.js',jsx:'automatic'});
let fonts='';if(process.env.HSM_FONT_DIR)for(const w of [400,500,600,700,800,900])fonts+=fs.readFileSync(`${process.env.HSM_FONT_DIR}/${w}.css`,'utf8').replaceAll('./files/',`file://${process.env.HSM_FONT_DIR}/files/`);
const layout=fs.readFileSync('app/layout.tsx','utf8');const files=[...layout.matchAll(/import ["']\.\/([^"']+\.css)["']/g)].map(m=>'app/'+m[1]);const css=[...files,'/tmp/hsm-mixed-ui.css'].map(f=>fs.readFileSync(f,'utf8').replace('@import "tailwindcss";','')).join('\n');fs.writeFileSync('/tmp/hsm-mixed-ui.html',`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*,*::before,*::after{box-sizing:border-box}body{margin:0}${fonts}\n${css}</style><div id="root"></div><script src="file:///tmp/hsm-mixed-ui.js"></script></html>`);
const browser=await chromium.launch({executablePath:process.env.HSM_CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu','--no-zygote'],headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///tmp/hsm-mixed-ui.html');
for(const width of [320,390,1440]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>window.render());const group=page.getByRole('group',{name:'가상 학생 B 수업 구분'});await group.waitFor();await page.getByLabel('가상 학생 B 결석 수업 연결').selectOption('regular:absence');assert.equal(await group.getByRole('button',{name:'보강',exact:true}).getAttribute('aria-pressed'),'true');await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const bounds=await group.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width);await group.scrollIntoViewIfNeeded();if(width===390)await page.screenshot({path:'/tmp/hsm-mixed-mobile.png'});if(width===1440)await page.screenshot({path:'/tmp/hsm-mixed-desktop.png'});}
await page.getByRole('button',{name:'일정 저장',exact:true}).click();await page.waitForFunction(()=>window.saved===1);const call=await page.evaluate(()=>window.calls.find(c=>c.name==='staff_save_mixed_special_lesson'));assert.equal(call.args.p_values.p_id,'s');assert.deepEqual(call.args.p_values.p_expected_student_ids,['a','b']);assert.deepEqual(JSON.parse(JSON.stringify(call.args.p_students)),[{studentId:'a',kind:'additional'},{studentId:'b',kind:'makeup',source:'regular',sourceId:'absence'}]);await page.evaluate(()=>window.render(false));await page.getByRole('button',{name:'＋ 일정 등록',exact:true}).click();await page.getByLabel(/^과목/).selectOption('english');await page.getByRole('button',{name:/가상 학생 C/}).click();await page.getByLabel(/^시작 시간/).fill('1400');await page.getByLabel(/^종료 시간/).fill('1530');await page.getByLabel(/^종료 시간/).blur();await page.getByRole('button',{name:'이 수업에 학생 추가',exact:true}).click();assert.equal(await page.getByRole('group',{name:'가상 학생 A 수업 구분'}).getByRole('button',{name:'추가수업',exact:true}).getAttribute('aria-pressed'),'true');assert.equal(await page.getByRole('group',{name:'가상 학생 C 수업 구분'}).getByRole('button',{name:'보강',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'일정 저장',exact:true}).click();await page.waitForFunction(()=>window.saved===2);const join=await page.evaluate(()=>window.calls.filter(c=>c.name==='staff_save_mixed_special_lesson').at(-1));assert.equal(join.args.p_values.p_id,'s');assert.deepEqual(join.args.p_students.map(s=>s.studentId),['a','b','c']);assert.deepEqual(errors,[]);console.log('PASS: actual mixed editor at 320/390/1440px; per-student choice, absence selection, exact save payload; no browser errors.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
