const {PGlite}=require(process.env.HSM_PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict');const read=f=>fs.readFileSync(f,'utf8');const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
(async()=>{const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select '${id(1)}'::uuid$$;`);
await db.exec(read('tests/special-record/mixed-schema.sql'));
await db.exec(`create function is_staff() returns boolean language sql as $$select true$$;create function current_user_role() returns user_role language sql as $$select coalesce(nullif(current_setting('test.role',true),''),'admin')::user_role$$;
create function can_send_alimtalk() returns boolean language sql as $$select true$$;
create function internal_family_student_id(uuid) returns uuid language sql as $$select $1$$;
create function correction_time_start(time,smallint) returns time language sql as $$select $1$$;
create function correction_time_end(time,smallint) returns time language sql as $$select $1$$;
alter table teacher_special_lessons alter column id set default gen_random_uuid();alter table teacher_special_lessons alter column status set default 'draft';
alter table teacher_special_lesson_students add primary key(session_id,student_id);
insert into profiles(id,display_name,role,is_active) values('${id(1)}','가상 선생님','admin',true);
insert into students(id,name,status) values('${id(2)}','가상 학생 A','active'),('${id(3)}','가상 학생 B','active');
insert into academy_subjects(id,name,main_subject,active) values('${id(4)}','영어','영어',true);
insert into classes(id,name,subject,subject_id) values('${id(5)}','가상 클래스','영어','${id(4)}');
insert into lessons(id,class_id,lesson_date,starts_at,status) values('${id(6)}','${id(5)}',current_date-1,now()-interval '1 day','completed');
insert into attendance(id,lesson_id,student_id,status) values('${id(7)}','${id(6)}','${id(3)}','absent');`);
await db.exec(read('tests/special-record/mixed-existing-functions.sql'));
await db.exec(read('supabase/migrations/20260919093601_mixed_special_lesson_students.sql'));
await db.exec('create trigger test_student_conflict before insert or update on teacher_special_lesson_students for each row execute function prevent_special_lesson_student_conflict(); create trigger test_session_conflict before update on teacher_special_lessons for each row execute function prevent_special_lesson_time_conflict();');
const date=(await db.query('select current_date::text d')).rows[0].d;
const values={p_id:null,p_teacher_id:id(1),p_date:date,p_start_time:'14:00',p_end_time:'15:30',p_kind:'additional',p_subject_id:id(4),p_room:'101',p_note:null,p_reminder_recipient_ids:[id(1)]};
const participants=[{studentId:id(2),kind:'additional'},{studentId:id(3),kind:'makeup',source:'regular',sourceId:id(7)}];
const save=async(v=values,p=participants)=>(await db.query('select staff_save_mixed_special_lesson($1,false,$2) id',[JSON.stringify(v),JSON.stringify(p)])).rows[0].id;
const sid=await save();assert.ok(sid);values.p_id=sid;
let students=(await db.query('select staff_teacher_special_lessons(null) s')).rows[0].s[0].students;assert.equal(students[0].lessonKind,'additional');assert.equal(students[1].lessonKind,'makeup');
const board=async()=>(await db.query('select absence_makeup_board() b')).rows[0].b.items;
assert.equal((await board()).find(i=>i.sourceId===id(7)).status,'scheduled');
await db.query("update teacher_special_lesson_students set attendance_status='present',lesson_content='보존할 기록' where session_id=$1",[sid]);
await db.query("select staff_set_special_lesson_state($1,'completed')",[sid]);assert.equal((await board()).find(i=>i.sourceId===id(7)).status,'completed');
await db.exec(`create function student_attends_class_on(uuid,uuid,date) returns boolean language sql as $$select false$$;
create function staff_student_learning_history(uuid,integer) returns jsonb language sql as $$select '[]'::jsonb$$;
create function family_student_context(uuid) returns jsonb language sql as $$select '{}'::jsonb$$;
create function family_live_dashboard(uuid) returns jsonb language sql as $$select jsonb_build_object('selectedStudent',jsonb_build_object('id',$1))$$;`);
for(const [student,label] of [[id(2),'추가수업'],[id(3),'보강']]){
 const today=(await db.query('select family_today_lessons($1) r',[student])).rows[0].r;assert.equal(today.find(r=>r.id==='special:'+sid).label,label);
 await db.query('select family_summary_snapshot($1,current_date,current_date)',[student]);
 await db.query('select family_learning_calendar_schedule($1,current_date)',[student]);
 await db.query("select family_previous_homework($1,$2,'lesson')",[student,sid]);
 await db.query('select staff_student_special_lesson_insights($1)',[student]);
 await db.query('select staff_student_completed_learning_history($1,10)',[student]);
 await db.query('select staff_student_attendance_makeup_history($1)',[student]);
}
let sources=(await db.query('select * from internal_alimtalk_report_sources($1,current_date,current_date)',[[id(2),id(3)]])).rows;assert.equal(sources.find(r=>r.student_id===id(2)).lessons[0].source,'extra');assert.equal(sources.find(r=>r.student_id===id(3)).lessons[0].source,'makeup');
await assert.rejects(save(values,[participants[0]]),/기록이 있는 학생/);
await assert.rejects(save({...values,p_expected_student_ids:[]}),/참여 학생이 변경/);
await assert.rejects(db.query("insert into makeup_sessions(attendance_id,status) values($1,'scheduled')",[id(7)]),/연결된 결석/);
await save();assert.equal((await db.query('select count(*)::int n from teacher_special_lessons')).rows[0].n,1);assert.equal((await db.query('select lesson_content from teacher_special_lesson_students where student_id=$1',[id(3)])).rows[0].lesson_content,'보존할 기록');
await assert.rejects(save({...values,p_id:null,p_start_time:'16:00',p_end_time:'17:30'}),/결석/);
await assert.rejects(save(values,[participants[0],{...participants[1],kind:'additional'}]),/결석 연결/);
await db.exec("select set_config('test.role','teacher',false)");await assert.rejects(save({...values,p_teacher_id:id(99)}),/권한/);
assert.equal((await db.query("select has_function_privilege('anon','staff_save_mixed_special_lesson(jsonb,boolean,jsonb)','execute') ok")).rows[0].ok,false);
console.log('PASS: mixed kinds, absence linking, completion, per-student alimtalk, existing-record preservation, duplicate links and unauthorized writes.');await db.close();})().catch(e=>{console.error(e.message);process.exit(1)});
