const {PGlite}=require(process.env.HSM_PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict');const read=f=>fs.readFileSync(f,'utf8');const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
(async()=>{const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select '${id(1)}'::uuid$$;`);
await db.exec(read('tests/special-record/mixed-schema.sql'));
await db.exec(`create function is_staff() returns boolean language sql as $$select true$$;create function current_user_role() returns user_role language sql as $$select coalesce(nullif(current_setting('test.role',true),''),'admin')::user_role$$;
create function can_send_alimtalk() returns boolean language sql as $$select true$$;
create function internal_family_student_id(uuid) returns uuid language sql as $$select $1$$;
create function correction_time_start(time,smallint) returns time language sql as $$select $1$$;
create function correction_time_end(time,smallint) returns time language sql as $$select $1$$;
alter table teacher_special_lessons alter column id set default gen_random_uuid();alter table teacher_special_lessons alter column status set default 'draft';
alter table teacher_special_lesson_students add primary key(session_id,student_id);
insert into profiles(id,display_name,role,is_active) values('${id(1)}','가상 선생님','admin',true);
insert into students(id,name,status) values('${id(2)}','가상 학생 A','active'),('${id(3)}','가상 학생 B','active');
insert into academy_subjects(id,name,main_subject,active) values('${id(4)}','영어','영어',true);
insert into classes(id,name,subject,subject_id) values('${id(5)}','가상 클래스','영어','${id(4)}');
insert into lessons(id,class_id,lesson_date,starts_at,status) values('${id(6)}','${id(5)}',current_date-1,now()-interval '1 day','completed');
insert into attendance(id,lesson_id,student_id,status) values('${id(7)}','${id(6)}','${id(3)}','absent');`);
await db.exec(read('tests/special-record/mixed-existing-functions.sql'));
await db.exec(read('supabase/migrations/20260919093601_mixed_special_lesson_students.sql'));
await db.exec('create trigger test_student_conflict before insert or update on teacher_special_lesson_students for each row execute function prevent_special_lesson_student_conflict(); create trigger test_session_conflict before update on teacher_special_lessons for each row execute function prevent_special_lesson_time_conflict();');
const date=(await db.query('select current_date::text d')).rows[0].d;
const values={p_id:null,p_teacher_id:id(1),p_date:date,p_start_time:'14:00',p_end_time:'15:30',p_kind:'additional',p_subject_id:id(4),p_room:'101',p_note:null,p_reminder_recipient_ids:[id(1)]};
const participants=[{studentId:id(2),kind:'additional'},{studentId:id(3),kind:'makeup',source:'regular',sourceId:id(7)}];
const save=async(v=values,p=participants)=>(await db.query('select staff_save_mixed_special_lesson($1,false,$2) id',[JSON.stringify(v),JSON.stringify(p)])).rows[0].id;

await db.exec(read('supabase/migrations/20261002124343_special_overlap_confirmation.sql'));
const sid=await save();
const overlapping={...values,p_start_time:'14:30',p_end_time:'16:00'};
const people=[{studentId:id(2),kind:'additional'}];
let conflict;try{await save(overlapping,people)}catch(e){conflict=e}
assert.equal(conflict.code,'PT409');assert.ok(conflict.detail);assert.match(conflict.message,/학생/);
assert.equal((await db.query('select count(*)::int n from teacher_special_lessons')).rows[0].n,1);
const confirmed=await save({...overlapping,p_overlap_token:conflict.detail},people);assert.ok(confirmed);
await db.query("update teacher_special_lesson_students set attendance_status='present',lesson_content='겹침 수업 기록' where session_id=$1",[confirmed]);
assert.ok((await db.query('select overlap_notice from teacher_special_lessons where id=$1',[confirmed])).rows[0].overlap_notice);
assert.ok((await db.query('select staff_teacher_special_lessons(null) s')).rows[0].s.find(x=>x.id===confirmed).overlapNotice);
await assert.rejects(save({...overlapping,p_overlap_token:conflict.detail},people),/이미 등록/);
await assert.rejects(save({...overlapping,p_start_time:'14:40',p_overlap_token:conflict.detail},people),e=>e.code==='PT409');
await db.exec("set test.role='teacher'");await assert.rejects(save({...overlapping,p_teacher_id:id(99),p_overlap_token:conflict.detail},people),/권한/);
assert.equal((await db.query("select has_function_privilege('authenticated','internal_save_mixed_special_lesson(jsonb,boolean,jsonb)','execute') ok")).rows[0].ok,false);
assert.equal((await db.query("select has_function_privilege('anon','staff_save_mixed_special_lesson(jsonb,boolean,jsonb)','execute') ok")).rows[0].ok,false);
assert.ok(!(await db.query("select current_setting('app.special_overlap_actor',true) v")).rows[0].v);
console.log('PASS: conflict prompt, confirmed save, badge persistence, duplicate rejection, stale token, authorization, private RPC and context cleanup');await db.close();})().catch(e=>{console.error(e);process.exit(1)});
