// Synthetic in-memory PostgreSQL only: no production credentials or student records.
const {PGlite}=require(process.env.HSM_PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict');
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
(async()=>{const db=new PGlite();await db.exec(`
create role anon;create role authenticated;create schema auth;
create function auth.uid() returns uuid language sql as $$select '${id(1)}'::uuid$$;
create function is_staff() returns boolean language sql as $$select true$$;
create function current_user_role() returns text language sql as $$select 'admin'::text$$;
create type attendance_status as enum('present','late','absent','excused');
create table classes(id uuid primary key,room text);
create table class_teachers(class_id uuid,profile_id uuid);
create table profiles(id uuid primary key,display_name text);
create table class_schedules(id uuid primary key,class_id uuid,weekday smallint,start_time time,end_time time,valid_from date,valid_until date);
create table class_makeup_attendees(class_id uuid,attendance_date date);
create table students(id uuid primary key,name text,school text,grade text);
create function student_attends_class_on(uuid,uuid,date) returns boolean language sql as $$select true$$;
create table class_lesson_roster_overrides(class_id uuid,lesson_date date,student_id uuid);
create table lessons(id uuid primary key default gen_random_uuid(),class_id uuid,lesson_date date,starts_at timestamptz,ends_at timestamptz,room text,status text default 'draft',teacher_profile_id uuid,updated_at timestamptz,lesson_content text,revision_draft jsonb,revision_saved_at timestamptz,revision_saved_by uuid,unique(class_id,starts_at));
create table attendance(id uuid default gen_random_uuid(),lesson_id uuid,student_id uuid,status attendance_status,checked_at timestamptz,note text,makeup_required boolean,late_minutes int,absence_reason text,unique(lesson_id,student_id));
create table lesson_exam_results(id uuid primary key default gen_random_uuid(),lesson_id uuid,student_id uuid,exam_type text,exam_title text,score numeric,max_score numeric,evaluation text,feedback text,created_by uuid,created_at timestamptz default now(),updated_at timestamptz default now());
create table lesson_homework_results(id uuid default gen_random_uuid(),lesson_id uuid,student_id uuid,lesson_content text,assigned_homework text,inspection_status text,inspection_note text,status text,note text,created_by uuid,updated_at timestamptz,unique(lesson_id,student_id));
create table class_lesson_revision_drafts(lesson_id uuid primary key,payload jsonb,saved_at timestamptz,saved_by uuid);
create table class_daily_notices(class_id uuid,notice_date date,content text,created_by uuid,updated_at timestamptz,unique(class_id,notice_date));
insert into classes values('${id(2)}','101');insert into students values('${id(3)}','가상 학생','가상 학교','고2');
insert into class_schedules values('${id(4)}','${id(2)}',6,'12:30','14:00',null,null);
`);
await db.exec(fs.readFileSync('supabase/migrations/20260911234033_class_record_conflict_protection.sql','utf8'));
await db.exec(fs.readFileSync('tests/class-record/identity-existing-writers.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260919090843_stabilize_class_record_lesson_identity.sql','utf8'));
const save=async()=> (await db.query('select staff_save_class_day($1,$2,null,null,null) id',[id(2),'2026-09-19'])).rows[0].id;
const snapshot=async()=> (await db.query('select staff_class_edit_snapshot($1,$2) s',[id(2),'2026-09-19'])).rows[0].s;
const patch=async(changes,state,mode)=>(await db.query('select staff_patch_class_record($1,$2,$3,$4,$5) s',[id(2),'2026-09-19',JSON.stringify(changes),state,mode])).rows[0].s;
const change=(field,before,value)=>({path:['students',id(3),field],before,value});
const first=await save();await db.exec("update class_schedules set start_time='14:00',end_time='15:30'");
assert.equal(await save(),first,'time change must keep the original lesson identity');
assert.equal((await db.query('select count(*)::int n from lessons')).rows[0].n,1);
await patch([change('status',null,'present'),change('exam_examType','','영단어 시험'),change('exam_score','','96'),change('assignedHomework','','가상 숙제')],'draft','complete');
let s=await snapshot();assert.equal(s.state,'completed');assert.equal(s.values.students[id(3)].exam_score,'96');
// Reproduce the historical split: an earlier empty draft and a later completed report.
await db.query("update lessons set starts_at='2026-09-19 14:00+09' where id=$1",[first]);
await db.query("insert into lessons(id,class_id,lesson_date,starts_at,status) values($1,$2,'2026-09-19','2026-09-19 12:30+09','draft')",[id(10),id(2)]);
s=await snapshot();assert.equal(s.day.lessonId,first);assert.equal(s.values.students[id(3)].exam_score,'96');assert.equal(s.values.students[id(3)].assignedHomework,'가상 숙제');assert.equal(await save(),first);
const examId=s.values.students[id(3)].exam_id;
s=await patch([change('exam_score','96','97'),change('exam_id',examId,examId)],'completed','revision');
assert.equal(s.values.students[id(3)].exam_score,'97');assert.equal((await db.query('select score from lesson_exam_results where id=$1',[examId])).rows[0].score,'96');
s=await patch([],'completed','publish');assert.equal(s.values.students[id(3)].exam_score,'97');assert.equal(s.revision,null);
assert.equal((await db.query('select count(*)::int n from lesson_exam_results')).rows[0].n,1,'publish must update the displayed exam rather than add a duplicate');
assert.equal((await db.query('select count(*)::int n from lessons')).rows[0].n,2,'historical records must not be deleted');
await assert.rejects(patch([change('assignedHomework','','stale')],'draft','draft'),/완료 상태/);
await db.exec('delete from class_schedules');assert.equal(await save(),first,'saved lessons remain editable after weekday changes');
await db.exec("create or replace function current_user_role() returns text language sql as $$select 'teacher'::text$$");
await assert.rejects(save(),/담당 클래스/);await assert.rejects(snapshot(),/담당 클래스/);
assert.equal((await db.query("select has_function_privilege('authenticated','internal_class_record_lesson_id(uuid,date)','execute') allowed")).rows[0].allowed,false);
console.log('PASS: timetable changes retain lesson ID; split records read completed report; private revision/publish preserve exam ID; no deletion/duplication; stale saves and unauthorized access rejected.');await db.close();})().catch(e=>{console.error(e);process.exit(1)});
