// Isolated UI test: mock RPC only. No real students or schedules are changed.
const fs=require('node:fs'),assert=require('node:assert/strict'),esbuild=require('esbuild');
const {chromium}=require(process.env.HSM_PLAYWRIGHT_MODULE||'playwright');
(async()=>{const source=fs.readFileSync('app/teacher-schedule-hub.tsx','utf8');const editor=source.slice(source.indexOf('function ClassEditor('),source.indexOf('\nfunction CorrectionEditor('));const helpers=source.slice(source.indexOf('function EditorModal('),source.indexOf('function getMonday()'));const saveError=source.slice(source.indexOf('function saveErrorMessage('),source.indexOf('\nfunction Empty('));
const entry=`import React,{useState,useEffect,useMemo} from 'react';import {createRoot} from 'react-dom/client';import {MilitaryTimeInput,isMilitaryTime} from './app/military-time-input';import {ClassScheduleSwap} from './app/class-schedule-swap';import swapStyles from './app/class-schedule-swap.module.css';const weekdays=['월','화','수','목','금','토','일'];const appConfirm=async()=>true;${editor}\n${helpers}\n${saveError}\n
const row={id:'a',classId:'c1',className:'고3 영어',weekday:6,startTime:'14:00',endTime:'15:30',teachers:[{id:'t',name:'가상 선생님'}],students:[],room:'101'};const target={...row,id:'b',classId:'c2',className:'군서고2',startTime:'12:30',endTime:'14:00'};window.calls=[];window.fail=false;window.delay=0;window.saved=0;window.closeCount=0;const client={rpc:async(name,args)=>{window.calls.push({name,args});await new Promise(r=>setTimeout(r,window.delay));return {error:window.fail?{message:'다른 선생님이 수업 시간을 변경했습니다.'}:null};}};const root=createRoot(document.getElementById('root'));window.render=(mode='normal')=>{const others=mode==='conflict'?[{...row,id:'c',classId:'c3',className:'겹치는 수업',startTime:'12:45',endTime:'13:00'}]:[];root.render(<ClassEditor key={Math.random()} supabase={client} row={row} data={{classes:[{id:'c1',name:'고3 영어'}],teachers:row.teachers,classSchedules:[row,...(mode==='empty'?[]:[target]),{...target,id:'other-day',weekday:1,className:'월요일 수업'},...others]}} onSaved={async()=>{window.saved++}} onClose={()=>window.closeCount++}/>)};window.render();`;
await esbuild.build({stdin:{contents:entry,resolveDir:process.cwd(),loader:'tsx'},bundle:true,outfile:'/tmp/hsm-swap-ui.js',jsx:'automatic'});
const globals=fs.readFileSync('app/globals.css','utf8').replace('@import "tailwindcss";','');const css=fs.readFileSync('/tmp/hsm-swap-ui.css','utf8');let fonts='';if(process.env.HSM_FONT_DIR){for(const weight of [400,500,600,700])fonts+=fs.readFileSync(`${process.env.HSM_FONT_DIR}/${weight}.css`,'utf8').replaceAll('./files/',`file://${process.env.HSM_FONT_DIR}/files/`);}
fs.writeFileSync('/tmp/hsm-swap-ui.html',`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${fonts}\n${globals}\n${css}</style><div id="root"></div><script src="file:///tmp/hsm-swap-ui.js"></script></html>`);
const browser=await chromium.launch({executablePath:process.env.HSM_CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote'],headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///tmp/hsm-swap-ui.html');
for(const width of [320,390,1440]){await page.setViewportSize({width,height:900});await page.evaluate(()=>window.render());await page.getByRole('button',{name:'다른 수업과 시간 맞바꾸기'}).click();const select=page.getByLabel('맞바꿀 수업');assert.equal(await select.locator('option').count(),2);await select.selectOption('b');await page.evaluate(()=>document.fonts.ready);const preview=page.getByLabel('변경 전후 시간');assert.match(await preview.textContent(),/12:30–14:00/);assert.match(await preview.textContent(),/14:00–15:30/);const box=await page.getByLabel('수업 시간 맞바꾸기').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(width===390)await page.screenshot({path:'/tmp/hsm-swap-mobile.png'});if(width===1440)await page.screenshot({path:'/tmp/hsm-swap-desktop.png'});}
await page.evaluate(()=>{window.delay=1500;window.fail=true;});await page.getByRole('button',{name:'맞바꾸기 적용'}).click();assert.equal(await page.getByRole('button',{name:'적용 중…'}).isDisabled(),true);await page.getByRole('button',{name:'닫기',exact:true}).click();assert.equal(await page.evaluate(()=>window.closeCount),0);await page.getByRole('alert').waitFor();assert.equal(await page.evaluate(()=>window.saved),0);assert.equal(await page.getByLabel('맞바꿀 수업').inputValue(),'b');await page.evaluate(()=>{window.fail=false;window.delay=0});await page.getByRole('button',{name:'맞바꾸기 적용'}).click();await page.waitForFunction(()=>window.saved===1);const calls=await page.evaluate(()=>window.calls);assert.equal(calls.length,2);assert.equal(calls[1].name,'staff_swap_class_schedule_times');assert.equal(calls[1].args.p_first_base.weekday,6);assert.equal(calls[1].args.p_second_base.startTime,'12:30');
await page.evaluate(()=>window.render('conflict'));await page.getByRole('button',{name:'다른 수업과 시간 맞바꾸기'}).click();await page.getByLabel('맞바꿀 수업').selectOption('b');assert.match(await page.getByRole('alert').textContent(),/겹치는/);assert.equal(await page.getByRole('button',{name:'맞바꾸기 적용'}).isDisabled(),true);
await page.getByRole('button',{name:'돌아가기'}).click();assert.equal(await page.getByRole('button',{name:'변경사항 저장'}).count(),1);
await page.evaluate(()=>window.render('empty'));await page.getByRole('button',{name:'다른 수업과 시간 맞바꾸기'}).click();assert.equal(await page.getByRole('button',{name:'맞바꾸기 적용'}).isDisabled(),true);assert.deepEqual(errors,[]);console.log('PASS: actual ClassEditor integration at 320/390/1440px; same-day choices, preview, RPC snapshots, pending guard, stale error/retry, conflict block, cancel, empty state.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
