// Run with HSM_PGLITE_MODULE pointing to an installed @electric-sql/pglite.
// All fixtures live in an in-memory database. Never connects to production.
const {PGlite}=require(process.env.HSM_PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict');
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
(async()=>{const db=new PGlite();await db.exec(`
create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create function public.is_staff() returns boolean language sql as $$select coalesce(current_setting('test.staff',true),'false')='true'$$;
create function public.current_user_role() returns text language sql as $$select 'teacher'::text$$;
create table classes(id uuid primary key,name text,room text,active boolean default true);
create table profiles(id uuid primary key,display_name text);
create table class_teachers(class_id uuid,profile_id uuid);
create table class_schedules(id uuid primary key default gen_random_uuid(),class_id uuid references classes,weekday smallint check(weekday between 1 and 7),start_time time,end_time time);
create table students(id uuid primary key,name text);
create table enrollments(student_id uuid,class_id uuid,status text);
create table student_schedule_assignments(student_id uuid,class_schedule_id uuid references class_schedules);
create table correction_assignments(id uuid,student_id uuid,active boolean,weekday smallint,subject text,start_time time,end_time time,slot_index smallint);
create table correction_schedule_exceptions(assignment_id uuid,kind text,target_date date,target_start_time time,target_end_time time);
`);
await db.exec(fs.readFileSync('tests/schedule-swap/existing-functions.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20260919160338_swap_class_schedule_times.sql','utf8'));
await db.exec(`create trigger class_teachers_prevent_conflict before insert or update on class_teachers for each row execute function prevent_class_schedule_conflict();`);
const reset=async()=>{await db.exec(`truncate student_schedule_assignments,class_schedules,class_teachers,classes,profiles,students,enrollments,correction_assignments,correction_schedule_exceptions cascade;select set_config('test.uid','${id(99)}',false),set_config('test.staff','true',false);
insert into classes values('${id(1)}','A','101',true),('${id(2)}','B','101',true),('${id(3)}','C','102',true);
insert into profiles values('${id(9)}','가상 선생님');insert into class_teachers values('${id(1)}','${id(9)}'),('${id(2)}','${id(9)}');
insert into class_schedules values('${id(11)}','${id(1)}',6,'14:00','15:30'),('${id(12)}','${id(2)}',6,'12:30','14:00'),('${id(13)}','${id(1)}',1,'14:00','15:30');
insert into students values('${id(50)}','가상 학생');insert into enrollments values('${id(50)}','${id(1)}','active'),('${id(50)}','${id(2)}','active');insert into student_schedule_assignments values('${id(50)}','${id(11)}'),('${id(50)}','${id(12)}');`)};
const base=async n=>(await db.query(`select jsonb_build_object('weekday',weekday,'startTime',to_char(start_time,'HH24:MI'),'endTime',to_char(end_time,'HH24:MI'),'teacherIds',coalesce((select jsonb_agg(profile_id::text order by profile_id) from class_teachers where class_id=s.class_id),'[]'::jsonb)) b from class_schedules s where id=$1`,[id(n)])).rows[0]?.b;
const times=async()=>(await db.query('select id,weekday,start_time,end_time from class_schedules order by id')).rows;
const swap=async(a,b)=>db.query('select staff_swap_class_schedule_times($1,$2,$3::jsonb,$4::jsonb)',[id(11),id(12),JSON.stringify(a??await base(11)),JSON.stringify(b??await base(12))]);
let count=0;const reject=async(re,fn=swap)=>{const before=await times();await assert.rejects(fn,re);assert.deepEqual(await times(),before);count++};
await reset();await swap();assert.equal((await times())[0].start_time,'12:30:00');assert.equal((await times())[1].start_time,'14:00:00');assert.equal((await times())[2].start_time,'14:00:00');assert.equal((await db.query('select count(*)::int n from student_schedule_assignments')).rows[0].n,2);count++;
await reset();await db.exec(`update class_schedules set end_time='15:00' where id='${id(11)}'`);await swap();assert.equal((await times())[0].end_time,'13:30:00');count++;
await reset();await db.exec(`update class_schedules set end_time='16:30' where id='${id(11)}'`);await reject(/충돌|같은 시간|겹치/);
await reset();await db.exec(`insert into class_schedules values('${id(14)}','${id(1)}',6,'16:00','17:00');update class_schedules set start_time='11:30' where id='${id(12)}'`);await reject(/충돌|같은 시간|겹치/);
await reset();await db.exec(`update classes set room='102' where id='${id(1)}';insert into class_schedules values('${id(14)}','${id(3)}',6,'12:30','14:00')`);await reject(/강의실/);
await reset();await db.exec(`insert into class_schedules values('${id(14)}','${id(3)}',6,'12:30','14:00');insert into class_teachers values('${id(3)}','${id(90)}');update class_teachers set profile_id='${id(90)}' where class_id='${id(1)}'`);await reject(/선생님/);
await reset();await db.exec(`insert into class_schedules values('${id(14)}','${id(3)}',6,'12:30','14:00');insert into enrollments values('${id(50)}','${id(3)}','active');delete from student_schedule_assignments where class_schedule_id='${id(12)}';insert into student_schedule_assignments values('${id(50)}','${id(14)}')`);await reject(/학생 시간 충돌/);
await reset();await db.exec(`delete from enrollments where class_id='${id(2)}';insert into correction_assignments values('${id(60)}','${id(50)}',true,6,'영어','12:30','14:00',0)`);await reject(/첨삭/);
await reset();let old=await base(11);await db.exec(`update class_schedules set end_time='15:00' where id='${id(11)}'`);await reject(/다른 선생님/,()=>swap(old));
await reset();old=await base(12);await db.exec(`update class_teachers set profile_id='${id(90)}' where class_id='${id(2)}'`);await reject(/다른 선생님/,()=>swap(undefined,old));
await reset();await db.exec(`update class_schedules set weekday=5 where id='${id(12)}'`);await reject(/같은 요일/);
await reset();await db.exec(`update class_schedules set start_time='23:00',end_time='23:30' where id='${id(12)}'`);await reject(/자정/);
await reset();await db.exec(`select set_config('test.uid','',false)`);await reject(/권한/);
await reset();await db.exec(`select set_config('test.staff','false',false)`);await reject(/권한/);
await reset();await reject(/서로 다른/,()=>db.query('select staff_swap_class_schedule_times($1,$1,null,null)',[id(11)]));
await reset();await reject(/같은 시간|충돌|겹치/,()=>db.exec(`update class_schedules set start_time='13:00' where id='${id(11)}'`));
await reset();await db.query('select staff_guard_class_schedule($1,$2,$3::jsonb,$4::jsonb)',[id(11),id(1),JSON.stringify(await base(11)),JSON.stringify({weekday:6,startTime:'15:00',endTime:'16:30',teacherIds:[id(9)]})]);assert.equal((await times())[0].start_time,'15:00:00');count++;
assert.equal((await db.query("select has_function_privilege('anon','staff_swap_class_schedule_times(uuid,uuid,jsonb,jsonb)','execute') allowed")).rows[0].allowed,false);
console.log(`PASS: ${count} database cases (atomic swap/rollback, durations, weekday, student/teacher/room/correction conflicts, stale state, authorization, ordinary edits).`);await db.close();})().catch(e=>{console.error(e);process.exit(1)});
