"use client";

import type { FormEvent } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import styles from "./communication-board.module.css";

type Role="student"|"guardian"|"teacher";
type Status="unsent"|"sent"|"joined"|"failed";
type TargetMode="individual"|"class"|"grade"|"school"|"all";
type SendMode="new"|"resend";
type Named={id:string;name:string};
type Student={id:string;name:string;school:string|null;grade:string|null;classIds:string[];classNames:string[];hasStudentAccount:boolean;hasStudentPhone:boolean;guardianName:string|null;guardianId:string|null;guardianFamilyKey:string|null;hasGuardianAccount:boolean;hasGuardianPhone:boolean};
type Invite={id:string;role:Role;studentId:string|null;studentIds:string[];targetName:string;studentName:string|null;maskedPhone:string|null;codeHint:string;createdAt:string;expiresAt:string;smsSentAt:string|null;smsAttempts:number;smsLastError:string|null;usedAt:string|null;revokedAt:string|null;status:Status};
type Board={students:Student[];invites:Invite[];classes:Named[];grades:string[];schools:string[]};
const roleLabels:Record<Role,string>={student:"학생",guardian:"학부모",teacher:"선생님"};
const statusLabels:Record<Status,string>={unsent:"미발송",sent:"발송완료",joined:"가입완료",failed:"발송실패"};
const modeLabels:Record<TargetMode,string>={individual:"개별 선택",class:"클래스별",grade:"학년별",school:"학교별",all:"전체"};

export function AccountInviteSmsBoard({supabase}:{supabase:SupabaseClient}){
  const [data,setData]=useState<Board>({students:[],invites:[],classes:[],grades:[],schools:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [historyRole,setHistoryRole]=useState<Role|"all">("all"),[historyStatus,setHistoryStatus]=useState<Status|"all">("all"),[historyQuery,setHistoryQuery]=useState("");
  const [composer,setComposer]=useState(false);
  const load=useCallback(async()=>{setLoading(true);const{data:next,error:loadError}=await supabase.rpc("admin_account_invite_sms_board");if(loadError||!next)setError(loadError?.message??"초대 문자 내역을 불러오지 못했습니다.");else{setData(next as Board);setError("")}setLoading(false)},[supabase]);
  useEffect(()=>{void load()},[load]);
  const counts=useMemo(()=>data.invites.reduce((result,row)=>{result[row.status]++;return result},{unsent:0,sent:0,joined:0,failed:0} as Record<Status,number>),[data.invites]);
  const visible=data.invites.filter(row=>(historyRole==="all"||row.role===historyRole)&&(historyStatus==="all"||row.status===historyStatus)&&(!historyQuery.trim()||`${row.targetName} ${row.studentName??""}`.includes(historyQuery.trim())));
  return <section className={styles.inviteSmsBoard}>
    <div className={styles.messageIntro}><div><b>회원가입 초대코드 문자</b><span>조건별로 대상을 고르고 발송 여부와 가입 완료를 관리합니다.</span></div><button type="button" className="primary" onClick={()=>setComposer(true)}>＋ 대상 선택·발송</button></div>
    <div className={styles.inviteSummary}>{(["unsent","sent","joined","failed"] as Status[]).map(item=><button type="button" key={item} className={historyStatus===item?styles.selected:""} onClick={()=>setHistoryStatus(current=>current===item?"all":item)}><span>{statusLabels[item]}</span><b>{counts[item]}</b></button>)}</div>
    <div className={styles.inviteControls}><nav>{(["all","guardian","teacher","student"] as const).map(item=><button type="button" key={item} className={historyRole===item?styles.selected:""} onClick={()=>setHistoryRole(item)}>{item==="all"?"전체":roleLabels[item]}</button>)}</nav><input value={historyQuery} onChange={event=>setHistoryQuery(event.target.value)} placeholder="이름 검색"/></div>
    {(error||message)&&<p className="attendance-error">{error||message}</p>}
    {loading?<p className={styles.inviteEmpty}>초대 문자 내역을 불러오는 중이에요…</p>:visible.length===0?<p className={styles.inviteEmpty}>선택한 조건의 초대 내역이 없습니다.</p>:<div className={styles.inviteTable}>{visible.map(row=><article key={row.id}><span className={`${styles.inviteRole} ${styles[row.role]}`}>{roleLabels[row.role]}</span><div><b>{row.targetName}</b><small>{row.studentName&&row.studentName!==row.targetName?`${row.studentName} 학생 · `:""}{row.maskedPhone??(row.status==="joined"?"연락처 기록 없음":"연락처 미등록")}</small></div><span className={`${styles.inviteStatus} ${styles[row.status]}`}>{statusLabels[row.status]}</span><div className={styles.inviteDates}><small>{row.smsSentAt?`발송 ${formatDate(row.smsSentAt)}`:`발급 ${formatDate(row.createdAt)}`}</small>{row.usedAt&&<small>가입 {formatDate(row.usedAt)}</small>}{row.smsLastError&&<small className={styles.inviteError}>{row.smsLastError}</small>}</div></article>)}</div>}
    {composer&&<BulkInviteComposer board={data} supabase={supabase} onClose={()=>setComposer(false)} onSent={async text=>{setComposer(false);setMessage(text);await load()}}/>}
  </section>
}

function BulkInviteComposer({board,supabase,onClose,onSent}:{board:Board;supabase:SupabaseClient;onClose:()=>void;onSent:(message:string)=>Promise<void>}){
  const [role,setRole]=useState<Role>("guardian"),[targetMode,setTargetMode]=useState<TargetMode>("individual"),[sendMode,setSendMode]=useState<SendMode>("new"),[filters,setFilters]=useState<string[]>([]),[query,setQuery]=useState(""),[selected,setSelected]=useState<string[]>([]);
  const [teacherName,setTeacherName]=useState(""),[teacherPhone,setTeacherPhone]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState(0),[confirming,setConfirming]=useState(false);
  const latest=useMemo(()=>{const map=new Map<string,Invite>();for(const row of board.invites){if(row.role!==role)continue;for(const id of row.studentIds?.length?row.studentIds:row.studentId?[row.studentId]:[]){if(!map.has(id))map.set(id,row)}}return map},[board.invites,role]);
  const stateOf=(student:Student)=>{const joined=role==="student"?student.hasStudentAccount:student.hasGuardianAccount,hasPhone=role==="student"?student.hasStudentPhone:student.hasGuardianPhone,invite=latest.get(student.id);return{joined,hasPhone,invite,sent:Boolean(invite?.smsSentAt)}};
  const candidates=useMemo(()=>board.students.filter(student=>{if(targetMode==="class"&&!filters.some(id=>student.classIds.includes(id)))return false;if(targetMode==="grade"&&!filters.includes(student.grade??""))return false;if(targetMode==="school"&&!filters.includes(student.school??""))return false;if(query.trim()&&!`${student.name} ${student.school??""} ${student.grade??""} ${student.classNames.join(" ")} ${student.guardianName??""}`.includes(query.trim()))return false;return true}),[board.students,targetMode,filters,query]);
  const eligible=candidates.filter(student=>{const state=stateOf(student);return !state.joined&&state.hasPhone&&(sendMode==="resend"?state.sent:!state.sent)});
  const selectedEligible=selected.filter(id=>eligible.some(student=>student.id===id));
  const selectedGroups=useMemo(()=>{const groups=new Map<string,Student[]>();for(const id of selectedEligible){const student=board.students.find(item=>item.id===id);if(!student)continue;const key=role==="guardian"?(student.guardianFamilyKey||student.guardianId||student.id):student.id;groups.set(key,[...(groups.get(key)??[]),student])}return Array.from(groups.values())},[board.students,role,selectedEligible]);
  const options=targetMode==="class"?board.classes:targetMode==="grade"?board.grades.map(value=>({id:value,name:value})):targetMode==="school"?board.schools.map(value=>({id:value,name:value})):[];
  const reset=(nextRole=role)=>{setRole(nextRole);setFilters([]);setSelected([]);setQuery("");setError("")};
  const changeTarget=(mode:TargetMode)=>{setTargetMode(mode);setFilters([]);setSelected([])};
  const toggleFilter=(id:string)=>setFilters(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
  const toggleStudent=(id:string)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
  const selectEligible=()=>setSelected(eligible.map(student=>student.id));
  const sendOne=async(rows:Student[])=>{const student=rows[0],invite=latest.get(student.id);const body=sendMode==="resend"&&invite?{action:"resend",inviteId:invite.id,studentIds:rows.map(row=>row.id)}:{action:invite?"resend":"issueAndSend",inviteId:invite?.id,role,studentId:student.id,studentIds:role==="guardian"?rows.map(row=>row.id):undefined};const{error:sendError}=await supabase.functions.invoke("send-account-invite-sms",{body});if(sendError){let text=sendError.message;const context=(sendError as{context?:Response}).context;if(context)try{const result=await context.clone().json() as{error?:string};if(result.error)text=result.error}catch{}throw new Error(`${rows.map(row=>row.name).join(", ")}: ${text}`)}};
  const sendBulk=async()=>{if(role==="teacher")return;setSaving(true);setConfirming(false);setError("");setProgress(0);let sent=0,failed=0;const failures:string[]=[];for(let index=0;index<selectedGroups.length;index+=4){const groups=selectedGroups.slice(index,index+4),results=await Promise.allSettled(groups.map(sendOne));results.forEach(result=>{if(result.status==="fulfilled")sent++;else{failed++;failures.push(result.reason instanceof Error?result.reason.message:"발송 실패")}});setProgress(Math.min(index+groups.length,selectedGroups.length))}setSaving(false);if(failed){setError(`발송 ${sent}명 · 실패 ${failed}명${failures[0]?` · ${failures[0]}`:""}`);return}await onSent(`${sent}명의 학부모에게 초대코드를 발송했습니다.`)};
  const sendTeacher=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError("");const{data,error:sendError}=await supabase.functions.invoke("send-account-invite-sms",{body:{action:"issueAndSend",role:"teacher",recipientName:teacherName,recipientPhone:teacherPhone}});if(sendError){let text=sendError.message;const context=(sendError as{context?:Response}).context;if(context)try{const result=await context.clone().json() as{error?:string};if(result.error)text=result.error}catch{}setError(text);setSaving(false);return}const result=data as{recipientName?:string;recipientPhone?:string};await onSent(`${result.recipientName??teacherName}님 ${result.recipientPhone??"등록 연락처"}로 초대코드를 발송했습니다.`)};
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose()}}><section className={`student-modal ${styles.bulkInviteComposer}`} role="dialog" aria-modal="true"><header><div><p className="eyebrow">SOLAPI 초대문자</p><h2>초대 대상 선택</h2><span>가입완료·연락처 없음 대상은 자동으로 제외됩니다.</span></div><button type="button" aria-label="닫기" disabled={saving} onClick={onClose}>×</button></header><div className={styles.bulkInviteBody}>
    <section className={styles.bulkRoleTabs}>{(["guardian","teacher","student"] as Role[]).map(item=><button type="button" key={item} className={role===item?styles.on:""} onClick={()=>reset(item)}>{roleLabels[item]}</button>)}</section>
    {role==="teacher"?<form className={styles.teacherInviteForm} onSubmit={sendTeacher}><label>선생님 이름<input required value={teacherName} onChange={event=>setTeacherName(event.target.value)} placeholder="이름"/></label><label>휴대전화 번호<input required inputMode="tel" value={teacherPhone} onChange={event=>setTeacherPhone(formatPhone(event.target.value))} placeholder="010-0000-0000"/></label>{error&&<p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving}>{saving?"발송 중…":"초대코드 발급·발송"}</button></footer></form>:<>
      <section className={styles.bulkSendModes}><button type="button" className={sendMode==="new"?styles.on:""} onClick={()=>{setSendMode("new");setSelected([])}}><b>미발송자 발송</b><span>아직 문자를 받지 않은 대상</span></button><button type="button" className={sendMode==="resend"?styles.on:""} onClick={()=>{setSendMode("resend");setSelected([])}}><b>미가입자 재발송</b><span>발송했지만 가입하지 않은 대상</span></button></section>
      <nav className={styles.bulkTargetModes}>{(["individual","class","grade","school","all"] as TargetMode[]).map(item=><button type="button" key={item} className={targetMode===item?styles.on:""} onClick={()=>changeTarget(item)}>{modeLabels[item]}</button>)}</nav>
      {options.length>0&&<section className={styles.bulkFilterOptions}><header><b>{modeLabels[targetMode]} 조건</b><button type="button" onClick={()=>setFilters([])}>조건 초기화</button></header><div>{options.map(item=><button type="button" key={item.id} className={filters.includes(item.id)?styles.on:""} onClick={()=>toggleFilter(item.id)}>{item.name}</button>)}</div></section>}
      <section className={styles.bulkStudentPicker}><header><div><b>발송 대상</b><span>조건 결과 {candidates.length}명 · 발송 가능 {eligible.length}명</span></div><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="학생·학교·클래스 검색"/></header><div className={styles.bulkSelectionBar}><label><input type="checkbox" checked={eligible.length>0&&selectedEligible.length===eligible.length} onChange={()=>selectedEligible.length===eligible.length?setSelected([]):selectEligible()}/>{sendMode==="new"?"미발송자":"미가입자"} 전체 선택</label><button type="button" onClick={()=>setSelected([])}>선택 해제</button></div><div className={styles.bulkStudentList}>{candidates.map(student=>{const state=stateOf(student),enabled=!state.joined&&state.hasPhone&&(sendMode==="resend"?state.sent:!state.sent),status=state.joined?"가입완료":!state.hasPhone?"연락처 없음":state.sent?"발송완료":state.invite?.status==="failed"?"발송실패":"미발송";return <label key={student.id} className={`${selected.includes(student.id)?styles.checked:""} ${!enabled?styles.disabled:""}`}><input type="checkbox" disabled={!enabled} checked={selected.includes(student.id)} onChange={()=>toggleStudent(student.id)}/><span><b>{student.name}</b><small>{[student.school,student.grade,...student.classNames].filter(Boolean).join(" · ")||"등록 정보 없음"}{role==="guardian"&&student.guardianName?` · ${student.guardianName}`:""}</small></span><em className={state.joined?styles.done:!state.hasPhone?styles.blocked:state.sent?styles.sent:styles.ready}>{status}</em></label>})}{!candidates.length&&<p>조건에 해당하는 학생이 없습니다.</p>}</div></section>
    </>}
  </div>{role!=="teacher"&&<footer className={styles.bulkInviteFooter}><div><b>{role==="guardian"?`학부모 ${selectedGroups.length}명 · 자녀 ${selectedEligible.length}명`:`${selectedEligible.length}명 선택`}</b><span>{saving?`${progress}/${selectedGroups.length}명 처리 중`:`가입완료·연락처 없음 대상은 제외됨`}</span></div><button type="button" className="secondary-button" disabled={saving} onClick={onClose}>취소</button><button type="button" className="primary" disabled={saving||!selectedEligible.length} onClick={()=>setConfirming(true)}>{saving?"발송 중…":role==="guardian"?`학부모 ${selectedGroups.length}명에게 발송`:`${selectedEligible.length}명에게 발송`}</button></footer>}{error&&role!=="teacher"&&<p className={styles.bulkError}>{error}</p>}
  {confirming&&<div className={styles.bulkConfirm}><section><p className="eyebrow">초대문자 최종 확인</p><h3>{role==="guardian"?`학부모 ${selectedGroups.length}명에게 발송할까요?`:`${selectedEligible.length}명에게 발송할까요?`}</h3><span>{role==="guardian"&&selectedEligible.length>selectedGroups.length?`같은 연락처로 선택한 형제자매 ${selectedEligible.length}명이 학부모 계정 ${selectedGroups.length}개에 함께 연결됩니다. `:""}{sendMode==="resend"?"기존 초대코드는 폐기되고 새 코드가 발급됩니다.":"14일간 사용할 수 있는 초대코드가 발급됩니다."}</span><div><button type="button" className="secondary-button" onClick={()=>setConfirming(false)}>돌아가기</button><button type="button" className="primary" onClick={()=>void sendBulk()}>발급·발송</button></div></section></div>}
  </section></div>
}

const formatDate=(value:string)=>new Intl.DateTimeFormat("ko-KR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value));
const formatPhone=(value:string)=>{const v=value.replace(/\D/g,"").slice(0,11);if(v.length<4)return v;if(v.length<8)return `${v.slice(0,3)}-${v.slice(3)}`;return `${v.slice(0,3)}-${v.slice(3,7)}-${v.slice(7)}`};
