"use client";

import type { FormEvent } from "react";
import { useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

export function AccountRecovery({supabase,onClose}:{supabase:SupabaseClient;onClose:()=>void}){
  const[mode,setMode]=useState<"id"|"password">("id"),[name,setName]=useState(""),[phone,setPhone]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[foundId,setFoundId]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();setLoading(true);setMessage("");setFoundId("");if(mode==="id"){const{data,error}=await supabase.rpc("find_login_id",{p_name:name,p_phone:phone});if(error)setMessage("아이디를 확인하지 못했습니다.");else if(data)setFoundId(String(data));else setMessage("입력한 이름과 연락처가 일치하는 계정을 찾지 못했습니다.");}else{const{error}=await supabase.rpc("request_password_reset",{p_name:name,p_phone:phone});setMessage(error?"재발급 요청을 등록하지 못했습니다.":"관리자에게 비밀번호 재발급을 요청했습니다. 문자 안내를 기다려 주세요.");}setLoading(false)};
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="student-modal recovery-modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">로그인 도움</p><h2>계정 찾기</h2><span>학원에 등록된 이름과 연락처를 입력해 주세요.</span></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><nav className="recovery-tabs"><button type="button" className={mode==="id"?"active":""} onClick={()=>{setMode("id");setMessage("");setFoundId("")}}>아이디 찾기</button><button type="button" className={mode==="password"?"active":""} onClick={()=>{setMode("password");setMessage("");setFoundId("")}}>비밀번호 재발급 요청</button></nav><form onSubmit={submit}><label>이름<input required value={name} onChange={event=>setName(event.target.value)} placeholder="실명을 입력해 주세요"/></label><label>연락처<input required inputMode="tel" value={phone} onChange={event=>setPhone(event.target.value)} placeholder="010-0000-0000"/></label>{foundId?<section className="recovery-result"><small>등록된 로그인 아이디</small><strong>{foundId}</strong></section>:null}{message?<p className="recovery-message" role="status">{message}</p>:null}<button className="primary" disabled={loading}>{loading?"확인 중…":mode==="id"?"아이디 확인":"관리자에게 요청"}</button></form><footer><button type="button" className="secondary-button" onClick={onClose}>로그인으로 돌아가기</button></footer></section></div>;
}

export function ForcedPasswordChange({supabase,onComplete}:{supabase:SupabaseClient;onComplete:()=>void}){
  const[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();setError("");if(password.length<8)return setError("새 비밀번호는 8자 이상 입력해 주세요.");if(password!==confirm)return setError("새 비밀번호 확인이 일치하지 않습니다.");setSaving(true);const{error:updateError}=await supabase.auth.updateUser({password});if(updateError){setError("비밀번호를 변경하지 못했습니다.");setSaving(false);return}const{error:completeError}=await supabase.rpc("complete_temporary_password_change");if(completeError){setError("비밀번호 변경 완료 처리를 하지 못했습니다.");setSaving(false);return}onComplete()};
  return <main className="auth-shell"><section className="auth-card forced-password-card"><div className="forced-lock">✓</div><h1>새 비밀번호를 설정해 주세요</h1><p className="auth-copy">문자로 받은 임시 비밀번호는 한 번만 사용합니다.<br/>계속하려면 본인만 아는 새 비밀번호로 변경해 주세요.</p><form onSubmit={submit}><label>새 비밀번호<input required minLength={8} type="password" autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="8자 이상"/></label><label>새 비밀번호 확인<input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)} placeholder="한 번 더 입력"/></label>{error?<p className="auth-error">{error}</p>:null}<button className="primary" disabled={saving}>{saving?"변경 중…":"새 비밀번호로 변경"}</button></form></section></main>;
}
