"use client";

import type { FormEvent } from "react";
import { useEffect, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

type RecoveryMode="id"|"password";
type FunctionError={context?:Response;message:string};
async function readFunctionError(error:FunctionError){if(error.context)try{const body=await error.context.clone().json() as{error?:string};if(body.error)return body.error}catch{}return error.message}

export function AccountRecovery({supabase,onClose}:{supabase:SupabaseClient;onClose:()=>void}){
  const[mode,setMode]=useState<RecoveryMode>("id"),[name,setName]=useState(""),[phone,setPhone]=useState(""),[code,setCode]=useState(""),[challengeId,setChallengeId]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[foundId,setFoundId]=useState(""),[seconds,setSeconds]=useState(0),[completed,setCompleted]=useState(false);
  useEffect(()=>{if(seconds<=0)return;const timer=window.setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[seconds]);
  const reset=(next:RecoveryMode)=>{setMode(next);setCode("");setChallengeId("");setPassword("");setConfirm("");setMessage("");setFoundId("");setCompleted(false);setSeconds(0)};
  const send=async()=>{setLoading(true);setMessage("");setFoundId("");const{data,error}=await supabase.functions.invoke("account-recovery-otp",{body:{action:"send",purpose:mode,name:name.trim(),phone}});if(error){setMessage(await readFunctionError(error as FunctionError));setLoading(false);return}setChallengeId((data as{challengeId:string}).challengeId);setSeconds(60);setMessage("등록된 정보와 일치하면 인증번호가 문자로 발송됩니다. 5분 안에 입력해 주세요.");setLoading(false)};
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!challengeId){await send();return}if(mode==="password"){if(password.length<8){setMessage("새 비밀번호는 8자 이상 입력해 주세요.");return}if(password!==confirm){setMessage("새 비밀번호 확인이 일치하지 않습니다.");return}}setLoading(true);setMessage("");const{data,error}=await supabase.functions.invoke("account-recovery-otp",{body:{action:"verify",challengeId,code,password:mode==="password"?password:undefined}});if(error){setMessage(await readFunctionError(error as FunctionError));setLoading(false);return}if(mode==="id")setFoundId((data as{loginId?:string}).loginId??"");else{setCompleted(true);setMessage("새 비밀번호가 설정되었습니다. 이제 새 비밀번호로 로그인해 주세요.")}setLoading(false)};
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="student-modal recovery-modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">로그인 도움</p><h2>계정 찾기</h2><span>학원에 등록된 본인 연락처로 안전하게 확인합니다.</span></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><nav className="recovery-tabs"><button type="button" className={mode==="id"?"active":""} onClick={()=>reset("id")}>아이디 찾기</button><button type="button" className={mode==="password"?"active":""} onClick={()=>reset("password")}>비밀번호 재설정</button></nav><form onSubmit={submit}><label>이름<input required disabled={Boolean(challengeId)} value={name} onChange={event=>setName(event.target.value)} placeholder="실명을 입력해 주세요"/></label><label>연락처<input required disabled={Boolean(challengeId)} inputMode="tel" autoComplete="tel" value={phone} onChange={event=>setPhone(event.target.value)} placeholder="010-0000-0000"/></label>{challengeId&&!foundId&&!completed?<><label>문자 인증번호<span className="recovery-code-field"><input required inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={event=>setCode(event.target.value.replace(/\D/g,"").slice(0,6))} placeholder="6자리 입력"/><button type="button" disabled={loading||seconds>0} onClick={()=>void send()}>{seconds>0?`${seconds}초 후 재전송`:"인증번호 재전송"}</button></span></label>{mode==="password"?<><label>새 비밀번호<input required minLength={8} type="password" autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="8자 이상"/></label><label>새 비밀번호 확인<input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)} placeholder="한 번 더 입력"/></label></>:null}</>:null}{foundId?<section className="recovery-result"><small>등록된 로그인 아이디</small><strong>{foundId}</strong></section>:null}{message?<p className={`recovery-message${completed?" success":""}`} role="status">{message}</p>:null}{!foundId&&!completed?<button className="primary" disabled={loading}>{loading?"처리 중…":!challengeId?"인증번호 받기":mode==="id"?"아이디 확인":"새 비밀번호 설정"}</button>:<button type="button" className="primary" onClick={onClose}>로그인하기</button>}<p className="recovery-help">등록 번호가 바뀌었거나 문자를 받을 수 없다면 학원 관리자에게 문의해 주세요.</p></form></section></div>;
}

export function ForcedPasswordChange({supabase,onComplete}:{supabase:SupabaseClient;onComplete:()=>void}){
  const[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();setError("");if(password.length<8)return setError("새 비밀번호는 8자 이상 입력해 주세요.");if(password!==confirm)return setError("새 비밀번호 확인이 일치하지 않습니다.");setSaving(true);const{error:updateError}=await supabase.auth.updateUser({password});if(updateError){setError("비밀번호를 변경하지 못했습니다.");setSaving(false);return}const{error:completeError}=await supabase.rpc("complete_temporary_password_change");if(completeError){setError("비밀번호 변경 완료 처리를 하지 못했습니다.");setSaving(false);return}onComplete()};
  return <main className="auth-shell"><section className="auth-card forced-password-card"><div className="forced-lock">✓</div><h1>새 비밀번호를 설정해 주세요</h1><p className="auth-copy">문자로 받은 임시 비밀번호는 한 번만 사용합니다.<br/>계속하려면 본인만 아는 새 비밀번호로 변경해 주세요.</p><form onSubmit={submit}><label>새 비밀번호<input required minLength={8} type="password" autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="8자 이상"/></label><label>새 비밀번호 확인<input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)} placeholder="한 번 더 입력"/></label>{error?<p className="auth-error">{error}</p>:null}<button className="primary" disabled={saving}>{saving?"변경 중…":"새 비밀번호로 변경"}</button></form></section></main>;
}
