"use client";

import type { FormEvent } from "react";
import type * as React from "react";
import { useCallback, useEffect, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

type Named = { id:string; name:string };
type Announcement = { id:string; title:string; body:string; audience:"all"|"class"|"student"; classId:string|null; className:string|null; studentId:string|null; studentName:string|null; authorName:string; publishedAt:string|null; expiresAt:string|null; createdAt:string };
type MessageLog = { id:string; studentName:string|null; recipientName:string; recipientPhone:string; body:string; status:string; errorMessage:string|null; sentAt:string|null; createdAt:string };
type Recipient = { studentId:string; studentName:string; recipientName:string; phone:string; kind:"student"|"guardian" };
type BoardData = { isStaff:boolean; classes:Named[]; students:Named[]; announcements:Announcement[]; messageLogs:MessageLog[] };
const audienceLabels = { all:"전체",class:"클래스",student:"개별 학생" };

export function CommunicationBoard({ supabase }: { supabase:SupabaseClient }) {
  const [data,setData] = useState<BoardData>({ isStaff:false,classes:[],students:[],announcements:[],messageLogs:[] }); const [loading,setLoading] = useState(true); const [error,setError] = useState(""); const [tab,setTab] = useState<"notice"|"message">("notice"); const [editor,setEditor] = useState<Announcement|"new"|null>(null); const [composer,setComposer] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); const { data:next,error:loadError } = await supabase.rpc("communication_board"); if (loadError) setError("공지·문자 내역을 불러오지 못했습니다."); else setData(next as BoardData); setLoading(false); },[supabase]);
  useEffect(() => { void load(); },[load]);
  const remove = async (row:Announcement) => { if (!confirm(`“${row.title}” 공지를 삭제할까요?`)) return; const { error:deleteError } = await supabase.rpc("staff_delete_announcement",{ p_announcement_id:row.id }); if (deleteError) setError("공지를 삭제하지 못했습니다."); else await load(); };
  if (loading) return <section className="panel communication-empty">공지·문자 내역을 불러오는 중이에요…</section>;
  return <><div className="page-heading compact"><div><p className="eyebrow">대상별 안내 관리</p><h1>{data.isStaff ? "공지·문자" : "공지"}</h1><p>{data.isStaff ? "대상별 공지를 게시하고 문자 발송 대기 내역을 관리합니다." : "나에게 공개된 학원 공지를 확인합니다."}</p></div>{data.isStaff && <button className="primary" onClick={() => tab === "notice" ? setEditor("new") : setComposer(true)}>{tab === "notice" ? "＋ 공지 작성" : "＋ 문자 작성"}</button>}</div>
    {error && <p className="attendance-error">{error}</p>}{data.isStaff && <div className="communication-tabs"><button className={tab === "notice" ? "active" : ""} onClick={() => setTab("notice")}>공지 관리</button><button className={tab === "message" ? "active" : ""} onClick={() => setTab("message")}>문자 대기열</button></div>}
    {(!data.isStaff || tab === "notice") ? <section className="communication-notices">{data.announcements.length === 0 ? <div className="panel communication-empty">{data.isStaff ? "아직 작성된 공지가 없습니다." : "현재 확인할 공지가 없습니다."}</div> : data.announcements.map((row) => <article className="panel" key={row.id}><header><div><span className="communication-audience">{audienceLabels[row.audience]}{row.className ? ` · ${row.className}` : row.studentName ? ` · ${row.studentName}` : ""}</span><h2>{row.title}</h2><small>{row.authorName} · {formatDateTime(row.publishedAt ?? row.createdAt)}</small></div><span className={`announcement-state ${announcementState(row)}`}>{announcementStateLabel(row)}</span></header><p>{row.body}</p>{row.expiresAt && <footer>공개 종료 {formatDateTime(row.expiresAt)}</footer>}{data.isStaff && <div className="announcement-actions"><button className="secondary-button" onClick={() => setEditor(row)}>수정</button><button className="danger-link" onClick={() => void remove(row)}>삭제</button></div>}</article>)}</section> : <MessageLogBoard logs={data.messageLogs} />}
    {editor && <AnnouncementEditor row={editor === "new" ? undefined : editor} data={data} supabase={supabase} onClose={() => setEditor(null)} onSaved={async () => { setEditor(null); await load(); }} />}{composer && <MessageComposer data={data} supabase={supabase} onClose={() => setComposer(false)} onSaved={async (count) => { setComposer(false); await load(); setError(`${count}건을 발송 대기열에 등록했습니다. 외부 문자업체 연결 후 실제 발송됩니다.`); }} />}</>;
}

function MessageLogBoard({ logs }: { logs:MessageLog[] }) {
  const queued = logs.filter((row) => row.status === "queued").length; const sent = logs.filter((row) => row.status === "sent").length; const failed = logs.filter((row) => row.status === "failed").length;
  return <><div className="makeup-summary"><span>발송 대기 <b>{queued}</b></span><span>발송 완료 <b>{sent}</b></span><span>실패 <b>{failed}</b></span></div><section className="panel message-log"><div className="message-log-head"><span>수신자</span><span>문자 내용</span><span>등록/발송</span><span>상태</span></div>{logs.length === 0 ? <p className="communication-empty">문자 발송 대기 내역이 없습니다.</p> : logs.map((row) => <article key={row.id}><span><b>{row.recipientName}</b><small>{row.studentName && row.studentName !== row.recipientName ? `${row.studentName} 학생 · ` : ""}{row.recipientPhone}</small></span><p>{row.body}</p><time>{formatDateTime(row.sentAt ?? row.createdAt)}</time><i className={row.status}>{messageStatus(row.status)}</i>{row.errorMessage && <em>{row.errorMessage}</em>}</article>)}</section></>;
}

function AnnouncementEditor({ row,data,supabase,onClose,onSaved }: { row?:Announcement; data:BoardData; supabase:SupabaseClient; onClose:()=>void; onSaved:()=>Promise<void> }) {
  const initialMode = !row?.publishedAt ? "draft" : new Date(row.publishedAt).getTime() <= Date.now() ? "now" : "schedule"; const [title,setTitle] = useState(row?.title ?? ""); const [body,setBody] = useState(row?.body ?? ""); const [audience,setAudience] = useState<"all"|"class"|"student">(row?.audience ?? "all"); const [targetId,setTargetId] = useState(row?.classId ?? row?.studentId ?? ""); const [publishMode,setPublishMode] = useState(initialMode); const [publishAt,setPublishAt] = useState(row?.publishedAt ? koreaDateTime(row.publishedAt) : `${koreaToday()}T18:00`); const [expiresAt,setExpiresAt] = useState(row?.expiresAt ? koreaDateTime(row.expiresAt) : ""); const [saving,setSaving] = useState(false); const [error,setError] = useState("");
  const changeAudience = (value:"all"|"class"|"student") => { setAudience(value); setTargetId(value === "class" ? data.classes[0]?.id ?? "" : value === "student" ? data.students[0]?.id ?? "" : ""); };
  const submit = async (event:FormEvent) => { event.preventDefault(); setSaving(true); setError(""); const published = publishMode === "draft" ? null : publishMode === "now" ? new Date().toISOString() : `${publishAt}:00+09:00`; const { error:saveError } = await supabase.rpc("staff_save_announcement",{ p_announcement_id:row?.id ?? null,p_title:title,p_body:body,p_audience:audience,p_target_id:targetId || null,p_published_at:published,p_expires_at:expiresAt ? `${expiresAt}:00+09:00` : null }); if (saveError) { setError(readError(saveError.message,"공지를 저장하지 못했습니다.")); setSaving(false); } else await onSaved(); };
  return <Modal title={row ? "공지 수정" : "공지 작성"} description="전체·클래스·개별 학생에게 필요한 내용만 공개합니다." onClose={onClose}><form onSubmit={submit}><div className="form-grid"><label>공개 대상<select value={audience} onChange={(event) => changeAudience(event.target.value as "all"|"class"|"student")}><option value="all">전체</option><option value="class">클래스</option><option value="student">개별 학생</option></select></label>{audience !== "all" && <label>{audience === "class" ? "클래스" : "학생"}<select required value={targetId} onChange={(event) => setTargetId(event.target.value)}><option value="">선택해 주세요</option>{(audience === "class" ? data.classes : data.students).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label className="full">제목 <b>*</b><input required value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="full">공지 내용 <b>*</b><textarea required rows={6} value={body} onChange={(event) => setBody(event.target.value)} /></label><label>게시 방식<select value={publishMode} onChange={(event) => setPublishMode(event.target.value)}><option value="draft">임시 저장</option><option value="now">즉시 공개</option><option value="schedule">예약 공개</option></select></label>{publishMode === "schedule" && <label>예약 시간<input required type="datetime-local" value={publishAt} onChange={(event) => setPublishAt(event.target.value)} /></label>}<label>공개 종료 (선택)<input type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /></label></div>{error && <p className="form-error">{error}</p>}<Actions saving={saving} onClose={onClose} label="공지 저장" /></form></Modal>;
}

function MessageComposer({ data,supabase,onClose,onSaved }: { data:BoardData; supabase:SupabaseClient; onClose:()=>void; onSaved:(count:number)=>Promise<void> }) {
  const [targetType,setTargetType] = useState<"all"|"class"|"student">("all"); const [targetId,setTargetId] = useState(""); const [recipientKind,setRecipientKind] = useState("guardian"); const [body,setBody] = useState(""); const [recipients,setRecipients] = useState<Recipient[]>([]); const [loading,setLoading] = useState(false); const [saving,setSaving] = useState(false); const [error,setError] = useState("");
  useEffect(() => { let active = true; setLoading(true); void supabase.rpc("staff_message_recipient_preview",{ p_target_type:targetType,p_target_id:targetId || null,p_recipient_kind:recipientKind }).then(({ data:next }) => { if (active) { setRecipients((next ?? []) as Recipient[]); setLoading(false); } }); return () => { active = false; }; },[recipientKind,supabase,targetId,targetType]);
  const changeTarget = (value:"all"|"class"|"student") => { setTargetType(value); setTargetId(value === "class" ? data.classes[0]?.id ?? "" : value === "student" ? data.students[0]?.id ?? "" : ""); };
  const submit = async (event:FormEvent) => { event.preventDefault(); if (!confirm(`${recipients.length}명에게 보낼 문자를 발송 대기열에 등록할까요?`)) return; setSaving(true); setError(""); const { data:count,error:saveError } = await supabase.rpc("staff_queue_messages",{ p_target_type:targetType,p_target_id:targetId || null,p_recipient_kind:recipientKind,p_body:body }); if (saveError) { setError(readError(saveError.message,"문자 대기열을 등록하지 못했습니다.")); setSaving(false); } else await onSaved(Number(count ?? 0)); };
  return <Modal title="문자 작성" description="현재는 외부 문자업체 연결 전 단계로, 확인된 수신자를 발송 대기열에 저장합니다." onClose={onClose}><form onSubmit={submit}><div className="form-grid"><label>발송 대상<select value={targetType} onChange={(event) => changeTarget(event.target.value as "all"|"class"|"student")}><option value="all">전체 재원생</option><option value="class">클래스</option><option value="student">개별 학생</option></select></label>{targetType !== "all" && <label>{targetType === "class" ? "클래스" : "학생"}<select required value={targetId} onChange={(event) => setTargetId(event.target.value)}>{(targetType === "class" ? data.classes : data.students).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>수신자<select value={recipientKind} onChange={(event) => setRecipientKind(event.target.value)}><option value="guardian">학부모</option><option value="student">학생</option><option value="both">학생+학부모</option></select></label><label className="full">문자 내용 <b>*</b><textarea required maxLength={1000} rows={5} value={body} onChange={(event) => setBody(event.target.value)} placeholder="발송할 안내 내용을 입력하세요." /><small>{body.length}/1000자</small></label></div><section className="recipient-preview"><header><b>수신 대상 미리보기</b><span>{loading ? "확인 중…" : `${recipients.length}명`}</span></header><div>{recipients.slice(0,12).map((item,index) => <span key={`${item.studentId}-${item.kind}-${index}`}><b>{item.recipientName}</b><small>{item.studentName}{item.kind === "guardian" ? " 학부모" : " 학생"} · {item.phone}</small></span>)}{recipients.length > 12 && <em>외 {recipients.length - 12}명</em>}{!loading && recipients.length === 0 && <p>등록된 연락처가 있는 수신자가 없습니다.</p>}</div></section>{error && <p className="form-error">{error}</p>}<Actions saving={saving} onClose={onClose} label="대기열 등록" disabled={!recipients.length} /></form></Modal>;
}

function Modal({ title,description,onClose,children }: { title:string; description:string; onClose:()=>void; children:React.ReactNode }) { return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="student-modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">공지·문자 관리</p><h2>{title}</h2><span>{description}</span></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header>{children}</section></div>; }
function Actions({ saving,onClose,label,disabled=false }: { saving:boolean; onClose:()=>void; label:string; disabled?:boolean }) { return <footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving || disabled}>{saving ? "저장 중…" : label}</button></footer>; }
function announcementState(row:Announcement) { if (!row.publishedAt) return "draft"; if (row.expiresAt && new Date(row.expiresAt).getTime() <= Date.now()) return "ended"; if (new Date(row.publishedAt).getTime() > Date.now()) return "scheduled"; return "published"; }
function announcementStateLabel(row:Announcement) { return ({ draft:"임시 저장",ended:"종료",scheduled:"예약",published:"공개" } as Record<string,string>)[announcementState(row)]; }
function messageStatus(status:string) { return ({ queued:"발송 대기",sent:"발송 완료",failed:"실패" } as Record<string,string>)[status] ?? status; }
function dateParts(value:Date) { const parts = new Intl.DateTimeFormat("en",{ timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false }).formatToParts(value); return Object.fromEntries(parts.map((part) => [part.type,part.value])); }
function koreaToday() { const item=dateParts(new Date()); return `${item.year}-${item.month}-${item.day}`; }
function koreaDateTime(value:string) { const item=dateParts(new Date(value)); return `${item.year}-${item.month}-${item.day}T${item.hour === "24" ? "00" : item.hour}:${item.minute}`; }
function formatDateTime(value:string) { return new Intl.DateTimeFormat("ko-KR",{ timeZone:"Asia/Seoul",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false }).format(new Date(value)); }
function readError(message:string,fallback:string) { return ["입력해","선택해","늦어야","교직원","찾을 수"].some((word) => message.includes(word)) ? message : fallback; }
