"use client";
import {useEffect,useMemo,useState} from "react";
import type {SupabaseClient} from "@supabase/supabase-js";
import styles from "./consultation-class-search.module.css";
type ClassInfo={id:string;name:string;subject:string;room:string|null;teachers:{id:string;name:string}[];students:{id:string;name:string;school:string|null;grade:string|null}[];schedules:{id:string;weekday:number;startTime:string;endTime:string}[]};
type Lesson={id:string;lessonDate:string;lessonContent:string|null;homeworkContent:string|null;teacherName:string};
const normalize=(s:string)=>s.toLocaleLowerCase().replace(/\s/g,"");
export function ConsultationClassSearch({supabase}:{supabase:SupabaseClient}){
 const[query,setQuery]=useState("");const[subject,setSubject]=useState("");const[grade,setGrade]=useState("");const[school,setSchool]=useState("");const[enabled,setEnabled]=useState(false);const[classes,setClasses]=useState<ClassInfo[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[retry,setRetry]=useState(0);const[limit,setLimit]=useState(6);
 useEffect(()=>{if(!enabled)return;let active=true;setLoading(true);setError("");Promise.all([supabase.rpc("teacher_class_workspace"),supabase.rpc("staff_manage_classes")]).then(([{data,error},managed])=>{if(!active)return;if(error||managed.error)setError("클래스 정보를 불러오지 못했습니다.");else {const teachers=new Map<string,ClassInfo["teachers"]>((managed.data??[]).map((c:ClassInfo)=>[c.id,c.teachers]));setClasses((data?.classes??[]).map((c:ClassInfo)=>({...c,teachers:teachers.get(c.id)??[]})));}setLoading(false)},()=>{if(active){setError("연결을 확인하고 다시 시도해 주세요.");setLoading(false)}});return()=>{active=false}},[enabled,retry,supabase]);
 const grades=useMemo(()=>Array.from(new Set(classes.flatMap(c=>c.students.map(s=>s.grade).filter(Boolean)))).sort(),[classes]);
 const schools=useMemo(()=>Array.from(new Set(classes.flatMap(c=>c.students.map(s=>s.school).filter(Boolean)))).sort((a,b)=>a!.localeCompare(b!,"ko")),[classes]);
 const results=useMemo(()=>{const words=query.trim().split(/\s+/).filter(Boolean).map(normalize);return classes.filter(c=>{const hay=normalize([c.name,c.subject,...c.teachers.map(t=>t.name),...c.students.flatMap(s=>[s.school??"",s.grade??""])].join(" "));return words.every(w=>hay.includes(w))&&(!subject||c.subject.includes(subject))&&(!grade||c.students.some(s=>s.grade===grade))&&(!school||c.students.some(s=>s.school===school))}).sort((a,b)=>a.name.localeCompare(b.name,"ko"))},[classes,query,subject,grade,school]);
 const searching=Boolean(query.trim()||subject||grade||school);
 return <section className={styles.search} aria-label="상담용 클래스 검색"><header><div><span className={styles.eyebrow}>상담 도우미</span><h2>어떤 반을 찾으세요?</h2><p>시간표부터 최근 수업 진도까지, 한곳에서 확인하세요.</p></div><span className={styles.badge}>전체 클래스 검색</span></header><div className={styles.input}><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input aria-label="반 이름, 학교, 학년, 과목, 선생님 검색" placeholder="반 이름, 학교, 학년, 과목, 선생님 검색" value={query} onFocus={()=>setEnabled(true)} onChange={e=>{setEnabled(true);setQuery(e.target.value);setLimit(6)}}/>{query&&<button aria-label="검색어 지우기" onClick={()=>setQuery("")}>×</button>}</div><div className={styles.filters}><select aria-label="과목" value={subject} onFocus={()=>setEnabled(true)} onChange={e=>{setSubject(e.target.value);setLimit(6)}}><option value="">모든 과목</option>{["국어","영어","수학"].map(v=><option key={v}>{v}</option>)}</select><select aria-label="학년" value={grade} onFocus={()=>setEnabled(true)} onChange={e=>{setGrade(e.target.value);setLimit(6)}}><option value="">모든 학년</option>{grades.map(v=><option key={v} value={v!}>{v}</option>)}</select><select aria-label="학교" value={school} onFocus={()=>setEnabled(true)} onChange={e=>{setSchool(e.target.value);setLimit(6)}}><option value="">모든 학교</option>{schools.map(v=><option key={v} value={v!}>{v}</option>)}</select>{searching&&<button onClick={()=>{setQuery("");setSubject("");setGrade("");setSchool("")}}>초기화</button>}</div>{error?<p role="alert">{error} <button onClick={()=>setRetry(v=>v+1)}>다시 시도</button></p>:searching?(loading?<p role="status">검색 정보를 확인하고 있어요…</p>:<><div className={styles.count}>검색 결과 <b>{results.length}개 반</b></div><div className={styles.results}>{results.slice(0,limit).map(c=><ClassResult key={c.id} item={c} supabase={supabase}/>)}</div>{!results.length&&<p className={styles.empty}>일치하는 반이 없습니다. 검색어나 필터를 바꿔 주세요.</p>}{results.length>limit&&<button className={styles.more} onClick={()=>setLimit(v=>v+6)}>검색 결과 더 보기</button>}</>):<p className={styles.hint}>예: 군서고 · 고1 영어 · 현호 <span>학교·학년 필터는 수강 학생 정보 기준입니다.</span></p>}</section>
}
function ClassResult({item,supabase}:{item:ClassInfo;supabase:SupabaseClient}){
 const[records,setRecords]=useState<Lesson[]|null>(null);const[error,setError]=useState(false);const[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setError(false);supabase.rpc("staff_class_lesson_history",{p_class_id:item.id,p_limit:3}).then(({data,error})=>{if(!active)return;if(error)setError(true);else setRecords(data??[])},()=>{if(active)setError(true)});return()=>{active=false}},[item.id,supabase,retry]);
 const latest=records?.[0];
 return <details className={styles.result}><summary><div className={styles.resultTitle}><span>{item.subject}</span><h3>{item.name}</h3><small>{item.students.length}명 <i>⌄</i></small></div><p className={styles.teacher}>{item.teachers.map(t=>t.name).join(" · ")||"담당 미지정"}{item.room?` · ${item.room}`:""}</p><div className={styles.times}>{item.schedules.length?[...item.schedules].sort((a,b)=>a.weekday-b.weekday||a.startTime.localeCompare(b.startTime)).map(s=><span key={s.id}>{["","월","화","수","목","금","토","일"][s.weekday]} {s.startTime.slice(0,5)}–{s.endTime.slice(0,5)}</span>):<span>시간표 미등록</span>}</div><div className={styles.progress}><small>최근 수업 기록 {latest&&<time>{latest.lessonDate}</time>}</small><p>{error?"진도를 불러오지 못했습니다. 펼쳐서 다시 시도해 주세요.":records===null?"최근 기록 확인 중…":latest?(latest.lessonContent?.trim()||"이 수업에 작성된 공통 진도가 없습니다."):"작성된 수업 기록이 없습니다."}</p></div></summary><div className={styles.expanded}><h4>최근 수업 3회</h4>{error?<button onClick={()=>setRetry(v=>v+1)}>기록 다시 불러오기</button>:records?.length?records.map(r=><article key={r.id}><time>{r.lessonDate} · {r.teacherName}</time><p>{r.lessonContent?.trim()||"공통 진도 미입력"}</p>{r.homeworkContent&&<p className={styles.homework}>숙제 · {r.homeworkContent}</p>}</article>):<p>수업 기록이 없습니다.</p>}<h4>수강 학생 · {item.students.length}명</h4><div className={styles.students}>{item.students.map(s=><span key={s.id}><b>{s.name}</b><small>{[s.school,s.grade].filter(Boolean).join(" · ")}</small></span>)}</div></div></details>
}
