"use client";

import type { FormEvent } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

type Named = { id:string; name:string };
type OverdueStudent = Named & { lastConsultedAt:string|null };
type Consultation = { id:string; studentId:string; studentName:string; consultantName:string; consultedAt:string; consultationType:string; internalNote:string|null; guardianSummary:string|null; studentSummary:string|null; nextContactOn:string|null };
type BoardData = { isStaff:boolean; students:Named[]; overdueStudents:OverdueStudent[]; items:Consultation[] };
const typeLabels:Record<string,string> = { student:"학생 상담",guardian:"학부모 상담",phone:"전화 상담",academic:"학습 상담",other:"기타" };

export function ConsultationBoard({ supabase }: { supabase:SupabaseClient }) {
  const [data,setData] = useState<BoardData>({ isStaff:false,students:[],overdueStudents:[],items:[] }); const [loading,setLoading] = useState(true); const [error,setError] = useState(""); const [editor,setEditor] = useState<{ row?:Consultation; studentId?:string }|null>(null); const [query,setQuery] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const { data:next,error:loadError } = await supabase.rpc("consultation_board"); if (loadError) setError("상담 기록을 불러오지 못했습니다."); else setData(next as BoardData); setLoading(false); },[supabase]);
  useEffect(() => { void load(); },[load]);
  const visible = useMemo(() => { const text = query.trim().toLowerCase(); return text ? data.items.filter((item) => [item.studentName,item.consultantName,typeLabels[item.consultationType] ?? ""].some((value) => value.toLowerCase().includes(text))) : data.items; },[data.items,query]);
  const upcoming = data.items.filter((item) => item.nextContactOn && item.nextContactOn >= koreaToday() && item.nextContactOn <= addDays(7)).length;
  const remove = async (row:Consultation) => { if (!confirm(`${row.studentName} 학생의 ${formatDate(row.consultedAt)} 상담 기록을 삭제할까요?`)) return; const { error:deleteError } = await supabase.rpc("staff_delete_consultation",{ p_consultation_id:row.id }); if (deleteError) setError("상담 기록을 삭제하지 못했습니다."); else await load(); };
  if (loading) return <section className="panel consultation-empty">상담 기록을 불러오는 중이에요…</section>;
  return <><div className="page-heading compact"><div><p className="eyebrow">학생별 상담 이력</p><h1>상담 관리</h1><p>{data.isStaff ? "내부 기록과 학부모 공유 내용을 분리해 안전하게 관리합니다." : "학원에서 공유한 자녀의 상담 내용을 확인합니다."}</p></div>{data.isStaff && <button className="primary" onClick={() => setEditor({})}>＋ 상담 기록</button>}</div>
    {error && <p className="attendance-error">{error}</p>}{data.isStaff && <><div className="makeup-summary"><span>30일 이상 미상담 <b>{data.overdueStudents.length}</b></span><span>7일 내 예정 <b>{upcoming}</b></span><span>전체 기록 <b>{data.items.length}</b></span></div>{data.overdueStudents.length > 0 && <section className="panel consultation-alert"><header><div><h2>상담이 필요한 학생</h2><span>마지막 상담 후 30일이 지났거나 상담 기록이 없습니다.</span></div></header><div>{data.overdueStudents.map((student) => <button key={student.id} onClick={() => setEditor({ studentId:student.id })}><i>{student.name.slice(0,1)}</i><span><b>{student.name}</b><small>{student.lastConsultedAt ? `마지막 상담 ${formatDate(student.lastConsultedAt)}` : "상담 기록 없음"}</small></span><strong>기록하기 ›</strong></button>)}</div></section>}</>}
    <section className="panel consultation-panel">{data.isStaff && <div className="consultation-toolbar"><div className="search-wrap inner"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="학생, 상담자 검색" /></div><span>전체 {visible.length}건</span></div>}<div className="consultation-list">{visible.length === 0 ? <p className="consultation-empty">{data.isStaff ? "아직 저장된 상담 기록이 없습니다." : "공유된 상담 기록이 없습니다."}</p> : visible.map((row) => <article key={row.id}><header><div className="consultation-person"><i>{row.studentName.slice(0,1)}</i><span><b>{row.studentName}</b><small>{typeLabels[row.consultationType] ?? "상담"} · {row.consultantName}</small></span></div><div className="consultation-date"><b>{formatDateTime(row.consultedAt)}</b>{row.nextContactOn && <small>다음 상담 {formatShortDate(row.nextContactOn)}</small>}</div>{data.isStaff && <div className="consultation-actions"><button className="secondary-button" onClick={() => setEditor({ row })}>수정</button><button className="danger-link" onClick={() => void remove(row)}>삭제</button></div>}</header><div className="consultation-notes">{data.isStaff && <section className="private"><b>🔒 내부 메모</b><p>{row.internalNote ?? "입력된 내부 메모가 없습니다."}</p></section>}{row.guardianSummary && <section className="shared"><b>학부모 공유 내용</b><p>{row.guardianSummary}</p></section>}{data.isStaff && row.studentSummary && <section className="student-shared"><b>학생 공유 내용</b><p>{row.studentSummary}</p></section>}</div></article>)}</div></section>
    {editor && <ConsultationEditor data={data} row={editor.row} initialStudentId={editor.studentId} supabase={supabase} onClose={() => setEditor(null)} onSaved={async () => { setEditor(null); await load(); }} />}</>;
}

function ConsultationEditor({ data,row,initialStudentId,supabase,onClose,onSaved }: { data:BoardData; row?:Consultation; initialStudentId?:string; supabase:SupabaseClient; onClose:()=>void; onSaved:()=>Promise<void> }) {
  const [studentId,setStudentId] = useState(row?.studentId ?? initialStudentId ?? data.students[0]?.id ?? ""); const [consultationType,setConsultationType] = useState(row?.consultationType ?? "guardian"); const [consultedAt,setConsultedAt] = useState(row ? koreaDateTime(row.consultedAt) : `${koreaToday()}T${koreaTime()}`); const [internalNote,setInternalNote] = useState(row?.internalNote ?? ""); const [guardianSummary,setGuardianSummary] = useState(row?.guardianSummary ?? ""); const [studentSummary,setStudentSummary] = useState(row?.studentSummary ?? ""); const [nextContactOn,setNextContactOn] = useState(row?.nextContactOn ?? ""); const [saving,setSaving] = useState(false); const [error,setError] = useState("");
  const submit = async (event:FormEvent) => { event.preventDefault(); setSaving(true); setError(""); const { error:saveError } = await supabase.rpc("staff_save_consultation",{ p_consultation_id:row?.id ?? null,p_student_id:studentId,p_consultation_type:consultationType,p_consulted_at:`${consultedAt}:00+09:00`,p_internal_note:internalNote || null,p_guardian_summary:guardianSummary || null,p_student_summary:studentSummary || null,p_next_contact_on:nextContactOn || null }); if (saveError) { setError(readError(saveError.message)); setSaving(false); } else await onSaved(); };
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="student-modal consultation-editor" role="dialog" aria-modal="true"><header><div><p className="eyebrow">역할별 상담 기록</p><h2>{row ? "상담 기록 수정" : "상담 기록"}</h2><span>내부 메모와 공유 내용을 구분해서 입력해 주세요.</span></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><form onSubmit={submit}><div className="form-grid"><label>학생 <b>*</b><select required value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">선택해 주세요</option>{data.students.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label><label>상담 유형 <b>*</b><select value={consultationType} onChange={(event) => setConsultationType(event.target.value)}>{Object.entries(typeLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>상담 일시 <b>*</b><input required type="datetime-local" value={consultedAt} onChange={(event) => setConsultedAt(event.target.value)} /></label><label>다음 상담 예정일<input type="date" value={nextContactOn} onChange={(event) => setNextContactOn(event.target.value)} /></label><label className="full consultation-private-field">🔒 내부 메모<textarea rows={4} value={internalNote} onChange={(event) => setInternalNote(event.target.value)} placeholder="관리자와 교사만 확인합니다." /></label><label className="full consultation-shared-field">학부모 공유 내용<textarea rows={4} value={guardianSummary} onChange={(event) => setGuardianSummary(event.target.value)} placeholder="학부모 계정에서 보이는 내용입니다." /></label><label className="full">학생 공유 내용<textarea rows={3} value={studentSummary} onChange={(event) => setStudentSummary(event.target.value)} placeholder="학생 계정에서 보일 내용 (선택)" /></label></div>{error && <p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving || !studentId}>{saving ? "저장 중…" : "상담 저장"}</button></footer></form></section></div>;
}

function dateParts(value:Date) { const parts = new Intl.DateTimeFormat("en",{ timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false }).formatToParts(value); return Object.fromEntries(parts.map((part) => [part.type,part.value])); }
function koreaToday() { const item = dateParts(new Date()); return `${item.year}-${item.month}-${item.day}`; }
function koreaTime() { const item = dateParts(new Date()); return `${item.hour === "24" ? "00" : item.hour}:${item.minute}`; }
function koreaDateTime(value:string) { const item = dateParts(new Date(value)); return `${item.year}-${item.month}-${item.day}T${item.hour === "24" ? "00" : item.hour}:${item.minute}`; }
function addDays(days:number) { const date = new Date(); date.setDate(date.getDate() + days); const item = dateParts(date); return `${item.year}-${item.month}-${item.day}`; }
function formatDate(value:string) { return new Intl.DateTimeFormat("ko-KR",{ timeZone:"Asia/Seoul",year:"numeric",month:"long",day:"numeric" }).format(new Date(value)); }
function formatDateTime(value:string) { return new Intl.DateTimeFormat("ko-KR",{ timeZone:"Asia/Seoul",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false }).format(new Date(value)); }
function formatShortDate(value:string) { return new Intl.DateTimeFormat("ko-KR",{ timeZone:"Asia/Seoul",month:"long",day:"numeric" }).format(new Date(`${value}T00:00:00+09:00`)); }
function readError(message:string) { return ["입력해","선택해","교직원","찾을 수"].some((word) => message.includes(word)) ? message : "상담 기록을 저장하지 못했습니다. 입력 내용을 확인해 주세요."; }
