"use client";

import type { CSSProperties, FormEvent } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { reorderById, useSortableOrder } from "./use-sortable-order";

type Named={id:string;name:string};
type OverdueStudent=Named&{lastGuardianConsultedAt:string|null;daysSinceGuardian:number|null};
type Consultation={id:string;studentId:string;studentName:string;consultantName:string;consultedAt:string;consultationType:string;internalNote:string|null;guardianSummary:string|null;studentSummary:string|null;nextContactOn:string|null};
type BoardData={isStaff:boolean;isAdmin:boolean;classes:ClassCard[];students:Named[];overdueStudents:OverdueStudent[];items:Consultation[]};
type ClassCard={id:string;name:string;subject:string;color:string;students:Named[]};
const typeLabels:Record<string,string>={student:"학생 상담",guardian:"학부모 상담",phone:"전화 상담",academic:"학습 상담",other:"기타"};

export function ConsultationBoard({supabase}:{supabase:SupabaseClient}){
  const[data,setData]=useState<BoardData>({isStaff:false,isAdmin:false,classes:[],students:[],overdueStudents:[],items:[]});
  const[classes,setClasses]=useState<ClassCard[]>([]); const[selectedClass,setSelectedClass]=useState(""); const[loading,setLoading]=useState(true); const[error,setError]=useState(""); const[editor,setEditor]=useState<{row?:Consultation;studentId?:string;consultationType?:"student"|"guardian"}|null>(null); const[query,setQuery]=useState(""); const[typeFilter,setTypeFilter]=useState("all"); const[sortOrder,setSortOrder]=useState<"latest"|"oldest">("latest");
  const classSortable=useSortableOrder((activeId,overId)=>setClasses((current)=>{const next=reorderById(current,activeId,overId);void supabase.rpc("save_user_class_order",{p_ids:next.map((item)=>item.id)});return next;}));
  const load=useCallback(async()=>{setLoading(true);setError("");const[{data:next,error:loadError},{data:preferences}]=await Promise.all([supabase.rpc("consultation_board"),supabase.rpc("user_list_preferences")]);if(loadError||!next){setError("상담 기록을 불러오지 못했습니다.");setLoading(false);return;}const board=next as BoardData;setData(board);if(board.isStaff){const order=(preferences as{classOrder?:string[]}|null)?.classOrder??[];const cards=(board.classes??[]).map((item)=>({...item,students:item.students??[]}));cards.sort((a,b)=>{const ai=order.indexOf(a.id),bi=order.indexOf(b.id);return(ai<0?99999:ai)-(bi<0?99999:bi)||a.name.localeCompare(b.name,"ko");});setClasses(cards);setSelectedClass((current)=>board.isAdmin&&current==="all"?"all":cards.some((item)=>item.id===current)?current:(board.isAdmin?"all":cards[0]?.id??""));}setLoading(false);},[supabase]);
  useEffect(()=>{void load();},[load]);
  const classStudentIds=useMemo(()=>new Set(selectedClass==="all"?data.students.map((student)=>student.id):classes.find((item)=>item.id===selectedClass)?.students.map((student)=>student.id)??[]),[classes,data.students,selectedClass]);
  const classItems=useMemo(()=>data.items.filter((item)=>!data.isStaff||selectedClass==="all"||classStudentIds.has(item.studentId)),[classStudentIds,data.isStaff,data.items,selectedClass]);
  const visible=useMemo(()=>{const text=query.trim().toLowerCase();return classItems.filter((item)=>(typeFilter==="all"||item.consultationType===typeFilter)&&(!text||[item.studentName,item.consultantName,typeLabels[item.consultationType]??""].some((value)=>value.toLowerCase().includes(text)))).sort((a,b)=>(sortOrder==="latest"?-1:1)*a.consultedAt.localeCompare(b.consultedAt));},[classItems,query,sortOrder,typeFilter]);
  const selectedStudents=selectedClass==="all"?data.students:classes.find((item)=>item.id===selectedClass)?.students??[];
  const overdue=data.overdueStudents.filter((student)=>!data.isStaff||selectedClass==="all"||classStudentIds.has(student.id));
  const remove=async(row:Consultation)=>{if(!confirm(`${row.studentName} 학생의 ${formatDate(row.consultedAt)} 상담 기록을 삭제할까요?`))return;const{error:deleteError}=await supabase.rpc("staff_delete_consultation",{p_consultation_id:row.id});if(deleteError)setError("상담 기록을 삭제하지 못했습니다.");else await load();};
  if(loading)return<section className="panel consultation-empty">상담 기록을 불러오는 중이에요…</section>;
  return<><div className="page-heading compact consultation-heading"><div><h1>상담 관리</h1><p>{data.isStaff?"학생·학부모 상담 기록을 클래스별로 관리합니다.":"학원에서 공유한 자녀의 상담 내용을 확인합니다."}</p></div>{data.isStaff&&<button className="primary" onClick={()=>setEditor({consultationType:"guardian"})}>＋ 상담 기록</button>}</div>
    {error&&<p className="attendance-error">{error}</p>}
    {data.isStaff&&<section className="teacher-class-cards consultation-class-cards">{data.isAdmin&&<button className={`consultation-all-class ${selectedClass==="all"?"active":""}`} onClick={()=>setSelectedClass("all")} style={{"--class-color":"#9f2b61"}as CSSProperties}><i/><span><small>관리자 통합 조회</small><b>전체 클래스</b><em>모든 학생의 상담 기록</em></span><strong>{data.students.length}명</strong></button>}{classes.map((item)=><button key={item.id}{...classSortable.itemProps(item.id)} data-drag-handle className={`${selectedClass===item.id?"active":""} ${classSortable.draggingId===item.id?"dragging":""}`.trim()} onClick={()=>setSelectedClass(item.id)} style={{"--class-color":item.color}as CSSProperties} aria-label={`${item.name}. 길게 눌러 순서 이동`}><i/><span><small>{item.subject}</small><b>{item.name}</b><em>{item.students.map((student)=>student.name).join(" · ")||"등록 학생 없음"}</em></span><strong>{item.students.length}명</strong></button>)}</section>}
    {data.isStaff&&<><div className="consultation-summary"><span>학부모 상담 필요 <b>{overdue.length}</b>명</span><i/><span>{selectedClass==="all"?"전체":"선택 클래스"} 상담 기록 <b>{classItems.length}</b>건</span><small>학부모 상담이 없거나 30일을 넘긴 학생을 표시합니다.</small></div>{overdue.length>0&&<section className="panel consultation-alert"><header><div><h2>학부모 상담이 필요한 학생</h2><span>마지막 학부모 상담이 30일 전이거나 학부모 상담 기록이 없는 학생입니다.</span></div></header><div>{overdue.map((student)=><button key={student.id} onClick={()=>setEditor({studentId:student.id,consultationType:"guardian"})}><i>{student.name.slice(0,1)}</i><span><b>{student.name}</b><small>{student.lastGuardianConsultedAt?`마지막 학부모 상담 ${formatDate(student.lastGuardianConsultedAt)} · ${student.daysSinceGuardian}일 전`:"학부모 상담 기록 없음"}</small></span><strong>＋ 학부모 상담</strong></button>)}</div></section>}</>}
    <section className="panel consultation-panel">{data.isStaff&&<div className="consultation-toolbar"><div className="search-wrap inner"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="학생·상담자 검색"/></div><nav aria-label="상담 대상 필터">{[["all","전체"],["guardian","학부모"],["student","학생"]].map(([value,label])=><button type="button" key={value} className={typeFilter===value?"active":""} onClick={()=>setTypeFilter(value)}>{label}</button>)}</nav><select aria-label="상담 기록 정렬" value={sortOrder} onChange={(event)=>setSortOrder(event.target.value as "latest"|"oldest")}><option value="latest">최신순</option><option value="oldest">오래된 순</option></select><span>{visible.length}건</span></div>}<div className="consultation-list">{visible.length===0?<div className="consultation-empty"><b>{query||typeFilter!=="all"?"검색 조건에 맞는 상담 기록이 없습니다.":data.isStaff?"아직 상담 기록이 없습니다.":"공유된 상담 기록이 없습니다."}</b>{data.isStaff&&!query&&typeFilter==="all"&&<button type="button" onClick={()=>setEditor({consultationType:"guardian"})}>＋ 첫 상담 기록</button>}</div>:visible.map((row)=><article key={row.id}><header><div className="consultation-person"><i>{row.studentName.slice(0,1)}</i><span><b>{row.studentName}</b><small>{typeLabels[row.consultationType]??"상담"} · {row.consultantName}</small></span></div><div className="consultation-date"><b>{formatDateTime(row.consultedAt)}</b></div>{data.isStaff&&<div className="consultation-actions"><button className="secondary-button" onClick={()=>setEditor({row})}>수정</button><button className="danger-link" onClick={()=>void remove(row)}>삭제</button></div>}</header><div className="consultation-notes"><section className="private"><b>상담 내용</b><p>{row.internalNote??row.guardianSummary??row.studentSummary??"입력된 상담 내용이 없습니다."}</p></section></div></article>)}</div></section>
    {editor&&<ConsultationEditor students={selectedStudents} row={editor.row} initialStudentId={editor.studentId} initialConsultationType={editor.consultationType} supabase={supabase} onClose={()=>setEditor(null)} onSaved={async()=>{setEditor(null);await load();}}/>}</>;
}

function ConsultationEditor({students,row,initialStudentId,initialConsultationType,supabase,onClose,onSaved}:{students:Named[];row?:Consultation;initialStudentId?:string;initialConsultationType?:"student"|"guardian";supabase:SupabaseClient;onClose:()=>void;onSaved:()=>Promise<void>}){
  const[studentId,setStudentId]=useState(row?.studentId??initialStudentId??students[0]?.id??"");const[consultationType,setConsultationType]=useState(row?.consultationType==="student"?"student":row?.consultationType==="guardian"?"guardian":initialConsultationType??"guardian");const[consultedAt,setConsultedAt]=useState(row?koreaDateTime(row.consultedAt):`${koreaToday()}T${koreaTime()}`);const[content,setContent]=useState(row?.internalNote??row?.guardianSummary??row?.studentSummary??"");const[saving,setSaving]=useState(false);const[error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError("");const{error:saveError}=await supabase.rpc("staff_save_consultation",{p_consultation_id:row?.id??null,p_student_id:studentId,p_consultation_type:consultationType,p_consulted_at:`${consultedAt}:00+09:00`,p_internal_note:content||null,p_guardian_summary:null,p_student_summary:null,p_next_contact_on:null});if(saveError){setError(readError(saveError.message));setSaving(false);}else await onSaved();};
  return<div className="modal-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className="student-modal consultation-editor" role="dialog" aria-modal="true"><header><div><p className="eyebrow">상담 기록</p><h2>{row?"상담 기록 수정":"새 상담 기록"}</h2><span>상담 대상과 내용을 간단히 기록해 주세요.</span></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><form onSubmit={submit}><div className="form-grid consultation-editor-grid"><label>학생 <b>*</b><select required value={studentId} onChange={(event)=>setStudentId(event.target.value)}><option value="">학생 선택</option>{students.map((student)=><option key={student.id} value={student.id}>{student.name}</option>)}</select></label><label>상담 대상 <b>*</b><select value={consultationType} onChange={(event)=>setConsultationType(event.target.value as "student"|"guardian")}><option value="guardian">학부모</option><option value="student">학생</option></select></label><label className="full">상담 일시 <b>*</b><input required type="datetime-local" value={consultedAt} onChange={(event)=>setConsultedAt(event.target.value)}/></label><label className="full consultation-private-field">상담 내용 <b>*</b><textarea required rows={7} value={content} onChange={(event)=>setContent(event.target.value)} placeholder="상담한 내용과 필요한 후속 사항을 기록해 주세요."/></label></div>{error&&<p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving||!studentId||!content.trim()}>{saving?"저장 중…":"상담 저장"}</button></footer></form></section></div>;
}
function dateParts(value:Date){const parts=new Intl.DateTimeFormat("en",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(value);return Object.fromEntries(parts.map((part)=>[part.type,part.value]));}
function koreaToday(){const item=dateParts(new Date());return`${item.year}-${item.month}-${item.day}`;}function koreaTime(){const item=dateParts(new Date());return`${item.hour==="24"?"00":item.hour}:${item.minute}`;}function koreaDateTime(value:string){const item=dateParts(new Date(value));return`${item.year}-${item.month}-${item.day}T${item.hour==="24"?"00":item.hour}:${item.minute}`;}function formatDate(value:string){return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"long",day:"numeric"}).format(new Date(value));}function formatDateTime(value:string){return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value));}function readError(message:string){return["입력해","선택해","교직원","담당 클래스","수정할 수"].some((word)=>message.includes(word))?message:"상담 기록을 저장하지 못했습니다. 입력 내용을 확인해 주세요.";}
