"use client";

import type { FormEvent } from "react";
import { useCallback,useEffect,useMemo,useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

type InviteRole="teacher"|"assistant"|"manager"|"student"|"guardian";
type Invite={id:string;codeHint:string;role:InviteRole;studentId:string|null;targetName:string;expiresAt:string;createdAt:string;usedAt:string|null;revokedAt:string|null;status:"active"|"used"|"revoked"|"expired"};
type Student={id:string;name:string;school:string|null;grade:string|null;hasAccount:boolean};
type Board={students:Student[];invites:Invite[]};
const labels:Record<InviteRole,string>={teacher:"선생님",assistant:"조교",manager:"실장님",student:"학생",guardian:"학부모"};
const statusLabels={active:"사용 가능",used:"가입 완료",revoked:"폐기됨",expired:"만료됨"};

export function InviteManager({supabase,onClose}:{supabase:SupabaseClient;onClose:()=>void}){
 const [board,setBoard]=useState<Board>({students:[],invites:[]}),[loading,setLoading]=useState(true),[role,setRole]=useState<InviteRole>("student"),[studentId,setStudentId]=useState(""),[days,setDays]=useState(14),[saving,setSaving]=useState(false),[smsSending,setSmsSending]=useState(false),[error,setError]=useState(""),[smsMessage,setSmsMessage]=useState(""),[issued,setIssued]=useState<{id:string;code:string;role:InviteRole;targetName:string;expiresAt:string}|null>(null);
 const load=useCallback(async()=>{setLoading(true);const{data,error:loadError}=await supabase.rpc("admin_account_invite_board");if(loadError)setError("초대코드 목록을 불러오지 못했습니다.");else setBoard(data as Board);setLoading(false)},[supabase]);
 useEffect(()=>{void load()},[load]);
 const available=useMemo(()=>board.students.filter(student=>role!=="student"||!student.hasAccount),[board.students,role]);
 const issue=async(event:FormEvent)=>{event.preventDefault();setError("");setSaving(true);const{data,error:issueError}=await supabase.rpc("admin_issue_account_invite",{p_role:role,p_student_id:role==="student"||role==="guardian"?studentId||null:null,p_valid_days:days});if(issueError)setError(issueError.message);else{setIssued(data as typeof issued);await load()}setSaving(false)};
 const revoke=async(id:string)=>{if(!window.confirm("이 초대코드를 폐기할까요? 폐기 후에는 가입할 수 없습니다."))return;const{error:revokeError}=await supabase.rpc("admin_revoke_account_invite",{p_invite_id:id});if(revokeError)setError(revokeError.message);else await load()};
 const copy=async()=>{if(!issued)return;await navigator.clipboard.writeText(`한살매 회원가입 초대코드: ${formatCode(issued.code)}\n운영 주소: https://hansalmae-student-manager.vercel.app`)};
 const sendSms=async()=>{if(!issued||!(issued.role==="student"||issued.role==="guardian"))return;setSmsSending(true);setSmsMessage("");const{data,error:sendError}=await supabase.functions.invoke("send-account-invite-sms",{body:{inviteId:issued.id,code:issued.code}});if(sendError){let text=sendError.message;const context=(sendError as{context?:Response}).context;if(context)try{const body=await context.clone().json()as{error?:string};if(body.error)text=body.error}catch{}setSmsMessage(text)}else{const result=data as{recipientName?:string;recipientPhone?:string};setSmsMessage(`${result.recipientName??issued.targetName}님 ${result.recipientPhone??"등록 연락처"}로 초대 문자를 발송했습니다.`)}setSmsSending(false)};
 return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section className="student-modal invite-manager" role="dialog" aria-modal="true"><header><div><p className="eyebrow">관리자 전용</p><h2>회원가입 초대코드</h2><span>역할과 연결 대상을 지정하면 1회용 코드가 생성됩니다.</span></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><div className="invite-layout"><form className="invite-issue" onSubmit={issue}><div className="invite-step"><i>1</i><span><b>가입 역할</b><small>가입자가 역할을 직접 바꿀 수 없습니다.</small></span></div><nav>{(["student","guardian","teacher","assistant","manager"] as InviteRole[]).map(item=><button type="button" key={item} className={role===item?"active":""} onClick={()=>{setRole(item);setStudentId("");setIssued(null);setSmsMessage("")}}>{labels[item]}</button>)}</nav>{(role==="student"||role==="guardian")&&<label>연결 학생<select required value={studentId} onChange={event=>setStudentId(event.target.value)}><option value="">학생을 선택해 주세요</option>{available.map(student=><option key={student.id} value={student.id}>{student.name}{student.school?` · ${student.school}`:""}{student.grade?` · ${student.grade}`:""}</option>)}</select></label>}<label>코드 유효기간<select value={days} onChange={event=>setDays(Number(event.target.value))}><option value={7}>7일</option><option value={14}>14일</option><option value={30}>30일</option></select></label><button className="primary invite-create" disabled={saving}>{saving?"발급 중…":"초대코드 발급"}</button>{error&&<p className="form-error">{error}</p>}{issued&&<section className="issued-code"><small>{labels[issued.role]} · {issued.targetName}</small><strong>{formatCode(issued.code)}</strong><span>{formatDate(issued.expiresAt)}까지 · 한 번만 사용 가능</span><div className="issued-code-actions"><button type="button" onClick={copy}>초대 문구 복사</button>{(issued.role==="student"||issued.role==="guardian")&&<button type="button" className="sms" disabled={smsSending} onClick={()=>void sendSms()}>{smsSending?"문자 발송 중…":"휴대폰으로 초대장 발송"}</button>}</div>{smsMessage&&<p className="invite-sms-message">{smsMessage}</p>}</section>}</form><section className="invite-history"><header><div><b>최근 발급 내역</b><span>보안을 위해 전체 코드는 발급 직후에만 표시됩니다.</span></div><em>{board.invites.filter(item=>item.status==="active").length}개 사용 가능</em></header>{loading?<p className="invite-empty">초대코드를 불러오는 중이에요…</p>:board.invites.length===0?<p className="invite-empty">아직 발급한 초대코드가 없습니다.</p>:<div>{board.invites.map(invite=><article key={invite.id}><span className={`invite-role ${invite.role}`}>{labels[invite.role]}</span><div><b>{invite.targetName}</b><small>••••-{invite.codeHint} · {formatDate(invite.expiresAt)}까지</small></div><em className={invite.status}>{statusLabels[invite.status]}</em>{invite.status==="active"&&<button type="button" onClick={()=>void revoke(invite.id)}>폐기</button>}</article>)}</div>}</section></div><footer><button className="secondary-button" onClick={onClose}>닫기</button></footer></section></div>
}
const formatCode=(code:string)=>`${code.slice(0,4)}-${code.slice(4)}`;
const formatDate=(value:string)=>new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"short",day:"numeric"}).format(new Date(value));
