"use client";
import {useEffect,useMemo,useState} from "react";
import type {SupabaseClient} from "@supabase/supabase-js";
import styles from "./monthly-lesson-coverage.module.css";
export type CoverageEvent={id:string;date:string;time:string|null;title:string;kind:string;state:string};
export type CoverageRow={studentId:string;name:string;school:string|null;grade:string|null;subject:string;enrollmentEnded?:boolean;target:number;version:number|null;attended:number;planned:number;unrecorded:number;absent:number;events:CoverageEvent[]};
type Coverage={month:string;today:string;isAdmin:boolean;items:CoverageRow[]};
export function coverageStatus(row:CoverageRow,ended:boolean){
 if(row.enrollmentEnded)return {kind:"neutral",label:"수강 종료",gap:0};
 if(row.target===0)return {kind:"neutral",label:"목표 제외",gap:0};
 if(row.attended>=row.target)return {kind:"good",label:"목표 달성",gap:0};
 const gap=Math.max(0,row.target-row.attended-row.planned);
 if(row.unrecorded)return {kind:"check",label:`기록 확인 ${row.unrecorded}건`,gap};
 if(gap)return {kind:"warning",label:ended?`${gap}회 미달`:`${gap}회 부족 예상`,gap};
 return {kind:"neutral",label:"달성 예정",gap:0};
}
export function MonthlyLessonCoverage({supabase,month,revision=0}:{supabase:SupabaseClient;month:string;revision?:number}){
 const [result,setResult]=useState<{month:string;data:Coverage}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[attempt,setAttempt]=useState(0);
 const [query,setQuery]=useState(""),[subject,setSubject]=useState(""),[onlyAttention,setOnlyAttention]=useState(true),[open,setOpen]=useState<string|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setError("");setOpen(null);void (async()=>{try{const {data,error:failure}=await supabase.rpc("staff_monthly_lesson_coverage",{p_month:month+"-01"});if(failure)throw failure;if(active)setResult({month,data:data as Coverage});}catch(e){if(active){setResult(null);setError((e as {message?:string}).message||"월별 수업 현황을 불러오지 못했습니다.");}}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[supabase,month,attempt,revision]);
 const data=result?.month===month?result.data:null,ended=Boolean(data&&month<data.today.slice(0,7));
 const rows=useMemo(()=>(data?.items??[]).filter(r=>(!subject||r.subject===subject)&&`${r.name} ${r.school??""}`.includes(query.trim())).sort((a,b)=>{const rank=(r:CoverageRow)=>{const s=coverageStatus(r,ended);return s.kind==="warning"?0:s.kind==="check"?1:2};return rank(a)-rank(b)||a.name.localeCompare(b.name,"ko")||a.subject.localeCompare(b.subject,"ko");}),[data,subject,query,ended]);
 const attention=rows.filter(r=>["warning","check"].includes(coverageStatus(r,ended).kind)),visible=onlyAttention?attention:rows;
 return <section className={styles.panel} aria-label="월별 수업 횟수">
  <header className={styles.header}><div><span className={styles.eyebrow}>국어 8회 · 영어 12회 / 월</span><h2>{Number(month.slice(5))}월 수업 현황</h2><p>정규·보강·추가 포함 · 첨삭 제외 · 실제 수업한 달 기준</p></div>{data&&!loading&&<span className={styles.count}>확인 필요 <b>{attention.length}</b>건</span>}</header>
  <div className={styles.filters}><label className={styles.search}><span className={styles.sr}>수업 횟수 학생 검색</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="학생 이름·학교 검색"/></label><select aria-label="수업 횟수 과목" value={subject} onChange={e=>setSubject(e.target.value)}><option value="">국어·영어 전체</option><option>국어</option><option>영어</option></select><button type="button" aria-pressed={onlyAttention} className={onlyAttention?styles.selected:""} onClick={()=>setOnlyAttention(v=>!v)}>확인 필요한 학생만</button></div>
  {loading?<p className={styles.empty}>월별 수업 현황을 확인하고 있어요.</p>:error?<p className={styles.empty} role="alert">{error} <button type="button" onClick={()=>setAttempt(v=>v+1)}>다시 시도</button></p>:!visible.length?<p className={styles.empty}>{onlyAttention?"현재 조건에서 확인이 필요한 학생이 없습니다. 전체 학생은 필터를 해제해 확인하세요.":"이 달에 집계할 국어·영어 수업이 없습니다."}</p>:<div className={styles.list}>{visible.map(r=>{const key=r.studentId+":"+r.subject,s=coverageStatus(r,ended),expanded=open===key;return <article key={key} className={styles.row}><button type="button" className={styles.rowButton} aria-expanded={expanded} onClick={()=>setOpen(expanded?null:key)}><span className={styles.person}><strong>{r.name}<i>{r.subject}</i></strong><small>{[r.school,r.grade].filter(Boolean).join(" · ")}</small></span><span className={styles.progress}><span><b>{r.attended}회 출석</b><small>＋ {r.planned}회 예정{r.enrollmentEnded?" / 지난 기록":` / 목표 ${r.target}회`}</small></span>{!r.enrollmentEnded&&<span className={styles.track}><i style={{width:`${r.target?Math.min(100,r.attended/r.target*100):0}%`}}/><em style={{width:`${r.target?Math.min(100-Math.min(100,r.attended/r.target*100),r.planned/r.target*100):0}%`}}/></span>}</span><span className={`${styles.badge} ${styles[s.kind]}`}>{s.label}</span><span aria-hidden="true">{expanded?"−":"＋"}</span></button>{expanded&&<div className={styles.detail}>{r.enrollmentEnded&&<p>수강이 종료되어 월 목표 확인 대상에서 제외됩니다. 기존 출결·수업 기록은 그대로 보관됩니다.</p>}<p>출석·지각만 출석 횟수에 포함합니다. 지난 수업의 미입력 출결은 ‘기록 확인’이며, 예정 수업은 출석을 보장하지 않습니다.</p>{r.unrecorded>0&&s.gap>0&&<p className={styles.warningText}>현재 기록·예정 기준 {s.gap}회 부족합니다. 미입력 출결을 먼저 확인해 주세요.</p>}<ul>{r.events.filter(e=>e.state!=="cancelled").map(e=><li key={e.id}><time>{e.date.slice(5).replace("-","/")} {e.time??"시간 미정"}</time><span>{e.title}<small>{e.kind}</small></span><b>{({attended:"출석",planned:"예정",absent:"미출석",unrecorded:"기록 확인"} as Record<string,string>)[e.state]??e.state}</b></li>)}</ul>{data?.isAdmin&&<TargetEditor key={key+":"+r.version} row={r} month={month} supabase={supabase} onSaved={()=>setAttempt(v=>v+1)}/>}</div>}</article>})}</div>}
  <footer className={styles.foot}>학생·과목별 집계입니다. 수강 종료 학생의 지난 기록은 ‘확인 필요한 학생만’을 해제하면 볼 수 있습니다. 중도 입학·휴원은 학생 상세에서 해당 월 목표를 조정하세요. 시간표 변경 전 미작성 기록은 당시 출결 확인이 필요합니다.</footer>
 </section>;
}
function TargetEditor({row,month,supabase,onSaved}:{row:CoverageRow;month:string;supabase:SupabaseClient;onSaved:()=>void}){
 const[value,setValue]=useState(String(row.target)),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const save=async()=>{const target=Number(value);if(!value.trim()||!Number.isInteger(target)||target<0||target>100){setError("0~100회로 입력해 주세요. 0회는 목표에서 제외합니다.");return;}setBusy(true);setError("");try{const {error:failure}=await supabase.rpc("admin_save_monthly_lesson_target",{p_student:row.studentId,p_subject:row.subject,p_month:month+"-01",p_target:target,p_expected_version:row.version});if(failure)throw failure;onSaved();}catch(e){setError((e as {message?:string}).message||"목표를 저장하지 못했습니다.");}finally{setBusy(false);}};
 return <div className={styles.target}><label>{Number(month.slice(5))}월 목표 <input type="number" min="0" max="100" value={value} disabled={busy} onChange={e=>setValue(e.target.value)}/>회</label><button type="button" disabled={busy||value===String(row.target)} onClick={()=>void save()}>{busy?"저장 중…":"목표 저장"}</button><small>이번 달에만 적용 · 0회는 목표 제외</small>{error&&<p role="alert">{error}</p>}</div>;
}
