"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

type AnalyticsData={students:{active:number;paused:number;completed:number;new:number;pausedInPeriod:number;completedInPeriod:number};billing:{charged:number;paid:number;outstanding:number};attendance:{total:number;present:number;late:number;absent:number;makeupNeeded:number;makeupCompleted:number};operations:{activeClasses:number;teachers:number;correctionStudents:number;vehicleStudents:number};classes:{id:string;name:string;subject:string;enrolled:number;teachers:number;attendanceRate:number}[];teachers:{id:string;name:string;classes:number;correctionStudents:number;consultations:number}[];monthly:{month:string;newStudents:number;charged:number;paid:number}[]};
type OverviewView="settings"|"students"|"schedule"|"attendance"|"assignments"|"tuition";
type AuditItem={id:string;name:string;detail:string};
type AuditCategory={key:string;title:string;description:string;severity:"critical"|"warning"|"info";actionLabel:string;actionView:OverviewView;count:number;items:AuditItem[]};
type AuditData={checkedAt:string;categories:AuditCategory[]};

export function OperationsAnalytics({supabase,onNavigate}:{supabase:SupabaseClient;onNavigate:(view:OverviewView)=>void}){
  const[from,setFrom]=useState(firstDay(-5)); const[to,setTo]=useState(today());
  const[data,setData]=useState<AnalyticsData|null>(null); const[audit,setAudit]=useState<AuditData|null>(null);
  const[loading,setLoading]=useState(true); const[error,setError]=useState(""); const[detailsOpen,setDetailsOpen]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError("");const[analyticsResult,auditResult]=await Promise.all([supabase.rpc("admin_operations_analytics",{p_from:from,p_to:to}),supabase.rpc("admin_operations_audit")]);if(analyticsResult.error||auditResult.error)setError("운영 현황을 모두 불러오지 못했습니다. 잠시 후 다시 확인해 주세요.");if(!analyticsResult.error)setData(analyticsResult.data as AnalyticsData);if(!auditResult.error)setAudit(auditResult.data as AuditData);setLoading(false);},[from,supabase,to]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  const attendanceRate=data?.attendance.total?Math.round(data.attendance.present/data.attendance.total*100):0; const collectionRate=data?.billing.charged?Math.round(data.billing.paid/data.billing.charged*100):0;
  const visibleAudits=useMemo(()=>audit?.categories.filter(item=>item.key!=="recent_assignments")??[],[audit]); const problemAudits=useMemo(()=>visibleAudits.filter(item=>item.count>0),[visibleAudits]); const issueCount=problemAudits.reduce((sum,item)=>sum+item.count,0); const healthyCount=visibleAudits.filter(item=>item.count===0).length;
  const maxMonthly=useMemo(()=>Math.max(1,...(data?.monthly??[]).map(x=>Math.max(x.charged,x.paid))),[data]);
  const csv=()=>{if(!data)return;const rows=[["구분","이름","항목1","항목2","항목3"],...data.classes.map(x=>["클래스",x.name,`재원 ${x.enrolled}`,`담당 ${x.teachers}`,`출석률 ${x.attendanceRate}%`]),...data.teachers.map(x=>["교직원",x.name,`클래스 ${x.classes}`,`첨삭 ${x.correctionStudents}`,`상담 ${x.consultations}`]),...data.monthly.map(x=>["월별",x.month,`신규 ${x.newStudents}`,`청구 ${x.charged}`,`수납 ${x.paid}`])];downloadCsv(`한살매_운영현황_${from}_${to}.csv`,rows)};
  return <div className="operations-overview"><div className="page-heading compact operations-heading"><div><p className="eyebrow">학원 운영 한눈에 보기</p><h1>운영 현황</h1><p>핵심 지표를 확인하고, 빠진 운영 항목은 바로 처리할 수 있습니다.</p></div><div className="operations-refresh"><span>{audit?`${formatDateTime(audit.checkedAt)} 점검`:""}</span><button className="secondary-button" disabled={loading} onClick={()=>void load()}>{loading?"확인 중…":"↻ 새로고침"}</button></div></div>{error&&<p className="attendance-error">{error}</p>}{loading&&!data?<section className="panel analytics-empty">운영 현황을 정리하는 중이에요…</section>:data&&<>
    <section className="overview-kpis"><Kpi label="재원생" value={`${data.students.active}명`} sub={`신규 ${data.students.new} · 휴원 ${data.students.paused}`} tone="neutral" onClick={()=>onNavigate("students")}/><Kpi label="수납률" value={`${collectionRate}%`} sub={`미납 ${money(data.billing.outstanding)}`} tone={data.billing.outstanding>0?"warning":"healthy"} onClick={()=>onNavigate("tuition")}/><Kpi label="출석률" value={`${attendanceRate}%`} sub={`결석 ${data.attendance.absent} · 지각 ${data.attendance.late}`} tone="neutral" onClick={()=>onNavigate("attendance")}/><Kpi label="미처리 보강" value={`${Math.max(0,data.attendance.makeupNeeded-data.attendance.makeupCompleted)}건`} sub={`완료 ${data.attendance.makeupCompleted}건`} tone={data.attendance.makeupNeeded>data.attendance.makeupCompleted?"warning":"healthy"}/><Kpi label="확인 필요" value={`${issueCount}건`} sub={issueCount?`${problemAudits.length}개 항목에서 발견`:`운영 설정 정상`} tone={issueCount?"danger":"healthy"}/></section>
    <section className="overview-secondary" aria-label="운영 보조 지표"><span>운영 클래스 <b>{data.operations.activeClasses}개</b></span><span>교직원 <b>{data.operations.teachers}명</b></span><span>첨삭 학생 <b>{data.operations.correctionStudents}명</b></span><span>차량 학생 <b>{data.operations.vehicleStudents}명</b></span></section>
    <section className="panel operations-checks"><header><div><p className="eyebrow">바로 처리할 항목</p><h2>{issueCount?`${issueCount}건의 확인이 필요합니다`:`현재 운영 설정이 정상입니다`}</h2><span>{issueCount?"항목을 누르면 해당 관리 화면으로 바로 이동합니다.":`${healthyCount}개 점검 항목을 모두 통과했습니다.`}</span></div><div className={issueCount?"check-status warning":"check-status healthy"}>{issueCount?"확인 필요":"정상"}</div></header>{problemAudits.length?<div className="operations-check-grid">{problemAudits.map(category=><article key={category.key} className={category.severity}><div><i>{category.severity==="critical"?"!":"△"}</i><span><b>{category.title}</b><small>{category.description}</small></span><strong>{category.count}건</strong></div><div className="check-preview">{category.items.slice(0,3).map(item=><span key={`${category.key}-${item.id}`}>{item.name}<small>{item.detail}</small></span>)}{category.count>3&&<em>외 {category.count-3}건</em>}</div><button onClick={()=>onNavigate(category.actionView)}>{category.actionLabel}에서 처리 <span>›</span></button></article>)}</div>:<div className="operations-all-clear"><i>✓</i><span><b>지금 바로 처리할 누락 항목이 없습니다.</b><small>계정 연결, 수강 배정, 담당 교사, 시간표, 연락 정보와 최근 출결을 확인했습니다.</small></span></div>}{healthyCount>0&&<p className="operations-healthy-note">정상 항목 {healthyCount}개는 간결하게 숨겼습니다.</p>}</section>
    <section className={`panel operations-details ${detailsOpen?"is-open":""}`}><button className="operations-details-toggle" onClick={()=>setDetailsOpen(value=>!value)} aria-expanded={detailsOpen}><span><b>상세 통계</b><small>월별 청구·수납, 클래스와 교직원 배정 현황</small></span><em>{detailsOpen?"접기":"펼쳐보기"} {detailsOpen?"⌃":"⌄"}</em></button>{detailsOpen&&<div className="operations-details-body"><div className="analytics-actions"><label>시작<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>종료<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="secondary-button" disabled={!data} onClick={csv}>CSV 다운로드</button></div><section className="analytics-monthly"><header><h2>월별 청구·수납</h2><small><i/> 청구 <em/> 수납</small></header><div>{data.monthly.map(x=><article key={x.month}><b>{formatMonth(x.month)}</b><span><i style={{width:`${x.charged/maxMonthly*100}%`}}/><em style={{width:`${x.paid/maxMonthly*100}%`}}/></span><small>청구 {money(x.charged)} · 수납 {money(x.paid)} · 신규 {x.newStudents}명</small></article>)}</div></section><div className="analytics-tables"><AnalyticsTable title="클래스 현황" heads={["클래스","재원","담당","출석률"]} rows={data.classes.map(x=>[`${x.name} · ${x.subject}`,`${x.enrolled}명`,`${x.teachers}명`,`${x.attendanceRate}%`])}/><AnalyticsTable title="교직원 배정" heads={["이름","클래스","첨삭","상담"]} rows={data.teachers.map(x=>[x.name,`${x.classes}개`,`${x.correctionStudents}명`,`${x.consultations}건`])}/></div></div>}</section>
  </>}</div>;
}
function Kpi({label,value,sub,tone,onClick}:{label:string;value:string;sub:string;tone:"neutral"|"warning"|"danger"|"healthy";onClick?:()=>void}){const content=<><span>{label}</span><b>{value}</b><small>{sub}</small>{onClick&&<em>바로가기 ›</em>}</>;return onClick?<button className={tone} onClick={onClick}>{content}</button>:<article className={tone}>{content}</article>}
function AnalyticsTable({title,heads,rows}:{title:string;heads:string[];rows:string[][]}){return <section className="analytics-table"><header><h2>{title}</h2></header><div className="analytics-table-row head">{heads.map(x=><b key={x}>{x}</b>)}</div>{rows.length?rows.map((r,i)=><div className="analytics-table-row" key={i}>{r.map((x,j)=><span key={j}>{x}</span>)}</div>):<p>표시할 데이터가 없습니다.</p>}</section>}
function money(v:number){return`${new Intl.NumberFormat("ko-KR").format(v)}원`}function today(){return new Date(Date.now()+9*3600000).toISOString().slice(0,10)}function firstDay(offset:number){const d=new Date();d.setUTCMonth(d.getUTCMonth()+offset,1);return d.toISOString().slice(0,10)}function formatMonth(v:string){return new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"short"}).format(new Date(v))}function formatDateTime(v:string){return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(v))}function downloadCsv(name:string,rows:string[][]){const text="\ufeff"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
