"use client";

import type { FormEvent } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { InviteManager } from "./invite-manager";
import { GuardianLinkRequests } from "./guardian-link-requests";

type UserRole = "admin"|"teacher"|"assistant"|"manager"|"student"|"guardian";
type Child = { id:string; name:string };
type Account = { id:string; email:string; displayName:string; phone:string|null; role:UserRole; isActive:boolean; isSelf:boolean; studentId:string|null; studentName:string|null; guardianId:string|null; children:Child[] };
type Student = { id:string; name:string; profileId:string|null };
type ChangeLog = { id:string; action:string; details:Record<string,unknown>; targetName:string; changedByName:string; createdAt:string };
type BoardData = { accounts:Account[]; students:Student[]; logs:ChangeLog[] };
const roleLabels:Record<UserRole,string> = { admin:"관리자",teacher:"교사",assistant:"조교",manager:"실장님",student:"학생",guardian:"학부모" };
const actionLabels:Record<string,string> = { account_updated:"계정 정보·역할 변경",student_link_changed:"학생 정보 연결 변경",guardian_children_changed:"자녀 연결 변경",teacher_classes_changed:"담당 클래스 연결 변경" };

function AccountSettingsContent({ supabase }: { supabase:SupabaseClient }) {
  const [data,setData] = useState<BoardData>({ accounts:[],students:[],logs:[] }); const [loading,setLoading] = useState(true); const [error,setError] = useState(""); const [query,setQuery] = useState(""); const [role,setRole] = useState<"all"|UserRole>("all"); const [editing,setEditing] = useState<Account|null>(null); const [invitesOpen,setInvitesOpen] = useState(false); const [creating,setCreating] = useState(false); const [created,setCreated] = useState<{email:string;password:string}|null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); const { data:next,error:loadError } = await supabase.rpc("admin_account_board"); if (loadError) setError("계정 설정을 불러오지 못했습니다. 관리자 계정인지 확인해 주세요."); else setData(next as BoardData); setLoading(false); },[supabase]);
  useEffect(() => { void load(); },[load]);
  const accounts = useMemo(() => { const text=query.trim().toLowerCase(); return data.accounts.filter((account) => (role === "all" || account.role === role) && (!text || [account.displayName,account.email,account.studentName ?? "",...account.children.map((child) => child.name)].some((value) => value.toLowerCase().includes(text)))); },[data.accounts,query,role]);
  if (loading) return <section className="panel settings-empty">계정 설정을 불러오는 중이에요…</section>;
  return <><div className="page-heading compact"><div><p className="eyebrow">관리자 전용</p><h1>계정·역할 설정</h1><p>초대 가입과 관리자 직접 생성을 상황에 맞게 선택할 수 있습니다.</p></div><div className="account-heading-actions"><button className="secondary-button" onClick={()=>{setCreated(null);setCreating(true)}}>직접 계정 만들기</button><button className="primary" onClick={() => setInvitesOpen(true)}>＋ 회원가입 초대</button></div></div>{error && <p className="attendance-error">{error}</p>}<section className="settings-guide"><b>초대 가입을 권장해요</b><span>사용자가 본인 비밀번호를 정하게 하거나, 급할 때는 관리자가 이메일과 임시 비밀번호를 직접 만들어 주세요.</span></section>{created&&<section className="settings-created"><span><b>직접 생성 완료</b>{created.email} · 임시 비밀번호 <strong>{created.password}</strong></span><button className="secondary-button" onClick={()=>void navigator.clipboard.writeText(`이메일: ${created.email}\n임시 비밀번호: ${created.password}\n접속 주소: https://hansalmae-student-manager.vercel.app`)}>접속 정보 복사</button></section>}
    <div className="makeup-summary"><span>전체 계정 <b>{data.accounts.length}</b></span><span>교직원 <b>{data.accounts.filter((item) => ["admin","teacher","assistant","manager"].includes(item.role)).length}</b></span><span>비활성 <b>{data.accounts.filter((item) => !item.isActive).length}</b></span></div>
    <section className="panel account-panel"><div className="account-toolbar"><div className="search-wrap inner"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="이름, 이메일, 연결 학생 검색" /></div><select value={role} onChange={(event) => setRole(event.target.value as "all"|UserRole)}><option value="all">전체 역할</option>{Object.entries(roleLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="account-table"><div className="account-head"><span>계정</span><span>역할</span><span>연결 정보</span><span>상태</span><span /></div>{accounts.length === 0 ? <p className="settings-empty">검색 결과가 없습니다.</p> : accounts.map((account) => <article key={account.id}><div className="account-person"><i>{account.displayName.slice(0,1)}</i><span><b>{account.displayName}{account.isSelf && <em>내 계정</em>}</b><small>{account.email}</small></span></div><strong>{roleLabels[account.role]}</strong><span className="account-link">{account.role === "student" ? account.studentName ?? "학생 미연결" : account.role === "guardian" ? account.children.length ? account.children.map((child) => child.name).join(", ") : "자녀 미연결" : account.role === "teacher" ? "교사 계정" : account.role === "assistant" ? "조교 계정" : account.role === "manager" ? "실장님 계정" : "전체 관리자"}</span><i className={account.isActive ? "active" : "inactive"}>{account.isActive ? "활성" : "비활성"}</i><button className="secondary-button" onClick={() => setEditing(account)}>설정</button></article>)}</div></section>
    <section className="panel account-history"><header><h2>최근 변경 이력</h2><span>최근 50건</span></header>{data.logs.length === 0 ? <p className="settings-empty">아직 계정 변경 이력이 없습니다.</p> : <div>{data.logs.map((log) => <article key={log.id}><i>⚙</i><span><b>{log.targetName} · {actionLabels[log.action] ?? log.action}</b><small>{log.changedByName} 관리자 · {formatDateTime(log.createdAt)}</small></span></article>)}</div>}</section>{editing && <AccountEditor account={editing} data={data} supabase={supabase} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); }} />}{invitesOpen&&<InviteManager supabase={supabase} onClose={()=>setInvitesOpen(false)}/>} {creating&&<AccountCreator data={data} supabase={supabase} onClose={()=>setCreating(false)} onCreated={async credentials=>{setCreating(false);setCreated(credentials);await load()}}/>}</>;
}

export function SettingsBoard({supabase}:{supabase:SupabaseClient}){
  return <><GuardianLinkRequests supabase={supabase}/><AccountHelpRequests supabase={supabase}/><AccountSettingsContent supabase={supabase}/></>;
}

type HelpRequest={id:string;requesterName:string;accountType:"student"|"guardian"|"staff";registeredPhone:string|null;reachablePhone:string;reason:"phone_changed"|"sms_unavailable"|"other";profileId:string|null;requestedAt:string;matchedName:string|null;matchedRole:UserRole|null};
function AccountHelpRequests({supabase}:{supabase:SupabaseClient}){
 const[rows,setRows]=useState<HelpRequest[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[selected,setSelected]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[processing,setProcessing]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);const[{data:requests},{data:board}]=await Promise.all([supabase.rpc("admin_account_help_board"),supabase.rpc("admin_account_board")]);const next=(requests??[])as HelpRequest[];setRows(next);setAccounts(((board as BoardData|null)?.accounts??[]));setSelected(Object.fromEntries(next.map(row=>[row.id,row.profileId??""])));setLoading(false)},[supabase]);useEffect(()=>{void load()},[load]);
 const process=async(row:HelpRequest,action:"approve"|"reject")=>{const profileId=selected[row.id];if(action==="approve"&&!profileId)return setMessage("본인 확인이 끝난 계정을 선택해 주세요.");const account=accounts.find(item=>item.id===profileId);if(!window.confirm(action==="approve"?`${account?.displayName??row.requesterName} 계정의 연락처를 ${row.reachablePhone} 번호로 바꾸고 임시 비밀번호를 문자로 보낼까요? 본인 확인을 마친 경우에만 진행해 주세요.`:`${row.requesterName}님의 도움 요청을 거절할까요?`))return;setProcessing(row.id);setMessage("");const{data:{session}}=await supabase.auth.getSession();if(!session){setMessage("로그인 세션이 만료되었습니다. 다시 로그인해 주세요.");setProcessing("");return}const{data,error}=await supabase.functions.invoke("admin-account-help",{body:{action,requestId:row.id,profileId},headers:{Authorization:`Bearer ${session.access_token}`}});if(error){let text=error.message;const context=(error as{context?:Response}).context;if(context)try{const body=await context.clone().json()as{error?:string};if(body.error)text=body.error}catch{}setMessage(text)}else{const result=data as{recipientPhone?:string};setMessage(action==="approve"?`처리 완료: ${result.recipientPhone??row.reachablePhone} 번호로 임시 비밀번호를 보냈습니다.`:"요청을 거절 처리했습니다.");await load()}setProcessing("")};
 const reasonLabel={phone_changed:"등록번호 변경",sms_unavailable:"문자 수신 불가",other:"기타"};
 return <section className="panel account-help-panel"><header><div><p className="eyebrow">관리자 본인 확인 필요</p><h2>계정 확인 도움 요청</h2><span>기존 학생·학부모 정보와 전화 또는 대면 확인을 마친 뒤 처리해 주세요.</span></div><em>{rows.length}건 대기</em></header>{message?<p className="password-reset-message">{message}</p>:null}{loading?<p className="settings-empty">요청을 확인하는 중이에요…</p>:rows.length===0?<p className="settings-empty">대기 중인 계정 도움 요청이 없습니다.</p>:<div className="account-help-list">{rows.map(row=><article key={row.id}><div className="account-help-request"><div className="account-help-person"><span><b>{row.requesterName}</b><em>{row.accountType==="student"?"학생":row.accountType==="guardian"?"학부모":"교직원"}</em></span><strong>{reasonLabel[row.reason]}</strong><dl><div><dt>기존 등록 번호</dt><dd>{row.registeredPhone?formatPhoneNumber(row.registeredPhone):"미입력"}</dd></div><div><dt>현재 연락 번호</dt><dd>{formatPhoneNumber(row.reachablePhone)}</dd></div></dl></div><time>요청 {formatDateTime(row.requestedAt)}</time></div><div className="account-help-resolution"><label>본인 확인된 계정<select value={selected[row.id]??""} onChange={e=>setSelected(current=>({...current,[row.id]:e.target.value}))}><option value="">계정을 선택해 주세요</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.displayName} · {roleLabels[account.role]} · {account.email}</option>)}</select><small>선택한 계정의 연락처를 현재 번호로 변경하고 임시 비밀번호를 발송합니다.</small></label><div className="account-help-actions"><button className="secondary-button" disabled={processing===row.id} onClick={()=>void process(row,"reject")}>거절</button><button className="primary" disabled={processing===row.id||!selected[row.id]} onClick={()=>void process(row,"approve")}>{processing===row.id?"처리 중…":"확인 후 변경·문자 발송"}</button></div></div></article>)}</div>}</section>
}

function GuardianChildPicker({students,childIds,onToggle,required=false}:{students:Student[];childIds:string[];onToggle:(id:string)=>void;required?:boolean}) {
  const[query,setQuery]=useState("");
  const visibleStudents=useMemo(()=>{
    const text=query.trim().toLowerCase();
    return students.filter(student=>!text||student.name.toLowerCase().includes(text));
  },[students,query]);
  return <fieldset className="editor-checklist guardian-child-picker full"><legend>자녀 연결 {required&&<b>*</b>}</legend><div className="guardian-child-toolbar"><span className="search-wrap inner"><i>⌕</i><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="학생 이름 검색" /></span><em>{childIds.length}명 선택</em></div><div className="guardian-child-options">{visibleStudents.length?visibleStudents.map(student=>{const active=childIds.includes(student.id);return <label key={student.id} className={active?"active":""}><input type="checkbox" checked={active} onChange={()=>onToggle(student.id)} /><span><b>{student.name}</b><small>{active?"자녀로 연결됨":"눌러서 선택"}</small></span></label>}):<p>검색 결과가 없습니다.</p>}</div></fieldset>;
}

function AccountCreator({ data,supabase,onClose,onCreated }: { data:BoardData; supabase:SupabaseClient; onClose:()=>void; onCreated:(credentials:{ email:string; password:string })=>Promise<void> }) {
  const [email,setEmail] = useState(""); const [password,setPassword] = useState(() => makePassword()); const [displayName,setDisplayName] = useState(""); const [phone,setPhone] = useState(""); const [role,setRole] = useState<UserRole>("teacher"); const [studentId,setStudentId] = useState(""); const [childIds,setChildIds] = useState<string[]>([]); const [saving,setSaving] = useState(false); const [error,setError] = useState("");
  const availableStudents = data.students.filter((student) => !student.profileId);
  const toggleChild = (id:string) => setChildIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current,id]);
  const submit = async (event:FormEvent) => { event.preventDefault(); setSaving(true); setError(""); const payload={ email:email.trim(),password,displayName:displayName.trim(),phone:phone.trim() || null,role,studentId:role === "student" ? studentId || null : null,childIds:role === "guardian" ? childIds : [] }; const { error:invokeError }=await supabase.functions.invoke("admin-create-user",{ body:payload }); if (invokeError) { let message=invokeError.message; const context=(invokeError as { context?:Response }).context; if (context) { try { const body=await context.clone().json() as { error?:string }; if (body.error) message=body.error; } catch {} } setError(readCreateError(message)); setSaving(false); return; } await onCreated({ email:payload.email,password }); };
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="student-modal account-create-modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">관리자 전용</p><h2>새 로그인 계정</h2><span>로그인 정보와 역할을 한 번에 등록합니다.</span></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><form onSubmit={submit}><div className="form-grid"><label>이메일 <b>*</b><input required type="email" autoComplete="off" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@example.com" /></label><label>임시 비밀번호 <b>*</b><span className="password-field"><input required minLength={8} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} /><button type="button" onClick={() => setPassword(makePassword())}>새로 만들기</button></span></label><label>표시 이름 <b>*</b><input required value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="예: 김선생" /></label><label>연락처<input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="010-0000-0000" /></label><label>계정 역할<select value={role} onChange={(event) => { setRole(event.target.value as UserRole); setStudentId(""); setChildIds([]); }}><option value="admin">관리자</option><option value="teacher">교사</option><option value="assistant">조교</option><option value="manager">실장님</option><option value="student">학생</option><option value="guardian">학부모</option></select></label>{role === "student" && <label>학생 정보 연결<select value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">나중에 연결</option>{availableStudents.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label>}{role === "guardian" && <GuardianChildPicker students={data.students} childIds={childIds} onToggle={toggleChild} />}</div><p className="settings-self-note">이메일은 확인 완료 상태로 생성됩니다. 임시 비밀번호를 사용자에게 직접 전달해 주세요.</p>{error && <p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving || (role === "guardian" && !phone.trim())}>{saving ? "계정 만드는 중…" : "로그인 계정 만들기"}</button></footer></form></section></div>;
}

function AccountEditor({ account,data,supabase,onClose,onSaved }: { account:Account; data:BoardData; supabase:SupabaseClient; onClose:()=>void; onSaved:()=>Promise<void> }) {
  const [displayName,setDisplayName] = useState(account.displayName); const [phone,setPhone] = useState(account.phone ?? ""); const [role,setRole] = useState<UserRole>(account.role); const [isActive,setIsActive] = useState(account.isActive); const [studentId,setStudentId] = useState(account.studentId ?? ""); const [childIds,setChildIds] = useState(account.children.map((child) => child.id)); const [saving,setSaving] = useState(false); const [error,setError] = useState("");
  const toggleChild = (id:string) => setChildIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current,id]);
  const submit = async (event:FormEvent) => { event.preventDefault(); setSaving(true); setError(""); const { error:saveError } = await supabase.rpc("admin_save_account_settings",{ p_profile_id:account.id,p_display_name:displayName,p_phone:phone || null,p_role:role,p_is_active:isActive,p_student_id:role === "student" ? studentId || null : null,p_child_ids:role === "guardian" ? childIds : [] }); if (saveError) { setError(readError(saveError.message)); setSaving(false); return; } await onSaved(); };
  const availableStudents = data.students.filter((student) => !student.profileId || student.profileId === account.id);
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="student-modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">관리자 계정 설정</p><h2>{account.displayName}</h2><span>{account.email}</span></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><form onSubmit={submit}><div className="form-grid"><label>표시 이름 <b>*</b><input required value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></label><label>연락처<input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="010-0000-0000" /></label><label>계정 역할<select disabled={account.isSelf} value={role} onChange={(event) => { setRole(event.target.value as UserRole); setStudentId(""); setChildIds([]); }}><option value="admin">관리자</option><option value="teacher">교사</option><option value="assistant">조교</option><option value="manager">실장님</option><option value="student">학생</option><option value="guardian">학부모</option></select></label><label className="account-active-check"><input type="checkbox" disabled={account.isSelf} checked={isActive} onChange={(event) => setIsActive(event.target.checked)} /><span><b>로그인 활성화</b><small>비활성화하면 다음 역할 확인부터 앱에 접근할 수 없습니다.</small></span></label>{role === "student" && <label className="full">학생 정보 연결<select value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">연결하지 않음</option>{availableStudents.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label>}{role === "guardian" && <GuardianChildPicker students={data.students} childIds={childIds} onToggle={toggleChild} required />}</div>{account.isSelf && <p className="settings-self-note">현재 로그인한 관리자 본인의 역할과 활성 상태는 변경할 수 없습니다.</p>}{error && <p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving || (role === "guardian" && !phone)}>{saving ? "저장 중…" : "계정 설정 저장"}</button></footer></form></section></div>;
}

function formatDateTime(value:string) { return new Intl.DateTimeFormat("ko-KR",{ timeZone:"Asia/Seoul",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false }).format(new Date(value)); }
function formatPhoneNumber(value:string) { const phone=value.replace(/\D/g,""); if(phone.length===11)return `${phone.slice(0,3)}-${phone.slice(3,7)}-${phone.slice(7)}`; if(phone.length===10)return `${phone.slice(0,3)}-${phone.slice(3,6)}-${phone.slice(6)}`; return value; }
function readError(message:string) { return ["관리자","입력해","선택해","찾을 수","이미 다른","연락처","현재 로그인"].some((word) => message.includes(word)) ? message : "계정 설정을 저장하지 못했습니다. 연결 정보를 확인해 주세요."; }
function readCreateError(message:string) { if (message.includes("already") || message.includes("registered")) return "이미 가입된 이메일입니다."; return ["관리자","이메일","비밀번호","이름","연락처","학생","계정"].some((word) => message.includes(word)) ? message : "로그인 계정을 만들지 못했습니다. 입력 내용을 확인해 주세요."; }
function makePassword() { const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$"; const values=crypto.getRandomValues(new Uint32Array(12)); return Array.from(values,(value) => chars[value % chars.length]).join(""); }
