"use client";

import type { FormEvent } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

type UserRole = "admin"|"teacher"|"student"|"guardian";
type Child = { id:string; name:string };
type Account = { id:string; email:string; displayName:string; phone:string|null; role:UserRole; isActive:boolean; isSelf:boolean; studentId:string|null; studentName:string|null; guardianId:string|null; children:Child[] };
type Student = { id:string; name:string; profileId:string|null };
type ChangeLog = { id:string; action:string; details:Record<string,unknown>; targetName:string; changedByName:string; createdAt:string };
type BoardData = { accounts:Account[]; students:Student[]; logs:ChangeLog[] };
const roleLabels:Record<UserRole,string> = { admin:"관리자",teacher:"교사",student:"학생",guardian:"학부모" };
const actionLabels:Record<string,string> = { account_updated:"계정 정보·역할 변경",student_link_changed:"학생 정보 연결 변경",guardian_children_changed:"자녀 연결 변경" };

export function SettingsBoard({ supabase }: { supabase:SupabaseClient }) {
  const [data,setData] = useState<BoardData>({ accounts:[],students:[],logs:[] }); const [loading,setLoading] = useState(true); const [error,setError] = useState(""); const [query,setQuery] = useState(""); const [role,setRole] = useState<"all"|UserRole>("all"); const [editing,setEditing] = useState<Account|null>(null);
  const load = useCallback(async () => { setLoading(true); setError(""); const { data:next,error:loadError } = await supabase.rpc("admin_account_board"); if (loadError) setError("계정 설정을 불러오지 못했습니다. 관리자 계정인지 확인해 주세요."); else setData(next as BoardData); setLoading(false); },[supabase]);
  useEffect(() => { void load(); },[load]);
  const accounts = useMemo(() => { const text=query.trim().toLowerCase(); return data.accounts.filter((account) => (role === "all" || account.role === role) && (!text || [account.displayName,account.email,account.studentName ?? "",...account.children.map((child) => child.name)].some((value) => value.toLowerCase().includes(text)))); },[data.accounts,query,role]);
  if (loading) return <section className="panel settings-empty">계정 설정을 불러오는 중이에요…</section>;
  return <><div className="page-heading compact"><div><p className="eyebrow">관리자 전용</p><h1>계정·역할 설정</h1><p>Supabase Auth에 이미 생성된 로그인 계정의 역할과 학생·자녀 연결을 관리합니다.</p></div></div>{error && <p className="attendance-error">{error}</p>}<section className="settings-guide"><b>새 로그인 계정은 어디서 만드나요?</b><span>Supabase → Authentication → Users에서 계정을 먼저 만든 뒤 이 화면에서 역할과 연결 대상을 지정하세요.</span></section>
    <div className="makeup-summary"><span>전체 계정 <b>{data.accounts.length}</b></span><span>교직원 <b>{data.accounts.filter((item) => item.role === "admin" || item.role === "teacher").length}</b></span><span>비활성 <b>{data.accounts.filter((item) => !item.isActive).length}</b></span></div>
    <section className="panel account-panel"><div className="account-toolbar"><div className="search-wrap inner"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="이름, 이메일, 연결 학생 검색" /></div><select value={role} onChange={(event) => setRole(event.target.value as "all"|UserRole)}><option value="all">전체 역할</option>{Object.entries(roleLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="account-table"><div className="account-head"><span>계정</span><span>역할</span><span>연결 정보</span><span>상태</span><span /></div>{accounts.length === 0 ? <p className="settings-empty">검색 결과가 없습니다.</p> : accounts.map((account) => <article key={account.id}><div className="account-person"><i>{account.displayName.slice(0,1)}</i><span><b>{account.displayName}{account.isSelf && <em>내 계정</em>}</b><small>{account.email}</small></span></div><strong>{roleLabels[account.role]}</strong><span className="account-link">{account.role === "student" ? account.studentName ?? "학생 미연결" : account.role === "guardian" ? account.children.length ? account.children.map((child) => child.name).join(", ") : "자녀 미연결" : account.role === "teacher" ? "교사 계정" : "전체 관리자"}</span><i className={account.isActive ? "active" : "inactive"}>{account.isActive ? "활성" : "비활성"}</i><button className="secondary-button" onClick={() => setEditing(account)}>설정</button></article>)}</div></section>
    <section className="panel account-history"><header><h2>최근 변경 이력</h2><span>최근 50건</span></header>{data.logs.length === 0 ? <p className="settings-empty">아직 계정 변경 이력이 없습니다.</p> : <div>{data.logs.map((log) => <article key={log.id}><i>⚙</i><span><b>{log.targetName} · {actionLabels[log.action] ?? log.action}</b><small>{log.changedByName} 관리자 · {formatDateTime(log.createdAt)}</small></span></article>)}</div>}</section>{editing && <AccountEditor account={editing} data={data} supabase={supabase} onClose={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); }} />}</>;
}

function AccountEditor({ account,data,supabase,onClose,onSaved }: { account:Account; data:BoardData; supabase:SupabaseClient; onClose:()=>void; onSaved:()=>Promise<void> }) {
  const [displayName,setDisplayName] = useState(account.displayName); const [phone,setPhone] = useState(account.phone ?? ""); const [role,setRole] = useState<UserRole>(account.role); const [isActive,setIsActive] = useState(account.isActive); const [studentId,setStudentId] = useState(account.studentId ?? ""); const [childIds,setChildIds] = useState(account.children.map((child) => child.id)); const [saving,setSaving] = useState(false); const [error,setError] = useState("");
  const toggleChild = (id:string) => setChildIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current,id]);
  const submit = async (event:FormEvent) => { event.preventDefault(); setSaving(true); setError(""); const { error:saveError } = await supabase.rpc("admin_save_account_settings",{ p_profile_id:account.id,p_display_name:displayName,p_phone:phone || null,p_role:role,p_is_active:isActive,p_student_id:role === "student" ? studentId || null : null,p_child_ids:role === "guardian" ? childIds : [] }); if (saveError) { setError(readError(saveError.message)); setSaving(false); return; } await onSaved(); };
  const availableStudents = data.students.filter((student) => !student.profileId || student.profileId === account.id);
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="student-modal" role="dialog" aria-modal="true"><header><div><p className="eyebrow">관리자 계정 설정</p><h2>{account.displayName}</h2><span>{account.email}</span></div><button type="button" aria-label="닫기" onClick={onClose}>×</button></header><form onSubmit={submit}><div className="form-grid"><label>표시 이름 <b>*</b><input required value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></label><label>연락처<input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="010-0000-0000" /></label><label>계정 역할<select disabled={account.isSelf} value={role} onChange={(event) => { setRole(event.target.value as UserRole); setStudentId(""); setChildIds([]); }}><option value="admin">관리자</option><option value="teacher">교사</option><option value="student">학생</option><option value="guardian">학부모</option></select></label><label className="account-active-check"><input type="checkbox" disabled={account.isSelf} checked={isActive} onChange={(event) => setIsActive(event.target.checked)} /><span><b>로그인 활성화</b><small>비활성화하면 다음 역할 확인부터 앱에 접근할 수 없습니다.</small></span></label>{role === "student" && <label className="full">학생 정보 연결<select value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">연결하지 않음</option>{availableStudents.map((student) => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label>}{role === "guardian" && <fieldset className="editor-checklist full"><legend>자녀 연결 <b>*</b></legend><div>{data.students.map((student) => <label key={student.id}><input type="checkbox" checked={childIds.includes(student.id)} onChange={() => toggleChild(student.id)} />{student.name}</label>)}</div></fieldset>}</div>{account.isSelf && <p className="settings-self-note">현재 로그인한 관리자 본인의 역할과 활성 상태는 변경할 수 없습니다.</p>}{error && <p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving || (role === "guardian" && !phone)}>{saving ? "저장 중…" : "계정 설정 저장"}</button></footer></form></section></div>;
}

function formatDateTime(value:string) { return new Intl.DateTimeFormat("ko-KR",{ timeZone:"Asia/Seoul",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false }).format(new Date(value)); }
function readError(message:string) { return ["관리자","입력해","선택해","찾을 수","이미 다른","연락처","현재 로그인"].some((word) => message.includes(word)) ? message : "계정 설정을 저장하지 못했습니다. 연결 정보를 확인해 주세요."; }
