"use client";

import type { CSSProperties, FormEvent } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Profile } from "./supabase";

type Subject={id:string;name:string;mainSubject:"국어"|"영어"|"수학";parentId:string|null};
type Schedule={id:string;weekday:number;startTime:string;endTime:string};
type Student={id:string;name:string;school:string|null;grade:string|null};
type ClassRoom={id:string;name:string;subject:string;subjectId:string|null;room:string|null;color:string;schedules:Schedule[];students:Student[]};
type Workspace={subjects:Subject[];classes:ClassRoom[]};
type AttendanceStatus="present"|"late"|"absent"|"excused";
type DayStudent=Student&{status:AttendanceStatus|null;lateMinutes:number|null;absenceReason:string|null;note:string|null};
type DayData={lessonId:string|null;examContent:string|null;lessonContent:string|null;homeworkContent:string|null;students:DayStudent[]};
const weekdays=["월","화","수","목","금","토","일"];

export function TeacherClassWorkspace({supabase,profile}:{supabase:SupabaseClient;profile:Profile}){
  const[data,setData]=useState<Workspace|null>(null);const[selectedId,setSelectedId]=useState("");const[date,setDate]=useState(today());const[day,setDay]=useState<DayData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[subjectOpen,setSubjectOpen]=useState(false);const[classOpen,setClassOpen]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError("");const{data:next,error:loadError}=await supabase.rpc("teacher_class_workspace");if(loadError||!next){setError("담당 클래스 정보를 불러오지 못했습니다. DB 최신 적용 여부를 확인해 주세요.");setLoading(false);return;}const workspace=next as Workspace;setData(workspace);setSelectedId((current)=>workspace.classes.some((item)=>item.id===current)?current:workspace.classes[0]?.id??"");setLoading(false);},[supabase]);
  useEffect(()=>{void load();},[load]);
  const selected=data?.classes.find((item)=>item.id===selectedId);
  const loadDay=useCallback(async()=>{if(!selectedId)return setDay(null);const{data:next,error:dayError}=await supabase.rpc("staff_class_day",{p_class_id:selectedId,p_date:date});if(dayError)setError("선택한 날짜의 출석부를 불러오지 못했습니다.");else setDay(next as DayData);},[date,selectedId,supabase]);
  useEffect(()=>{void loadDay();},[loadDay]);
  if(loading)return <section className="panel teacher-workspace-empty">담당 클래스를 불러오는 중이에요…</section>;
  if(error&&!data)return <section className="panel teacher-workspace-empty error">{error}</section>;
  return <><div className="teacher-home-heading"><div><p className="eyebrow">{profile.role==="admin"?"전체 클래스 운영":"나의 수업 공간"}</p><h1>{profile.display_name} 선생님 클래스</h1><p>클래스를 선택하면 출석부와 수업 내용을 한 화면에서 기록할 수 있습니다.</p></div><div className="teacher-home-actions"><button className="secondary-button" onClick={()=>setSubjectOpen(true)}>＋ 하위과목 추가</button><button className="primary" onClick={()=>setClassOpen(true)}>＋ 새 클래스</button></div></div>
    {error&&<p className="attendance-error">{error}</p>}
    <section className="teacher-class-cards">{data?.classes.length?data.classes.map((item)=><button key={item.id} className={selectedId===item.id?"active":""} onClick={()=>setSelectedId(item.id)} style={{"--class-color":item.color} as CSSProperties}><i/><span><small>{item.subject}</small><b>{item.name}</b><em>{scheduleText(item.schedules)}{item.room?` · ${item.room}`:""}</em></span><strong>{item.students.length}명</strong></button>):<div className="panel teacher-workspace-empty">아직 담당 클래스로 배정된 수업이 없습니다.<br/>관리자에게 클래스 담당 배정을 요청해 주세요.</div>}</section>
    {selected&&<ClassDayPanel supabase={supabase} classRoom={selected} date={date} onDate={setDate} day={day} onReload={loadDay}/>} 
    {subjectOpen&&<SubjectEditor supabase={supabase} subjects={data?.subjects??[]} onClose={()=>setSubjectOpen(false)} onSaved={async()=>{setSubjectOpen(false);await load();}}/>}
    {classOpen&&<ClassCreator supabase={supabase} profile={profile} subjects={data?.subjects??[]} onClose={()=>setClassOpen(false)} onSaved={async()=>{setClassOpen(false);await load();}}/>}
  </>;
}

function ClassDayPanel({supabase,classRoom,date,onDate,day,onReload}:{supabase:SupabaseClient;classRoom:ClassRoom;date:string;onDate:(value:string)=>void;day:DayData|null;onReload:()=>Promise<void>}){
  const[exam,setExam]=useState("");const[content,setContent]=useState("");const[homework,setHomework]=useState("");const[saving,setSaving]=useState("");const[error,setError]=useState("");
  useEffect(()=>{setExam(day?.examContent??"");setContent(day?.lessonContent??"");setHomework(day?.homeworkContent??"");},[day]);
  const validDay=useMemo(()=>classRoom.schedules.some((item)=>item.weekday===isoWeekday(date)),[classRoom.schedules,date]);
  const saveLog=async(event:FormEvent)=>{event.preventDefault();setSaving("log");setError("");const{error:saveError}=await supabase.rpc("staff_save_class_day",{p_class_id:classRoom.id,p_date:date,p_exam_content:exam,p_lesson_content:content,p_homework_content:homework});if(saveError)setError(saveError.message.includes("수업 시간")?saveError.message:"수업 기록을 저장하지 못했습니다.");else await onReload();setSaving("");};
  const saveAttendance=async(student:DayStudent,status:AttendanceStatus)=>{let lateMinutes:number|null=null;let absenceReason:string|null=null;if(status==="late"){const answer=window.prompt(`${student.name} 학생은 몇 분 지각했나요?`,String(student.lateMinutes??10));if(answer===null)return;lateMinutes=Number(answer);if(!Number.isFinite(lateMinutes)||lateMinutes<1)return setError("지각 시간을 1분 이상 숫자로 입력해 주세요.");}if(status==="absent"){absenceReason=window.prompt(`${student.name} 학생의 결석 사유를 입력해 주세요.`,student.absenceReason??"");if(!absenceReason?.trim())return setError("결석 사유를 입력해 주세요.");}setSaving(student.id);setError("");const{error:saveError}=await supabase.rpc("staff_save_class_attendance",{p_class_id:classRoom.id,p_date:date,p_student_id:student.id,p_status:status,p_late_minutes:lateMinutes,p_absence_reason:absenceReason,p_note:student.note});if(saveError)setError(saveError.message.includes("입력")||saveError.message.includes("수업")?saveError.message:"출결을 저장하지 못했습니다.");else await onReload();setSaving("");};
  return <section className="panel class-day-workspace"><header><div><p className="eyebrow">{classRoom.subject}</p><h2>{classRoom.name}</h2><span>{scheduleText(classRoom.schedules)}{classRoom.room?` · ${classRoom.room}`:""}</span></div><label className="class-date-picker"><span>달력 출석부</span><input type="date" value={date} onChange={(event)=>onDate(event.target.value)}/></label></header>
    {!validDay&&<p className="class-day-notice">선택한 날짜에는 정규 수업이 없습니다. 수업 요일에 해당하는 날짜를 선택해 주세요.</p>}
    <div className="class-workspace-grid"><section><h3>학생 출석부 <small>{day?.students.length??classRoom.students.length}명</small></h3><div className="class-roster">{(day?.students??classRoom.students.map((item)=>({...item,status:null,lateMinutes:null,absenceReason:null,note:null}))).map((student)=><article key={student.id}><span><i>{student.name.slice(0,1)}</i><b>{student.name}</b><small>{[student.school,student.grade].filter(Boolean).join(" · ")}</small></span><div>{([['present','출석'],['late','지각'],['absent','결석'],['excused','공결']] as [AttendanceStatus,string][]).map(([id,label])=><button key={id} disabled={!validDay||saving===student.id} className={`${id} ${student.status===id?"active":""}`} onClick={()=>void saveAttendance(student,id)}>{label}</button>)}</div>{student.status==="late"&&<em>{student.lateMinutes}분 지각</em>}{student.status==="absent"&&<em>{student.absenceReason}</em>}</article>)}</div></section>
      <form className="class-lesson-log" onSubmit={saveLog}><h3>오늘의 수업 기록</h3><label><b>시험</b><textarea value={exam} onChange={(event)=>setExam(event.target.value)} placeholder="시험명, 범위, 결과 또는 다음 시험 계획" rows={3}/></label><label><b>수업 내용</b><textarea value={content} onChange={(event)=>setContent(event.target.value)} placeholder="진도, 핵심 개념, 학생 반응과 보충할 내용" rows={6}/></label><label><b>숙제</b><textarea value={homework} onChange={(event)=>setHomework(event.target.value)} placeholder="교재, 페이지, 문제 번호와 제출일" rows={4}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={!validDay||saving==="log"}>{saving==="log"?"저장 중…":"수업 기록 저장"}</button></form></div>
  </section>;
}

function SubjectEditor({supabase,subjects,onClose,onSaved}:{supabase:SupabaseClient;subjects:Subject[];onClose:()=>void;onSaved:()=>Promise<void>}){const[main,setMain]=useState<"국어"|"영어"|"수학">("국어");const[name,setName]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState("");const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError("");const{error:saveError}=await supabase.rpc("staff_create_subject",{p_main_subject:main,p_name:name});if(saveError){setError("하위과목을 추가하지 못했습니다. 같은 이름이 있는지 확인해 주세요.");setSaving(false);}else await onSaved();};return <div className="modal-backdrop"><section className="student-modal subject-editor"><header><div><p className="eyebrow">담당 선생님 설정</p><h2>하위과목 추가</h2><span>기본 국어·영어·수학 아래에 세부 과목을 추가합니다.</span></div><button onClick={onClose}>×</button></header><form onSubmit={submit}><div className="subject-main-options">{(["국어","영어","수학"] as const).map((item)=><button type="button" className={main===item?"active":""} key={item} onClick={()=>setMain(item)}>{item}</button>)}</div><label className="editor-field"><b>하위과목 이름</b><input autoFocus value={name} onChange={(event)=>setName(event.target.value)} placeholder={main==="수학"?"예: 미적분, 기하, 확률과 통계":"예: 독서, 문학"} required/></label><div className="existing-subjects"><b>현재 {main} 과목</b><span>{subjects.filter((item)=>item.mainSubject===main).map((item)=>item.name).join(" · ")}</span></div>{error&&<p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving}>{saving?"저장 중…":"과목 추가"}</button></footer></form></section></div>}

function ClassCreator({supabase,profile,subjects,onClose,onSaved}:{supabase:SupabaseClient;profile:Profile;subjects:Subject[];onClose:()=>void;onSaved:()=>Promise<void>}){
  const first=subjects[0];const[name,setName]=useState("");const[subjectId,setSubjectId]=useState(first?.id??"");const[room,setRoom]=useState("");const[color,setColor]=useState("#922D61");const[saving,setSaving]=useState(false);const[error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();const subject=subjects.find((item)=>item.id===subjectId);if(!subject)return setError("과목을 선택해 주세요.");setSaving(true);setError("");const{data:created,error:createError}=await supabase.from("classes").insert({name:name.trim(),subject:subject.name,subject_id:subject.id,room:room.trim()||null,color}).select("id").single();if(createError||!created){setError("클래스를 만들지 못했습니다.");setSaving(false);return;}if(profile.role==="teacher"){const{error:teacherError}=await supabase.from("class_teachers").insert({class_id:created.id,profile_id:profile.id});if(teacherError){setError("클래스는 생성됐지만 담당 선생님 연결에 실패했습니다. 관리자에게 배정을 요청해 주세요.");setSaving(false);return;}}await onSaved();};
  return <div className="modal-backdrop"><section className="student-modal subject-editor"><header><div><p className="eyebrow">나의 수업 공간</p><h2>새 클래스</h2><span>학생은 한 번만 등록한 뒤 여러 클래스에 연결할 수 있습니다.</span></div><button onClick={onClose}>×</button></header><form onSubmit={submit}><div className="form-grid"><label>클래스 이름 <b>*</b><input autoFocus required value={name} onChange={(event)=>setName(event.target.value)} placeholder="예: 고2 영어 서해"/></label><label>과목 <b>*</b><select required value={subjectId} onChange={(event)=>setSubjectId(event.target.value)}>{(["국어","영어","수학"] as const).map((main)=><optgroup label={main} key={main}>{subjects.filter((item)=>item.mainSubject===main).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</optgroup>)}</select></label><label>강의실<input value={room} onChange={(event)=>setRoom(event.target.value)} placeholder="예: A 강의실"/></label><label>표시 색상<input type="color" value={color} onChange={(event)=>setColor(event.target.value)}/></label></div><p className="class-create-hint">생성 후 전과목 시간표에서 수업 요일과 시간을 배정하세요.</p>{error&&<p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving}>{saving?"생성 중…":"클래스 만들기"}</button></footer></form></section></div>;
}

function scheduleText(rows:Schedule[]){return rows.length?rows.map((row)=>`${weekdays[row.weekday-1]} ${row.startTime.slice(0,5)}–${row.endTime.slice(0,5)}`).join(" · "):"시간 미배정"}
function isoWeekday(value:string){const day=new Date(`${value}T00:00:00`).getDay();return day===0?7:day}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
