"use client";

import type * as React from "react";
import Image from "next/image";
import type { FormEvent } from "react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

type Payment = { id:string; amount:number; method:string; paidAt:string; memo:string|null };
type Charge = { id:string; studentId:string; studentName:string; classes:string; baseAmount:number; discountAmount:number; additionalAmount:number; totalAmount:number; paidAmount:number; balance:number; status:"open"|"partial"|"paid"|"waived"; memo:string|null; payments:Payment[] };
type Data = { isStaff:boolean; items:Charge[] };
type Rule = { label:string; amount:number; active:boolean };
type Enrollment = { id:string; className:string; monthlyFee:number };
type StudentRule = { id:string; name:string; enrollments:Enrollment[]; discount:Rule; additional:Rule };
type Filter = "all"|"unpaid"|"partial"|"paid"|"waived";

const statusLabel = { open:"미납", partial:"부분 납부", paid:"납부 완료", waived:"면제" };

export function TuitionBoard({ supabase }:{ supabase:SupabaseClient }) {
  const [month,setMonth] = useState(koreaMonth());
  const [data,setData] = useState<Data>({ isStaff:false,items:[] });
  const [loading,setLoading] = useState(true);
  const [message,setMessage] = useState("");
  const [search,setSearch] = useState("");
  const [filter,setFilter] = useState<Filter>("all");
  const [editing,setEditing] = useState<Charge|null>(null);
  const [paying,setPaying] = useState<Charge|null>(null);
  const [settingsOpen,setSettingsOpen] = useState(false);
  const [receipt,setReceipt] = useState<Charge|null>(null);
  const load = useCallback(async () => { setLoading(true); setMessage(""); const { data:next,error } = await supabase.rpc("tuition_board",{ p_month:`${month}-01` }); if (error) setMessage("원비 정산 내역을 불러오지 못했습니다."); else setData(next as Data); setLoading(false); },[month,supabase]);
  // Data is loaded whenever the selected settlement month changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); },[load]);
  const generate = async () => { const { data:count,error } = await supabase.rpc("staff_generate_monthly_tuition",{ p_month:`${month}-01` }); if (error) setMessage("이번 달 정산을 만들지 못했습니다."); else { await load(); setMessage(`${Number(count??0)}명의 이번 달 정산을 만들었습니다.`); } };
  const remind = async () => { const { data:count,error } = await supabase.rpc("staff_queue_tuition_reminders",{ p_month:`${month}-01` }); setMessage(error ? "미납 알림을 만들지 못했습니다." : `${Number(count??0)}명의 미납 알림을 만들었습니다.`); };
  const totals = useMemo(() => data.items.reduce((result,row) => ({ charged:result.charged+row.totalAmount, paid:result.paid+row.paidAmount, balance:result.balance+row.balance, completed:result.completed+(row.status==="paid"?1:0), unpaid:result.unpaid+(row.balance>0&&row.status!=="waived"?1:0) }),{ charged:0,paid:0,balance:0,completed:0,unpaid:0 }),[data.items]);
  const collectionRate = totals.charged ? Math.round(totals.paid/totals.charged*100) : 0;
  const visible = useMemo(() => data.items.filter(row => !search.trim() || `${row.studentName} ${row.classes} ${row.memo??""}`.toLowerCase().includes(search.trim().toLowerCase())).filter(row => filter==="all" || (filter==="unpaid" ? row.status==="open" : row.status===filter)).sort((a,b) => statusOrder(a.status)-statusOrder(b.status) || b.balance-a.balance || a.studentName.localeCompare(b.studentName,"ko")),[data.items,filter,search]);
  const printReceipt = (row:Charge) => { setReceipt(row); setTimeout(() => window.print(),100); };
  return <>
    <div className="page-heading compact tuition-page-heading"><div><p className="eyebrow">월별 청구·수납 통합 관리</p><h1>원비 정산</h1><p>{data.isStaff?"학생별 청구액과 납부 상태를 한 화면에서 확인하고 처리합니다.":"월별 원비 청구와 납부 내역을 확인합니다."}</p></div><div className="tuition-heading-actions"><div className="tuition-month-picker"><button aria-label="이전 달" onClick={()=>setMonth(current=>shiftMonth(current,-1))}>‹</button><input aria-label="정산 월" type="month" value={month} onChange={event=>setMonth(event.target.value)}/><button aria-label="다음 달" onClick={()=>setMonth(current=>shiftMonth(current,1))}>›</button></div>{data.isStaff&&<><button className="secondary-button" onClick={()=>setSettingsOpen(true)}>수강료 설정</button><button className="primary" onClick={()=>void generate()}>＋ 이번 달 정산 생성</button></>}</div></div>
    {message&&<p className={message.includes("못")?"attendance-error":"attendance-prepared"}>{message}</p>}
    <div className="tuition-summary tuition-summary-five"><article><span>총 청구액</span><b>{money(totals.charged)}</b><small>{data.items.length}명 기준</small></article><article><span>납부액</span><b>{money(totals.paid)}</b><small>수납률 {collectionRate}%</small></article><article className="outstanding"><span>미수금</span><b>{money(totals.balance)}</b><small>미납·부분 납부 합계</small></article><article><span>납부 완료</span><b>{totals.completed}명</b><small>전체 {data.items.length}명</small></article><article className={totals.unpaid?"attention":""}><span>확인 필요</span><b>{totals.unpaid}명</b><small>미납·부분 납부</small></article></div>
    <section className="panel tuition-settlement-panel"><header className="tuition-toolbar"><div className="tuition-filters" role="group" aria-label="납부 상태 필터">{([['all','전체'],['unpaid','미납'],['partial','부분 납부'],['paid','납부 완료'],['waived','면제']] as [Filter,string][]).map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{label}<small>{filterCount(data.items,value)}</small></button>)}</div><div className="tuition-toolbar-actions"><label className="tuition-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="학생·수강 검색"/></label>{data.isStaff&&<button className="secondary-button" disabled={!totals.unpaid} onClick={()=>void remind()}>미납 알림</button>}</div></header><div className="tuition-table-scroll"><div className="tuition-settlement-head"><span>학생</span><span>수강 내역</span><span>청구액</span><span>납부액</span><span>미수금</span><span>상태</span><span>최근 납부</span><span>비고</span><span/></div><div className="tuition-settlement-body">{loading?<p className="tuition-empty">원비 정산 내역을 불러오는 중이에요…</p>:!visible.length?<p className="tuition-empty">조건에 맞는 정산 내역이 없습니다.</p>:visible.map(row=>{const latest=row.payments[0];return <article key={row.id} className={`tuition-row ${row.status}`}><span className="student"><b>{row.studentName}</b><small>{row.payments.length?`${row.payments.length}회 납부`:"납부 기록 없음"}</small></span><span className="classes" title={row.classes}>{row.classes}</span><strong>{money(row.totalAmount)}<small>기본 {money(row.baseAmount)}{row.discountAmount?` · 할인 -${money(row.discountAmount)}`:""}{row.additionalAmount?` · 추가 +${money(row.additionalAmount)}`:""}</small></strong><strong>{money(row.paidAmount)}</strong><strong className={row.balance>0?"balance":""}>{money(row.balance)}</strong><span><i className={row.status}>{statusLabel[row.status]}</i></span><span>{latest?<><b>{formatDate(latest.paidAt)}</b><small>{methodLabel(latest.method)}</small></>:<small>—</small>}</span><span className="memo" title={row.memo??""}>{row.memo||"—"}</span>{data.isStaff?<div className="tuition-row-actions"><button className="quick-pay" disabled={row.status==="waived"} onClick={()=>setPaying(row)}>{row.balance>0?"정산":"추가 납부"}</button><button className="more" onClick={()=>setEditing(row)}>조정</button>{row.paidAmount>0&&<button className="more" onClick={()=>printReceipt(row)}>영수증</button>}</div>:<span/>}</article>})}</div></div></section>
    {editing&&<ChargeEditor row={editing} supabase={supabase} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load();}}/>}
    {paying&&<PaymentEditor row={paying} supabase={supabase} onClose={()=>setPaying(null)} onSaved={async()=>{setPaying(null);await load();}}/>}
    {settingsOpen&&<TuitionSettingsModal supabase={supabase} onClose={()=>setSettingsOpen(false)}/>}
    {receipt&&<Receipt row={receipt} onClose={()=>setReceipt(null)}/>}
  </>;
}

function TuitionSettingsModal({supabase,onClose}:{supabase:SupabaseClient;onClose:()=>void}) {
  const [students,setStudents]=useState<StudentRule[]>([]); const [selectedId,setSelectedId]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [search,setSearch]=useState("");
  useEffect(()=>{let active=true;void supabase.rpc("tuition_billing_settings").then(({data,error})=>{if(!active)return;const next=error?[]:(data??[]) as StudentRule[];setStudents(next);setSelectedId(next[0]?.id??"");setMessage(error?"수강료 기준을 불러오지 못했습니다.":"");setLoading(false);});return()=>{active=false};},[supabase]);
  const selected=students.find(student=>student.id===selectedId); const visible=students.filter(student=>student.name.includes(search.trim()));
  const updateEnrollment=(id:string,value:number)=>setStudents(current=>current.map(student=>student.id!==selectedId?student:{...student,enrollments:student.enrollments.map(enrollment=>enrollment.id===id?{...enrollment,monthlyFee:value}:enrollment)}));
  const updateRule=(kind:"discount"|"additional",key:keyof Rule,value:string|number|boolean)=>setStudents(current=>current.map(student=>{if(student.id!==selectedId)return student;const rule={...student[kind]};if(key==="label")rule.label=String(value);else if(key==="amount")rule.amount=Number(value);else rule.active=Boolean(value);return{...student,[kind]:rule};}));
  const save=async()=>{if(!selected)return;setSaving(true);setMessage("");const results=await Promise.all([...selected.enrollments.map(enrollment=>supabase.rpc("staff_save_enrollment_fee",{p_enrollment_id:enrollment.id,p_monthly_fee:enrollment.monthlyFee})),supabase.rpc("staff_save_tuition_recurring_rule",{p_student_id:selected.id,p_kind:"discount",p_label:selected.discount.label,p_amount:selected.discount.amount,p_active:selected.discount.active}),supabase.rpc("staff_save_tuition_recurring_rule",{p_student_id:selected.id,p_kind:"additional",p_label:selected.additional.label,p_amount:selected.additional.amount,p_active:selected.additional.active})]);setMessage(results.some(result=>result.error)?"수강료 기준을 저장하지 못했습니다.":"다음 정산 생성부터 적용할 기준을 저장했습니다.");setSaving(false);};
  const expected=selected?selected.enrollments.reduce((sum,enrollment)=>sum+enrollment.monthlyFee,0)-(selected.discount.active?selected.discount.amount:0)+(selected.additional.active?selected.additional.amount:0):0;
  return <div className="modal-backdrop tuition-settings-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="student-modal tuition-settings-modal"><header><div><p className="eyebrow">원비 정산 기준</p><h2>학생별 수강료 설정</h2><small>저장한 금액은 다음 월 정산을 생성할 때 적용됩니다.</small></div><button onClick={onClose}>×</button></header><div className="tuition-settings-layout"><aside><label className="tuition-search"><span>⌕</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="학생 검색"/></label><div>{loading?<p>불러오는 중…</p>:visible.map(student=><button key={student.id} className={student.id===selectedId?"active":""} onClick={()=>setSelectedId(student.id)}><b>{student.name}</b><small>{student.enrollments.map(enrollment=>enrollment.className).join(" · ")||"수강 없음"}</small></button>)}</div></aside><main>{!selected?<p className="tuition-empty">설정할 재원생이 없습니다.</p>:<><section><header><div><h3>{selected.name}</h3><p>수강 클래스별 월 원비</p></div><b>예상 {money(expected)}</b></header><div className="tuition-fee-list">{selected.enrollments.map(enrollment=><label key={enrollment.id}><span>{enrollment.className}</span><input type="number" min="0" value={enrollment.monthlyFee} onChange={event=>updateEnrollment(enrollment.id,Number(event.target.value))}/><em>원</em></label>)}</div></section><section><header><div><h3>매월 반복 조정</h3><p>할인과 추가 비용을 자동 반영합니다.</p></div></header><div className="tuition-rule-list">{(["discount","additional"] as const).map(kind=><div key={kind}><label><input type="checkbox" checked={selected[kind].active} onChange={event=>updateRule(kind,"active",event.target.checked)}/><span>{kind==="discount"?"할인":"추가 비용"}</span></label><input value={selected[kind].label} onChange={event=>updateRule(kind,"label",event.target.value)} placeholder={kind==="discount"?"형제 할인":"교재비·차량비"}/><input type="number" min="0" value={selected[kind].amount} onChange={event=>updateRule(kind,"amount",Number(event.target.value))}/><em>원</em></div>)}</div></section>{message&&<p className={message.includes("못")?"form-error":"attendance-prepared"}>{message}</p>}<footer><button className="secondary-button" onClick={onClose}>닫기</button><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?"저장 중…":"수강료 기준 저장"}</button></footer></>}</main></div></section></div>;
}

function ChargeEditor({row,supabase,onClose,onSaved}:{row:Charge;supabase:SupabaseClient;onClose:()=>void;onSaved:()=>Promise<void>}){const[base,setBase]=useState(row.baseAmount);const[discount,setDiscount]=useState(row.discountAmount);const[additional,setAdditional]=useState(row.additionalAmount);const[memo,setMemo]=useState(row.memo??"");const[waived,setWaived]=useState(row.status==="waived");const[saving,setSaving]=useState(false);const[error,setError]=useState("");const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);const{error:saveError}=await supabase.rpc("staff_save_tuition_charge",{p_charge_id:row.id,p_base_amount:base,p_discount_amount:discount,p_additional_amount:additional,p_memo:memo||null,p_waived:waived});if(saveError){setError("금액을 저장하지 못했습니다.");setSaving(false);}else await onSaved();};return <TuitionModal title={`${row.studentName} 청구 조정`} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><MoneyInput label="기본 수강료" value={base} setValue={setBase}/><MoneyInput label="할인" value={discount} setValue={setDiscount}/><MoneyInput label="추가 비용" value={additional} setValue={setAdditional}/><label>청구 합계<input disabled value={money(base-discount+additional)}/></label><label className="full">비고<input value={memo} onChange={event=>setMemo(event.target.value)} placeholder="형제 할인, 교재비 등"/></label><label className="full account-active-check"><input type="checkbox" checked={waived} onChange={event=>setWaived(event.target.checked)}/><span><b>이번 달 원비 면제</b><small>청구 기록은 유지하고 미납 집계에서 제외합니다.</small></span></label></div>{error&&<p className="form-error">{error}</p>}<Actions saving={saving} onClose={onClose} label="청구 저장"/></form></TuitionModal>}
function PaymentEditor({row,supabase,onClose,onSaved}:{row:Charge;supabase:SupabaseClient;onClose:()=>void;onSaved:()=>Promise<void>}){const[amount,setAmount]=useState(row.balance||row.totalAmount);const[method,setMethod]=useState("transfer");const[paidAt,setPaidAt]=useState(koreaDateTime());const[memo,setMemo]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState("");const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);const{error:saveError}=await supabase.rpc("staff_record_tuition_payment",{p_charge_id:row.id,p_amount:amount,p_method:method,p_paid_at:`${paidAt}:00+09:00`,p_memo:memo||null});if(saveError){setError("납부 내역을 저장하지 못했습니다.");setSaving(false);}else await onSaved();};return <TuitionModal title={`${row.studentName} 납부 등록`} onClose={onClose}><form onSubmit={submit}><div className="payment-quick-total"><span>현재 미수금</span><b>{money(row.balance)}</b><button type="button" onClick={()=>setAmount(row.balance)}>전액 입력</button></div><div className="form-grid"><MoneyInput label="납부 금액" value={amount} setValue={setAmount}/><label>결제 방법<select value={method} onChange={event=>setMethod(event.target.value)}><option value="transfer">계좌이체</option><option value="card">카드</option><option value="cash">현금</option><option value="other">기타</option></select></label><label>납부 일시<input type="datetime-local" required value={paidAt} onChange={event=>setPaidAt(event.target.value)}/></label><label>저장 후 미수금<input disabled value={money(Math.max(row.balance-amount,0))}/></label><label className="full">비고<input value={memo} onChange={event=>setMemo(event.target.value)} placeholder="입금자명, 카드 승인번호 등"/></label></div>{error&&<p className="form-error">{error}</p>}<Actions saving={saving} onClose={onClose} label="납부 저장"/></form></TuitionModal>}
function Receipt({row,onClose}:{row:Charge;onClose:()=>void}){return <div className="print-receipt"><Image src="/hansalmae-logo.png" width={58} height={58} alt="한살매"/><h1>원비 납부 영수증</h1><p><b>학생</b>{row.studentName}</p><p><b>수강</b>{row.classes}</p><p><b>청구 금액</b>{money(row.totalAmount)}</p><p><b>납부 금액</b>{money(row.paidAmount)}</p><p><b>미수금</b>{money(row.balance)}</p><hr/><small>한살매 입시전문학원 · 전산 발행 영수증</small><button onClick={onClose}>닫기</button></div>}
function TuitionModal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="student-modal"><header><div><p className="eyebrow">원비 정산</p><h2>{title}</h2></div><button onClick={onClose}>×</button></header>{children}</section></div>}
function MoneyInput({label,value,setValue}:{label:string;value:number;setValue:(value:number)=>void}){return <label>{label}<input type="number" min="0" required value={value} onChange={event=>setValue(Number(event.target.value))}/></label>}
function Actions({saving,onClose,label}:{saving:boolean;onClose:()=>void;label:string}){return <footer><button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary" disabled={saving}>{saving?"저장 중…":label}</button></footer>}
function filterCount(items:Charge[],filter:Filter){if(filter==="all")return items.length;if(filter==="unpaid")return items.filter(row=>row.status==="open").length;return items.filter(row=>row.status===filter).length}
function statusOrder(status:Charge["status"]){return({open:0,partial:1,paid:2,waived:3})[status]}
function money(value:number){return `${new Intl.NumberFormat("ko-KR").format(value)}원`}
function methodLabel(value:string){return({cash:"현금",transfer:"계좌이체",card:"카드",other:"기타"} as Record<string,string>)[value]??value}
function koreaMonth(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7)}
function koreaDateTime(){return new Date(Date.now()+9*3600000).toISOString().slice(0,16)}
function formatDate(value:string){return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",month:"numeric",day:"numeric"}).format(new Date(value))}
function shiftMonth(value:string,offset:number){const [year,month]=value.split("-").map(Number);const date=new Date(Date.UTC(year,month-1+offset,1));return `${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,"0")}`}
