"use client";

import { useEffect, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Profile } from "./supabase";

type WordSet = { id:string; name:string; slug:string; sort_order:number };
type Word = { id:number; day:number; word:string; meaning:string; example:string; translation:string; example_answer:string; sort_order:number };
type QuestionKind = "eng_to_kor" | "kor_to_eng" | "example";
type Question = Word & { kind:QuestionKind; prompt:string; answer:string };
type History = { id:string; title:string; word_set_name:string; start_day:number; end_day:number; question_count:number; created_at:string };

const MAX_QUESTIONS=200;
const shuffle=<T,>(values:T[])=>{const result=[...values];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;};
const clean=(value:string)=>value.trim().replace(/\s+/g," ");
const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[character]??character));

export function VocabularyTestGenerator({supabase,profile}:{supabase:SupabaseClient;profile:Profile}){
  const[sets,setSets]=useState<WordSet[]>([]);const[setId,setSetId]=useState("");const[startDay,setStartDay]=useState(1);const[endDay,setEndDay]=useState(1);
  const[engToKor,setEngToKor]=useState(15);const[korToEng,setKorToEng]=useState(15);const[exampleCount,setExampleCount]=useState(10);
  const[teacherName,setTeacherName]=useState(profile.display_name);const[history,setHistory]=useState<History[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  const[preview,setPreview]=useState<Question[]|null>(null);const[title,setTitle]=useState("");
  const total=engToKor+korToEng+exampleCount;const selectedSet=sets.find(item=>item.id===setId);

  useEffect(()=>{let active=true;void Promise.all([
    supabase.from("vocabulary_word_sets").select("id,name,slug,sort_order").eq("enabled",true).order("sort_order"),
    supabase.from("vocabulary_test_history").select("id,title,word_set_name,start_day,end_day,question_count,created_at").order("created_at",{ascending:false}).limit(12),
  ]).then(([setResult,historyResult])=>{if(!active)return;if(setResult.error){setMessage("단어 DB를 불러오지 못했습니다.");return;}const next=(setResult.data??[]) as WordSet[];setSets(next);setSetId(current=>current||next[0]?.id||"");setHistory((historyResult.data??[]) as History[]);});return()=>{active=false};},[supabase]);

  const validate=()=>{if(!setId)return "단어 DB를 선택해 주세요.";if(startDay<1||endDay<startDay)return "Day 범위를 확인해 주세요.";if(total<1||total>MAX_QUESTIONS)return `총 문제 수는 1~${MAX_QUESTIONS}개여야 합니다.`;return "";};
  const create=async()=>{const invalid=validate();if(invalid){setMessage(invalid);return;}setBusy(true);setMessage("");const{data,error}=await supabase.rpc("staff_get_vocabulary_words",{p_word_set_id:setId,p_start_day:startDay,p_end_day:endDay});if(error){setMessage("단어를 불러오지 못했습니다.");setBusy(false);return;}const words=(data??[]) as Word[];if(words.length<total){setMessage(`선택 범위에는 ${words.length}개 단어만 있습니다. 문제 수를 줄여 주세요.`);setBusy(false);return;}const picked=shuffle(words).slice(0,total);let cursor=0;const questions:Question[]=[];
    const add=(count:number,kind:QuestionKind)=>{picked.slice(cursor,cursor+count).forEach(word=>questions.push(makeQuestion(word,kind,words)));cursor+=count;};add(engToKor,"eng_to_kor");add(korToEng,"kor_to_eng");add(exampleCount,"example");const mixed=shuffle(questions);const dayText=startDay===endDay?`D${startDay}`:`D${startDay}-D${endDay}`;const nextTitle=`${selectedSet?.name??"영단어"} ${dayText}`;setTitle(nextTitle);setPreview(mixed);
    const{data:saved}=await supabase.from("vocabulary_test_history").insert({title:nextTitle,word_set_id:setId,word_set_name:selectedSet?.name??"영단어",start_day:startDay,end_day:endDay,question_count:total,eng_to_kor_count:engToKor,kor_to_eng_count:korToEng,example_count:exampleCount,created_by:profile.id,created_by_name:profile.display_name}).select("id,title,word_set_name,start_day,end_day,question_count,created_at").single();if(saved)setHistory(current=>[saved as History,...current].slice(0,12));setBusy(false);};

  const downloadDocx=async(answer:boolean)=>{if(!preview)return;setBusy(true);setMessage("");try{const blob=await buildDocx(title,teacherName,preview,answer);downloadBlob(blob,`${title} ${answer?"답지":"시험지"}.docx`);setMessage(`${answer?"답지":"시험지"} 수정용 파일을 내려받았습니다.`);}catch{setMessage("문서 파일을 만들지 못했습니다.");}finally{setBusy(false);}};
  const printPdf=(answer:boolean)=>{if(!preview)return;const popup=window.open("","_blank","noopener,noreferrer");if(!popup){setMessage("팝업이 차단되었습니다. 이 사이트의 팝업을 허용해 주세요.");return;}popup.document.write(buildPrintHtml(title,teacherName,preview,answer));popup.document.close();};
  const importExcel=async(file:File)=>{if(profile.role!=="admin")return;setBusy(true);setMessage("엑셀에서 단어를 읽는 중입니다…");try{const{default:readXlsxFile}=await import("read-excel-file");const mappings=[{sheet:"중등단어DB",slug:"middle",name:"중등 영단어",order:1},{sheet:"고등단어DB",slug:"high",name:"고등 영단어",order:2},{sheet:"수능단어DB",slug:"csat",name:"수능 영단어",order:3}];for(const mapping of mappings){const rows=(await readXlsxFile(file,{sheet:mapping.sheet})).slice(1).filter(row=>Number(row[0])>0&&clean(String(row[1]??"")));const{data:setRow,error:setError}=await supabase.from("vocabulary_word_sets").upsert({name:mapping.name,slug:mapping.slug,sort_order:mapping.order,enabled:true},{onConflict:"slug"}).select("id").single();if(setError||!setRow)throw setError??new Error("DB 생성 실패");const{error:deleteError}=await supabase.from("vocabulary_words").delete().eq("word_set_id",setRow.id);if(deleteError)throw deleteError;for(let i=0;i<rows.length;i+=400){const payload=rows.slice(i,i+400).map((row,index)=>({word_set_id:setRow.id,day:Number(row[0]),word:clean(String(row[1])),meaning:clean(String(row[2])),example:String(row[3]??"").trim(),translation:String(row[4]??"").trim(),example_answer:clean(String(row[5]??""))||clean(String(row[1])),sort_order:i+index+1}));const{error:insertError}=await supabase.from("vocabulary_words").insert(payload);if(insertError)throw insertError;}}setMessage("중등·고등·수능 단어 DB를 최신 엑셀 내용으로 교체했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"엑셀 DB를 반영하지 못했습니다.");}finally{setBusy(false);}};

  return <div className="vocab-page"><header className="vocab-heading"><div><p className="eyebrow">영어 선생님 도구</p><h1>단어 시험 출제</h1><p>단어를 빠르게 뽑아 형식이 고정된 시험지·답지를 만듭니다. 파일 본문은 Supabase에 저장하지 않습니다.</p></div>{profile.role==="admin"&&<label className="vocab-upload">엑셀 DB 업데이트<input type="file" accept=".xlsx,.xls" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void importExcel(file);event.currentTarget.value="";}}/></label>}</header>
    <div className="vocab-layout"><section className="panel vocab-builder"><div className="vocab-section-title"><span>1</span><div><h2>출제 범위</h2><p>교재와 Day 범위를 선택하세요.</p></div></div><div className="vocab-form-grid"><label>단어 DB<select value={setId} onChange={e=>setSetId(e.target.value)}>{sets.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>시작 Day<input type="number" min="1" value={startDay} onChange={e=>setStartDay(Number(e.target.value))}/></label><label>끝 Day<input type="number" min="1" value={endDay} onChange={e=>setEndDay(Number(e.target.value))}/></label><label>담당 선생님<input value={teacherName} onChange={e=>setTeacherName(e.target.value)} spellCheck={false}/></label></div>
      <div className="vocab-section-title"><span>2</span><div><h2>문제 구성</h2><p>유형별 개수를 정하면 무작위로 섞어 출제합니다.</p></div></div><div className="vocab-counts"><label><span>영어 → 뜻</span><input type="number" min="0" value={engToKor} onChange={e=>setEngToKor(Number(e.target.value))}/></label><label><span>뜻 → 영어</span><input type="number" min="0" value={korToEng} onChange={e=>setKorToEng(Number(e.target.value))}/></label><label><span>예문 빈칸</span><input type="number" min="0" value={exampleCount} onChange={e=>setExampleCount(Number(e.target.value))}/></label><strong><small>총 문제</small>{total}<em>/ {MAX_QUESTIONS}</em></strong></div>{message&&<p className="vocab-message">{message}</p>}<button className="primary vocab-create" disabled={busy||!sets.length} onClick={()=>void create()}>{busy?"처리 중…":"시험지 미리보기 만들기"}</button></section>
      <aside className="panel vocab-history"><header><div><p className="eyebrow">최근 생성</p><h2>출제 이력</h2></div><span>90일 · 최대 300건</span></header>{history.length?history.map(item=><article key={item.id}><b>{item.title}</b><small>{item.question_count}문제 · {new Date(item.created_at).toLocaleString("ko-KR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}</small></article>):<p className="vocab-empty">아직 생성 이력이 없습니다.</p>}</aside></div>
    {preview&&<section className="panel vocab-preview"><header><div><p className="eyebrow">생성 완료</p><h2>{title}</h2><span>{preview.length}문제 · A4 2열 자동 배치</span></div><div><button onClick={()=>printPdf(false)}>시험지 PDF</button><button onClick={()=>void downloadDocx(false)}>시험지 수정용</button><button onClick={()=>printPdf(true)}>답지 PDF</button><button className="primary" onClick={()=>void downloadDocx(true)}>답지 수정용</button></div></header><div className="vocab-preview-sheet">{preview.slice(0,20).map((question,index)=><p key={`${question.id}-${index}`}><b>{index+1}.</b><span>{question.prompt}</span></p>)}{preview.length>20&&<em>외 {preview.length-20}문제 · 내려받은 문서에서 전체 내용을 확인하세요.</em>}</div></section>}
  </div>;
}

function makeQuestion(word:Word,kind:QuestionKind,all:Word[]):Question{if(kind==="eng_to_kor")return{...word,kind,prompt:word.word,answer:word.meaning};if(kind==="kor_to_eng")return{...word,kind,prompt:word.meaning,answer:word.word};const answer=clean(word.example_answer)||word.word;const source=word.example||`${word.word} : ${word.meaning}`;const blank=source.replace(new RegExp(answer.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"),"__________");const distractors=shuffle(all.filter(item=>item.id!==word.id).map(item=>clean(item.example_answer)||item.word)).slice(0,3);const choices=shuffle([answer,...distractors]);return{...word,kind,prompt:`${blank}\n${choices.map((item,index)=>`${index+1}) ${item}`).join("   ")}`,answer:`${answer} · ${word.meaning}`};}
function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

async function buildDocx(title:string,teacher:string,questions:Question[],answer:boolean){const docx=await import("docx");const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,BorderStyle,AlignmentType,PageBreak}=docx;const none={style:BorderStyle.NONE,size:0,color:"FFFFFF"};const line={style:BorderStyle.SINGLE,size:10,color:"222222"};const para=(text:string,bold=false,size=20)=>new Paragraph({spacing:{after:50,line:250},children:[new TextRun({text,bold,size,font:"Arial"})]});const pages:InstanceType<typeof Table>[]=[];const half=Math.ceil(questions.length/2);for(let page=0;page<Math.ceil(half/38);page++){const left=questions.slice(page*38,Math.min(half,page*38+38));const right=questions.slice(half+page*38,half+page*38+38);const rows=Array.from({length:Math.max(left.length,right.length)},(_,index)=>new TableRow({children:[left[index],right[index]].map((question,column)=>new TableCell({width:{size:column===0?4800:4560,type:WidthType.DXA},borders:{top:none,bottom:none,left:none,right:none},margins:{top:30,bottom:30,left:80,right:80},children:question?[para(`${(column===0?page*38:half+page*38)+index+1}. ${answer?question.answer:question.prompt}`,true,20)]:[para("")] }))}));pages.push(new Table({width:{size:9360,type:WidthType.DXA},columnWidths:[4800,4560],borders:{top:none,bottom:none,left:none,right:none,insideHorizontal:none,insideVertical:none},rows}));}
  const children:(InstanceType<typeof Paragraph>|InstanceType<typeof Table>)[]=[new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:120},children:[new TextRun({text:answer?`${title} 답지`:title,bold:true,size:28,font:"Arial"})]})];if(!answer)children.push(new Table({width:{size:9360,type:WidthType.DXA},columnWidths:[3100,3100,3160],borders:{top:line,bottom:line,left:line,right:line,insideHorizontal:line,insideVertical:line},rows:[new TableRow({children:[`이름:`,`점수:        / ${questions.length}`,`담당: ${clean(teacher)} 선생님`].map(text=>new TableCell({children:[para(text,true,19)]}))})]}));children.push(new Paragraph({spacing:{after:60},children:[]}));pages.forEach((table,index)=>{children.push(table);if(index<pages.length-1)children.push(new Paragraph({children:[new PageBreak()]}));});const document=new Document({styles:{default:{document:{run:{font:"Arial",size:20},paragraph:{spacing:{after:50,line:250}}}}},sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:500,right:560,bottom:500,left:560}}},children}]});return Packer.toBlob(document);}

function buildPrintHtml(title:string,teacher:string,questions:Question[],answer:boolean){const half=Math.ceil(questions.length/2);const pageCount=Math.ceil(half/38);const pages=Array.from({length:pageCount},(_,page)=>{const left=questions.slice(page*38,Math.min(half,page*38+38));const right=questions.slice(half+page*38,half+page*38+38);const column=(items:Question[],offset:number)=>`<div class="column">${items.map((item,index)=>`<p><b>${offset+index+1}.</b><span>${escapeHtml(answer?item.answer:item.prompt).replace(/\n/g,"<br>")}</span></p>`).join("")}</div>`;return`<section class="page">${page===0?`<h1>${escapeHtml(answer?`${title} 답지`:title)}</h1>${answer?"":`<div class="info"><span>이름:</span><span>점수: &nbsp;&nbsp;&nbsp; / ${questions.length}</span><span>담당: ${escapeHtml(clean(teacher))} 선생님</span></div>`}`:""}<div class="columns">${column(left,page*38)}${column(right,half+page*38)}</div></section>`;}).join("");return`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>@page{size:A4;margin:9mm 10mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,'Noto Sans KR','Malgun Gothic',sans-serif;color:#111}.page{width:190mm;min-height:277mm;page-break-after:always;padding-top:2mm}.page:last-child{page-break-after:auto}h1{text-align:center;font-size:14pt;margin:0 0 3mm}.info{border:1px solid #222;display:grid;grid-template-columns:repeat(3,1fr);font-size:9.5pt;font-weight:700;padding:2.2mm 3mm;margin-bottom:3mm}.columns{display:grid;grid-template-columns:1fr 1fr;gap:7mm}.column p{display:grid;grid-template-columns:8mm 1fr;gap:1mm;margin:0 0 1.5mm;font-size:10pt;line-height:1.25;font-weight:700}.column b{text-align:right}.column span{white-space:pre-wrap}@media screen{body{background:#eee}.page{background:white;margin:12px auto;padding:9mm 10mm;box-shadow:0 2px 12px #aaa}}@media print{.page{width:auto;min-height:auto;padding:0}}</style></head><body>${pages}<script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`;}
