import {test} from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import fs from 'node:fs';
const load=async file=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(fs.readFileSync(file,'utf8'),{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022})).toString('base64'));
const {combineCourses,updateMerge,releaseMerge}=await load('app/planner/merge.ts');const {shared,validate}=await load('app/planner/engine.ts');
const make=(id,students)=>({id,name:id,subject:'영어',room:'',teachers:['t'],students:students.map(id=>({id,name:id,grade:'고2'})),enabled:true,high:true,count:3,duration:120});
const a=make('a',['s1','s2']),b=make('b',['s2','s3']),c=make('c',['s4']);const settings={id:'merge-test',name:'고2 영어 합반',teacherId:'t',count:3,duration:120,room:'1'};
test('merged students are deduplicated and conflict with other subjects',()=>{const m=combineCourses([a,b],settings);assert.equal(m.students.length,3);assert.ok(shared(m,{...c,subject:'수학',teachers:['other'],students:[{id:'s3'}]}));assert.equal(m.count,3);assert.equal(m.high,true);});
test('replace, edit, serialize and release preserve original classes',()=>{let courses=updateMerge([a,b,c],combineCourses([a,b],settings));assert.equal(courses.length,2);assert.ok(!courses.some(v=>v.id==='a'));courses=JSON.parse(JSON.stringify(courses));const restored=releaseMerge(courses,'merge-test');assert.deepEqual(restored.find(v=>v.id==='a'),a);assert.deepEqual(restored.find(v=>v.id==='b'),b);const changed=updateMerge(courses,combineCourses([a,c],settings),'merge-test');assert.deepEqual(changed.find(v=>v.id==='b'),b);assert.equal(changed.length,2);});
test('reject mixed subjects, duplicate classes and nested merges',()=>{assert.throws(()=>combineCourses([a,{...b,subject:'수학'}],settings));assert.throws(()=>combineCourses([a,a],settings));assert.throws(()=>combineCourses([a,combineCourses([b,c],settings)],settings));});
test('solver validation respects selected merge teacher days',()=>{const m=combineCourses([a,b],{...settings,count:1});const config={courses:[m],teachers:[{id:'t',name:'t',days:[1]}],starts:['18:00','18:00','','','','',''],objective:'student'};assert.equal(validate(config,[{classId:m.id,day:1,start:1080,end:1200}]).length,0);assert.ok(validate(config,[{classId:m.id,day:2,start:1080,end:1200}]).length);});
