import {readFileSync} from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import test from 'node:test';import assert from 'node:assert/strict';
const source=readFileSync(new URL('../../app/alimtalk-send-center.tsx',import.meta.url),'utf8');
function harness(){const pending=[],effects=[],state={history:[{id:'saved'}]};const ctx={useCallback:f=>f,useEffect:f=>effects.push(f),historyVersion:{current:0},readyVersion:{current:0},period:{start:'2026-09-11',end:'2026-09-11'},anchor:'2026-09-11',type:'daily',sending:false,Set,supabase:{rpc:(name,args)=>new Promise((resolve,reject)=>pending.push({name,args,resolve,reject}))}};
for(const name of ['History','HistoryError','Loading','Message','ReadyStudents','Checked','StudentId','Type','Anchor','Confirming','IncompletePrompt','ResendTarget','ListMode'])ctx['set'+name]=v=>state[name[0].toLowerCase()+name.slice(1)]=v;
vm.createContext(ctx);const loaders=source.slice(source.indexOf('  const loadHistory=useCallback'),source.indexOf('  async function sendRow'));const reset=source.slice(source.indexOf('  function resetPeriod'),source.indexOf('  function toggle'));vm.runInContext(ts.transpile(loaders+reset+';globalThis.historyLoad=loadHistory;globalThis.readyLoad=loadReady;globalThis.reset=resetPeriod;',{target:ts.ScriptTarget.ES2022}),ctx);return {ctx,state,pending,effects};}
const rows=id=>({data:[{studentId:id,complete:true,recipient:{available:true}}],error:null});
test('history errors retain existing rows and show an independent error',async()=>{const h=harness();const p=h.ctx.historyLoad();h.pending[0].resolve({data:null,error:{message:'offline'}});await p;assert.equal(h.state.history[0].id,'saved');assert.ok(h.state.historyError)});
test('valid empty history replaces rows while recovery clears error',async()=>{const h=harness();h.state.historyError='old';const p=h.ctx.historyLoad();h.pending[0].resolve({data:[],error:null});await p;assert.equal(h.state.history.length,0);assert.equal(h.state.historyError,'')});
test('late history error cannot overwrite a newer successful refresh',async()=>{const h=harness();const a=h.ctx.historyLoad(),b=h.ctx.historyLoad();h.pending[1].resolve({data:[{id:'new'}]});await b;h.pending[0].resolve({error:{message:'old'}});await a;assert.equal(h.state.history[0].id,'new');assert.equal(h.state.historyError,'')});
test('old date response cannot replace current date rows',async()=>{const h=harness();const a=h.ctx.readyLoad();h.ctx.reset(undefined,'2026-09-12');h.ctx.period={start:'2026-09-12',end:'2026-09-12'};const b=h.ctx.readyLoad();h.pending[1].resolve(rows('new'));await b;h.pending[0].resolve(rows('old'));await a;assert.equal(h.state.readyStudents[0].studentId,'new');assert.equal(h.state.loading,false)});
test('date change immediately invalidates requests before next effect',async()=>{const h=harness();const a=h.ctx.readyLoad();h.ctx.reset(undefined,'2026-09-12');h.pending[0].resolve(rows('old'));await a;assert.equal(h.state.readyStudents.length,0);assert.equal(h.state.loading,true)});
test('effect cleanup prevents both loaders updating after unmount',async()=>{const h=harness();const cleanup=h.effects.map(f=>f());cleanup.forEach(f=>f());h.pending.forEach(p=>p.resolve(rows('late')));await new Promise(r=>setImmediate(r));assert.equal(h.state.history[0].id,'saved');assert.equal(h.state.readyStudents,undefined)});
test('network exceptions retain history and terminate ready loading',async()=>{const h=harness();const a=h.ctx.historyLoad(),b=h.ctx.readyLoad();h.pending.forEach(p=>p.reject(Error('offline')));await Promise.all([a,b]);assert.equal(h.state.history[0].id,'saved');assert.ok(h.state.historyError);assert.equal(h.state.loading,false);assert.ok(h.state.message)});
test('same period click does not clear rows or strand loading',()=>{const h=harness();h.ctx.reset('daily');assert.equal(h.state.loading,undefined);assert.equal(h.ctx.readyVersion.current,0)});
test('period cannot change during a send',()=>{const h=harness();h.ctx.sending=true;h.ctx.reset(undefined,'2026-09-12');assert.equal(h.state.anchor,undefined)});
