import {readFileSync} from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import test from 'node:test';import assert from 'node:assert/strict';
const source=readFileSync(new URL('../../app/family-learning-report-feed.tsx',import.meta.url),'utf8');
function harness(){const state={items:['existing']},pending=[];const ctx={isTransientFamilyError:e=>/offline|fetch/i.test(e.message),clearFamilyPageCache:()=>{state.cacheCleared=true},setSelected:v=>state.selected=v,setCalendarSchedule:()=>{},setCanComment:()=>{},setUnavailable:v=>state.unavailable=v,loading:false,useCallback:f=>f,studentId:'a',refreshInFlight:{current:false},feedGeneration:{current:1},refreshCompleteTimer:{current:null},supabase:{rpc:()=>new Promise((resolve,reject)=>pending.push({resolve,reject}))},window:{clearTimeout:()=>{},setTimeout:(f,ms)=>{if(ms!==900)f();return 1;}},setRefreshError:v=>state.error=v,setRefreshing:v=>state.refreshing=v,setRefreshComplete:v=>state.complete=v,setItems:v=>state.items=v,setCorrections:()=>{},setReads:()=>{},setReadTracking:()=>{},setCorrectionReads:()=>{},normalizeCorrectionReport:x=>x};const a=source.indexOf('  const refreshFeed = useCallback('),b=source.indexOf('  useEffect(',a);vm.createContext(ctx);vm.runInContext(ts.transpile(source.slice(a,b)+';globalThis.run=refreshFeed;',{target:ts.ScriptTarget.ES2022}),ctx);return {ctx,state,pending};}
test('returned errors retain records, report failure and release refresh lock',async()=>{const h=harness(),run=h.ctx.run();h.pending.forEach(p=>p.resolve({data:null,error:{message:'offline'}}));await run;assert.equal(h.state.complete,false);assert.deepEqual(h.state.items,['existing']);assert.ok(h.state.error);assert.equal(h.state.refreshing,false);assert.equal(h.ctx.refreshInFlight.current,false);});
test('rejected request releases loading and allows successful retry',async()=>{const h=harness(),run=h.ctx.run();h.pending.forEach(p=>p.reject(Error('offline')));await run;assert.equal(h.state.refreshing,false);const count=h.pending.length,retry=h.ctx.run();h.pending.slice(count).forEach(p=>p.resolve({data:[],error:null}));await retry;assert.equal(h.state.complete,true);assert.equal(h.state.error,'');});
test('one failed source prevents partial refresh from reporting success',async()=>{const h=harness(),run=h.ctx.run();h.pending.forEach((p,i)=>p.resolve({data:[],error:i===2?{message:'Failed to fetch'}:null}));await run;assert.deepEqual(h.state.items,['existing']);assert.equal(h.state.complete,false);});
test('duplicate gestures issue only one request batch',async()=>{const h=harness(),run=h.ctx.run();await h.ctx.run();assert.equal(h.pending.length,4);h.pending.forEach(p=>p.resolve({data:[],error:null}));await run;});
test('responses after child/month change or unmount cannot replace records',async()=>{const h=harness(),run=h.ctx.run();h.ctx.feedGeneration.current++;h.pending.forEach(p=>p.resolve({data:[],error:null}));await run;assert.deepEqual(h.state.items,['existing']);assert.equal(h.state.complete,false);});
test('initial load blocks pull refresh',async()=>{const h=harness();h.ctx.loading=true;await h.ctx.run();assert.equal(h.pending.length,0);});
test('access denial removes existing records, closes detail and clears page cache',async()=>{const h=harness(),run=h.ctx.run();h.pending.forEach(p=>p.resolve({data:null,error:{code:'P0001',message:'연결된 자녀만 확인할 수 있습니다.'}}));await run;assert.equal(h.state.items.length,0);assert.equal(h.state.selected,null);assert.equal(h.state.cacheCleared,true);assert.equal(h.state.unavailable,true);assert.equal(h.state.refreshing,false);assert.equal(h.state.complete,false);});
