import {readFileSync} from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import test from 'node:test';import assert from 'node:assert/strict';
const source=readFileSync(new URL('../../app/use-family-previous-homework.ts',import.meta.url),'utf8');const tick=()=>new Promise(r=>setImmediate(r));
function harness(){let index=0,effect,cleanup;const states=[],pending=[],exports={};const react={useState:initial=>{const i=index++;if(!(i in states))states[i]=initial;return [states[i],v=>states[i]=typeof v==='function'?v(states[i]):v]},useEffect:f=>effect=f};
 vm.runInNewContext(ts.transpile(source,{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}),{exports,require:()=>react});const client={rpc:(name,args)=>new Promise((resolve,reject)=>pending.push({name,args,resolve,reject}))};
 return {states,pending,render(record='a'){index=0;const result=exports.useFamilyPreviousHomework(client,'student',record,'lesson');cleanup?.();cleanup=effect();return result},cleanup:()=>cleanup?.()};
}
test('homework lookup requests record identity without a date cap',async()=>{const h=harness();h.render();await tick();assert.equal(h.pending[0].name,'family_previous_homework');assert.equal(h.pending[0].args.p_record_id,'a');assert.equal(h.pending[0].args.p_start_date,undefined);h.pending[0].resolve({data:'90일 전 숙제',error:null});await tick();assert.equal(h.states[1].value,'90일 전 숙제');});
test('old record response and unmounted requests cannot replace the current homework',async()=>{const h=harness();h.render('a');await tick();h.render('b');await tick();h.pending[1].resolve({data:'B',error:null});await tick();h.pending[0].resolve({data:'A',error:null});await tick();assert.equal(h.states[1].value,'B');h.cleanup();});
test('failed homework read displays an error and retry can recover',async()=>{const h=harness();let view=h.render();await tick();h.pending[0].resolve({data:null,error:{message:'denied'}});await tick();assert.equal(h.states[1].value,'');assert.ok(h.states[1].error);view.retry();h.render();await tick();h.pending[1].resolve({data:'recovered',error:null});await tick();assert.equal(h.states[1].value,'recovered');assert.equal(h.states[1].error,'');});
