import {readFileSync} from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import test from 'node:test';import assert from 'node:assert/strict';
const exports={};vm.runInNewContext(ts.transpile(readFileSync(new URL('../../app/family-detail-query.ts',import.meta.url),'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}),{exports});
const feed=readFileSync(new URL('../../app/family-learning-report-feed.tsx',import.meta.url),'utf8');
function open(items,corrections,detailTarget){const start=feed.indexOf('  useEffect(() => {\n    if (loading || !detailTarget)'),end=feed.indexOf('  useEffect(',start+12);const ctx={loading:false,items,corrections,detailTarget,useEffect:f=>f(),setSelected:v=>ctx.selected=v,confirmRead:()=>{},confirmCorrectionRead:()=>{}};vm.runInNewContext(ts.transpile(feed.slice(start,end),{target:ts.ScriptTarget.ES2022}),ctx);return ctx.selected;}
test('detail uses selected date with no record cap and opens lesson 67 and correction 75',async()=>{
 const lessons=Array.from({length:67},(_,i)=>({lessonId:`lesson-${i}`,lessonDate:'2026-09-01',startsAt:'2026-09-01T12:00:00+09:00'}));const corrections=Array.from({length:75},(_,i)=>({id:`correction-${i}`,correctionDate:'2026-09-01',startTime:'12:00'}));let calls=0;
 const client={rpc:async(name,args)=>{calls++;assert.equal(name,'family_summary_snapshot');assert.equal(args.p_student_id,'a');assert.equal(args.p_start_date,'2026-08-01');assert.equal(args.p_end_date,'2026-09-01');assert.equal(args.p_limit,undefined);return {data:{lessons,corrections},error:null};}};
 const [regular,correction]=await exports.loadFamilyDetailReports(client,'a','2026-09-01');assert.equal(calls,1);
 assert.equal(open(regular.data,correction.data,{lessonId:'lesson-66'}).report.lessonId,'lesson-66');assert.equal(open(regular.data,correction.data,{correctionId:'correction-74'}).report.id,'correction-74');
});
test('detail authorization failure propagates to both record groups',async()=>{const error={code:'P0001',message:'denied'};const result=await exports.loadFamilyDetailReports({rpc:async()=>({data:null,error})},'other','2026-09-01');assert.equal(result[0].error,error);assert.equal(result[1].error,error);});
test('invalid dates do not issue a query and malformed response is an error',async()=>{let calls=0;const client={rpc:async()=>{calls++;return {data:{},error:null}}};for(const date of ['bad','2026-02-30'])await assert.rejects(exports.loadFamilyDetailReports(client,'a',date));assert.equal(calls,0);assert.ok((await exports.loadFamilyDetailReports(client,'a','2026-09-01'))[0].error);});
test('summary passes clicked date to detail and detail loader reacts to date changes',()=>{const source=readFileSync(new URL('../../app/family-dashboard.tsx',import.meta.url),'utf8');assert.match(source,/correctionId: item\.id\.slice\("correction-"\.length\), date: item\.date/);assert.match(source,/lessonId: item\.id\.slice\("lesson-"\.length\), date: item\.date/);assert.match(feed,/detailDate\s*\? await loadFamilyDetailReports/);assert.match(feed,/\[detailOnly, detailDate, studentId, supabase\]/);});
