import {readFileSync} from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import test from 'node:test';import assert from 'node:assert/strict';
const source=readFileSync(new URL('../../app/tuition-board.tsx',import.meta.url),'utf8');
const start=source.indexOf('  const load = useCallback('),end=source.indexOf('  const generate =',start);
const code=ts.transpile(source.slice(start,end)+';globalThis.load=load;', {target:ts.ScriptTarget.ES2022});
const tick=()=>new Promise(r=>setImmediate(r));
function harness(){const pending=[],state={},ctx={month:'2026-09',request:{current:0},EMPTY_TUITION_DATA:{isStaff:false,items:[]},useCallback:f=>f,useEffect:f=>{ctx.cleanup=f();},setPending:v=>state.loading=v,setMessage:v=>state.message=v,setLoaded:v=>state.loaded=v};ctx.supabase={rpc:()=>new Promise((resolve,reject)=>pending.push({resolve,reject}))};ctx.activeContext={current:{month:ctx.month,supabase:ctx.supabase}};vm.createContext(ctx);return {ctx,state,pending,mount(month='2026-09'){ctx.cleanup?.();ctx.month=month;ctx.activeContext.current={month,supabase:ctx.supabase};vm.runInContext('(function(month,supabase){'+code+'})(month,supabase)',ctx);},unmount(){ctx.cleanup();}};}
const response=id=>({data:{isStaff:true,items:[{id}]},error:null});
test('latest month wins even if old response resolves last',async()=>{const h=harness();h.mount();h.mount('2026-10');h.pending[1].resolve(response('oct'));await tick();h.pending[0].resolve(response('sep'));await tick();assert.equal(h.state.loaded.month,'2026-10');assert.equal(h.state.loaded.data.items[0].id,'oct');assert.equal(h.state.loading,false);});
test('stale failure cannot clear new results',async()=>{const h=harness();h.mount();h.mount('2026-10');h.pending[1].resolve(response('oct'));await tick();h.pending[0].reject(new Error('offline'));await tick();assert.equal(h.state.loaded.data.items[0].id,'oct');assert.equal(h.state.message,'');});
test('returned and thrown errors clear stale records and stop loading; retry succeeds',async()=>{const h=harness();h.mount();h.pending[0].resolve(response('sep'));await tick();let p=h.ctx.load();h.pending[1].resolve({data:null,error:{message:'offline'}});await p;assert.equal(h.state.loaded.data.items.length,0);assert.equal(h.state.loading,false);p=h.ctx.load();h.pending[2].reject(new Error('offline'));await p;assert.equal(h.state.loading,false);p=h.ctx.load();h.pending[3].resolve(response('retry'));await p;assert.equal(h.state.loaded.data.items[0].id,'retry');});
test('unmount invalidates pending responses',async()=>{const h=harness();h.mount();h.unmount();h.pending[0].resolve(response('late'));await tick();assert.equal(h.state.loaded,undefined);});
test('old callback cannot start requests after month change',async()=>{const h=harness();h.mount();const old=h.ctx.load;h.mount('2026-10');await old();assert.equal(h.pending.length,2);h.unmount();});
test('display data is scoped to month and account, with retry action',()=>{assert.match(source,/loaded\?\.month===month&&loaded.client===supabase/);assert.match(source,/const data=current\?loaded.data:EMPTY_TUITION_DATA/);assert.match(source,/onClick=\{\(\)=>void load\(\)\}>다시 시도/);});
