do $test$
declare uid uuid; other_uid uuid; eid uuid; sid uuid; ver uuid; d date:=(now() at time zone 'Asia/Seoul')::date; cat text; v jsonb; res jsonb; sid_student uuid; sub uuid;
begin
 select id into uid from public.profiles where role='admin' and is_active limit 1;
 select id into other_uid from public.profiles where role='teacher' and is_active and id<>uid limit 1;
 if uid is null or other_uid is null then raise exception 'test fixture missing';end if;
 perform set_config('request.jwt.claim.sub',uid::text,true);
 select id into cat from public.academic_calendar_categories where scope='academy' and is_active limit 1;
 v:=jsonb_build_object('p_scope','academy','p_category',cat,'p_title','Reminder rollback test','p_starts_on',d,'p_ends_on',d,'p_teacher_id',uid,'p_status','scheduled','p_note','full memo');
 eid:=public.staff_save_calendar_with_reminder(v,true);
 if not (select reminder_enabled from public.academic_calendar_events where id=eid) then raise exception 'calendar save flag';end if;
 res:=public.staff_schedule_reminders(true);
 if jsonb_array_length(res->'popup')<>1 then raise exception 'first popup %',res;end if;
 if jsonb_array_length(public.staff_schedule_reminders(true)->'popup')<>0 then raise exception 'duplicate popup';end if;
 select reminder_version into ver from public.academic_calendar_events where id=eid;
 perform public.staff_ack_schedule_reminder('calendar',eid,ver);
 if not (select (x->>'read')::boolean from jsonb_array_elements(public.staff_schedule_reminders(false)->'items') x where x->>'id'=eid::text) then raise exception 'ack missing';end if;
 perform set_config('request.jwt.claim.sub',other_uid::text,true);
 if exists(select 1 from jsonb_array_elements(public.staff_schedule_reminders(false)->'items') x where x->>'id'=eid::text) then raise exception 'recipient leak';end if;
 begin perform public.staff_ack_schedule_reminder('calendar',eid,ver);raise exception 'other acknowledged';exception when others then if sqlerrm='other acknowledged' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',uid::text,true);
 select public.calendar_edit_values(e) into v from public.academic_calendar_events e where id=eid;
 res:=public.staff_patch_calendar_event(eid,v,jsonb_build_object('note','changed memo'));
 if not coalesce((res->>'saved')::boolean,false) then raise exception 'patch failed';end if;
 if (select reminder_version=ver from public.academic_calendar_events where id=eid) then raise exception 'version not changed';end if;
 if jsonb_array_length(public.staff_schedule_reminders(true)->'popup')<>1 then raise exception 'changed popup missing';end if;
 update public.academic_calendar_events set status='cancelled' where id=eid;
 if exists(select 1 from public.current_schedule_reminders() where source_id=eid) then raise exception 'cancel retained';end if;
 update public.academic_calendar_events set status='scheduled',starts_on=d+1,ends_on=d+1 where id=eid;
 if exists(select 1 from public.current_schedule_reminders() where source_id=eid) then raise exception 'future retained';end if;
 update public.academic_calendar_events set starts_on=d,ends_on=d,reminder_enabled=false where id=eid;
 if exists(select 1 from public.current_schedule_reminders() where source_id=eid) then raise exception 'disabled retained';end if;
 update public.academic_calendar_events set reminder_enabled=true,teacher_profile_id=other_uid where id=eid;
 if exists(select 1 from public.current_schedule_reminders() where source_id=eid) then raise exception 'old recipient retained';end if;
 perform set_config('request.jwt.claim.sub',other_uid::text,true);
 if jsonb_array_length(public.staff_schedule_reminders(true)->'popup')<>1 then raise exception 'new recipient missing';end if;
 perform set_config('request.jwt.claim.sub',uid::text,true);
 delete from public.academic_calendar_events where id=eid;
 if exists(select 1 from public.current_schedule_reminders() where source_id=eid) then raise exception 'deleted retained';end if;
 select id into sid_student from public.students limit 1;
 select id into sub from public.academy_subjects where active limit 1;
 sid:=public.staff_save_special_with_reminder(jsonb_build_object('p_teacher_id',uid,'p_date',d,'p_start_time','03:01','p_end_time','03:02','p_kind','makeup','p_subject_id',sub,'p_student_ids',jsonb_build_array(sid_student)),true);
 if not exists(select 1 from public.current_schedule_reminders() where source='special' and source_id=sid) then raise exception 'special missing';end if;
 select reminder_version into ver from public.teacher_special_lessons where id=sid;
 update public.teacher_special_lessons set class_notice='learning content changed' where id=sid;
 if (select reminder_version<>ver from public.teacher_special_lessons where id=sid) then raise exception 'learning update causes alert';end if;
 update public.teacher_special_lessons set status='completed' where id=sid;
 if exists(select 1 from public.current_schedule_reminders() where source_id=sid) then raise exception 'completed retained';end if;
 perform set_config('request.jwt.claim.sub','',true);
 begin perform public.staff_schedule_reminders();raise exception 'anonymous allowed';exception when others then if sqlerrm='anonymous allowed' then raise;end if;end;
 if has_function_privilege('anon','public.staff_schedule_reminders(boolean)','EXECUTE') then raise exception 'anon grant';end if;
end $test$;
select 'reminder rollback checks passed' as result;
