-- Execute only inside BEGIN / ROLLBACK, alongside the migration when testing before release.
do $test$
declare a uuid;b uuid;c uuid;invalid uuid;eid uuid;sid uuid;ver uuid;v jsonb;res jsonb;cat text;student uuid;sub uuid;d date:=(now() at time zone 'Asia/Seoul')::date;
begin
 select id into a from public.profiles where is_active and role='admin' limit 1;
 select id into b from public.profiles where is_active and role='teacher' and id<>a limit 1;
 select id into c from public.profiles where is_active and role in ('teacher','assistant','manager') and id<>a and id<>b limit 1;
 select id into invalid from public.profiles where role in ('student','guardian') limit 1;
 if a is null or b is null or c is null or invalid is null then raise exception 'Missing fixtures';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select id into cat from public.academic_calendar_categories where scope='academy' and is_active limit 1;
 v:=jsonb_build_object('p_scope','academy','p_category',cat,'p_title','Recipients rollback test','p_starts_on',d,'p_ends_on',d,'p_teacher_id',a,'p_status','scheduled','p_reminder_recipient_ids',jsonb_build_array(a,b,b));
 eid:=public.staff_save_calendar_with_reminder(v,true);
 select reminder_version into ver from public.academic_calendar_events where id=eid;
 if (select cardinality(reminder_recipient_ids) from public.academic_calendar_events where id=eid)<>2 then raise exception 'Recipients not deduplicated';end if;
 if not exists(select 1 from jsonb_array_elements_text(public.staff_schedule_reminders(true)->'popup') x where x='calendar:'||eid||':'||ver) then raise exception 'First recipient missing';end if;
 perform public.staff_ack_schedule_reminder('calendar',eid,ver);
 perform set_config('request.jwt.claim.sub',b::text,true);
 if not exists(select 1 from public.current_schedule_reminders() where source_id=eid) then raise exception 'Second recipient missing';end if;
 if (select (x->>'read')::boolean from jsonb_array_elements(public.staff_schedule_reminders(false)->'items') x where x->>'id'=eid::text) then raise exception 'Read state leaked between recipients';end if;
 perform public.staff_ack_schedule_reminder('calendar',eid,ver);
 perform set_config('request.jwt.claim.sub',c::text,true);
 if exists(select 1 from public.current_schedule_reminders() where source_id=eid) then raise exception 'Unselected recipient sees reminder';end if;
 begin perform public.staff_ack_schedule_reminder('calendar',eid,ver);raise exception 'Unauthorized ack succeeded';exception when others then if sqlerrm='Unauthorized ack succeeded' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select public.calendar_edit_values(e) into v from public.academic_calendar_events e where id=eid;
 res:=public.staff_patch_calendar_event(eid,v,jsonb_build_object('reminderRecipientIds',jsonb_build_array(a,b,c)));
 if not coalesce((res->>'saved')::boolean,false) then raise exception 'Recipient patch failed';end if;
 if (select reminder_version from public.academic_calendar_events where id=eid)<>ver then raise exception 'Adding recipient re-alerts existing recipients';end if;
 if not (select (x->>'read')::boolean from jsonb_array_elements(public.staff_schedule_reminders(false)->'items') x where x->>'id'=eid::text) then raise exception 'Existing receipt lost';end if;
 res:=public.staff_patch_calendar_event(eid,v,jsonb_build_object('reminderRecipientIds',jsonb_build_array(a)));
 if not (res->'conflicts' ? 'reminderRecipientIds') then raise exception 'Concurrent recipient edit not detected';end if;
 perform set_config('request.jwt.claim.sub',c::text,true);
 if not exists(select 1 from jsonb_array_elements_text(public.staff_schedule_reminders(true)->'popup') x where x='calendar:'||eid||':'||ver) then raise exception 'Added recipient has no popup';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select public.calendar_edit_values(e) into v from public.academic_calendar_events e where id=eid;
 perform public.staff_patch_calendar_event(eid,v,jsonb_build_object('reminderRecipientIds',jsonb_build_array(a,c)));
 perform set_config('request.jwt.claim.sub',b::text,true);
 if exists(select 1 from public.current_schedule_reminders() where source_id=eid) then raise exception 'Removed recipient still sees reminder';end if;
 begin perform public.staff_ack_schedule_reminder('calendar',eid,ver);raise exception 'Removed recipient acknowledged';exception when others then if sqlerrm='Removed recipient acknowledged' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',a::text,true);
 select public.calendar_edit_values(e) into v from public.academic_calendar_events e where id=eid;
 begin perform public.staff_patch_calendar_event(eid,v,jsonb_build_object('reminderRecipientIds',jsonb_build_array(invalid)));raise exception 'Family recipient accepted';exception when others then if sqlerrm='Family recipient accepted' then raise;end if;end;
 begin perform public.staff_patch_calendar_event(eid,v,jsonb_build_object('reminderRecipientIds','[]'::jsonb));raise exception 'Empty recipients accepted';exception when others then if sqlerrm='Empty recipients accepted' then raise;end if;end;
 if (select cardinality(reminder_recipient_ids) from public.academic_calendar_events where id=eid)<>2 then raise exception 'Failed update not rolled back';end if;
 select id into student from public.students limit 1;
 select id into sub from public.academy_subjects where active limit 1;
 v:=jsonb_build_object('p_teacher_id',a,'p_date',d,'p_start_time','03:03','p_end_time','03:04','p_kind','makeup','p_subject_id',sub,'p_student_ids',jsonb_build_array(student),'p_reminder_recipient_ids',jsonb_build_array(a,b));
 sid:=public.staff_save_special_with_reminder(v,true);
 perform set_config('request.jwt.claim.sub',b::text,true);
 if not exists(select 1 from public.current_schedule_reminders() where source='special' and source_id=sid) then raise exception 'Special second recipient missing';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);
 -- Older clients omit recipients: preserve the explicit selection on save.
 perform public.staff_save_special_with_reminder((v-'p_reminder_recipient_ids')||jsonb_build_object('p_id',sid),true);
 if (select cardinality(reminder_recipient_ids) from public.teacher_special_lessons where id=sid)<>2 then raise exception 'Legacy save lost recipients';end if;
 perform set_config('request.jwt.claim.sub',invalid::text,true);
 begin perform public.staff_schedule_reminder_people();raise exception 'Family can list recipients';exception when others then if sqlerrm='Family can list recipients' then raise;end if;end;
 if has_function_privilege('anon','public.staff_schedule_reminder_people()','EXECUTE') then raise exception 'Anonymous recipient list grant';end if;
end $test$;
select 'multi-recipient checks passed' as result;
