-- 관리자가 운영 전 필수 연결과 최근 데이터 누락을 한눈에 점검합니다.

create or replace function public.admin_operations_audit()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare result jsonb;
begin
  if public.current_user_role() is distinct from 'admin'::public.user_role then raise exception '관리자만 운영 상태를 점검할 수 있습니다.'; end if;
  select jsonb_build_object('checkedAt',now(),'categories',jsonb_build_array(
    jsonb_build_object('key','account_links','title','로그인 계정 연결','description','활성 학생·학부모·교사 계정이 실제 정보와 연결되어야 합니다.','severity','critical','actionLabel','계정·역할','actionView','settings','count',(select count(*) from public.profiles p where p.is_active and ((p.role='student' and not exists(select 1 from public.students s where s.profile_id=p.id)) or (p.role='guardian' and not exists(select 1 from public.guardians g where g.profile_id=p.id)) or (p.role='teacher' and not exists(select 1 from public.teachers t where t.profile_id=p.id)))),'items',coalesce((select jsonb_agg(row_data) from (select jsonb_build_object('id',p.id,'name',p.display_name,'detail',case p.role when 'student' then '학생 정보 미연결' when 'guardian' then '자녀·학부모 정보 미연결' else '교사 정보 미연결' end) row_data from public.profiles p where p.is_active and ((p.role='student' and not exists(select 1 from public.students s where s.profile_id=p.id)) or (p.role='guardian' and not exists(select 1 from public.guardians g where g.profile_id=p.id)) or (p.role='teacher' and not exists(select 1 from public.teachers t where t.profile_id=p.id))) order by p.display_name limit 12) rows),'[]'::jsonb)),
    jsonb_build_object('key','student_enrollments','title','수강 클래스가 없는 재원생','description','재원생은 하나 이상의 운영 클래스에 배정되어야 합니다.','severity','critical','actionLabel','학생 관리','actionView','students','count',(select count(*) from public.students s where s.status in ('active','재원') and not exists(select 1 from public.enrollments e where e.student_id=s.id and e.status='active')),'items',coalesce((select jsonb_agg(row_data) from (select jsonb_build_object('id',s.id,'name',s.name,'detail',coalesce(s.school,'학교 미입력')||case when s.grade is not null then ' · '||s.grade else '' end) row_data from public.students s where s.status in ('active','재원') and not exists(select 1 from public.enrollments e where e.student_id=s.id and e.status='active') order by s.name limit 12) rows),'[]'::jsonb)),
    jsonb_build_object('key','class_teachers','title','담당 선생님이 없는 클래스','description','운영 클래스마다 로그인 교직원을 한 명 이상 배정해 주세요.','severity','critical','actionLabel','시간표','actionView','schedule','count',(select count(*) from public.classes c where c.active and not exists(select 1 from public.class_teachers ct where ct.class_id=c.id)),'items',coalesce((select jsonb_agg(row_data) from (select jsonb_build_object('id',c.id,'name',c.name,'detail',c.subject||coalesce(' · '||c.room,'')) row_data from public.classes c where c.active and not exists(select 1 from public.class_teachers ct where ct.class_id=c.id) order by c.name limit 12) rows),'[]'::jsonb)),
    jsonb_build_object('key','class_schedules','title','시간표가 없는 클래스','description','운영 클래스의 요일과 시작·종료 시간을 등록해 주세요.','severity','critical','actionLabel','시간표','actionView','schedule','count',(select count(*) from public.classes c where c.active and not exists(select 1 from public.class_schedules cs where cs.class_id=c.id and (cs.valid_until is null or cs.valid_until>=current_date))),'items',coalesce((select jsonb_agg(row_data) from (select jsonb_build_object('id',c.id,'name',c.name,'detail',c.subject||coalesce(' · '||c.room,'')) row_data from public.classes c where c.active and not exists(select 1 from public.class_schedules cs where cs.class_id=c.id and (cs.valid_until is null or cs.valid_until>=current_date)) order by c.name limit 12) rows),'[]'::jsonb)),
    jsonb_build_object('key','student_contacts','title','연락 정보가 부족한 학생','description','학생 연락처 또는 학부모 연결 중 하나 이상을 등록해 주세요.','severity','warning','actionLabel','학생 관리','actionView','students','count',(select count(*) from public.students s where s.status in ('active','재원') and nullif(trim(s.phone),'') is null and not exists(select 1 from public.student_guardians sg where sg.student_id=s.id)),'items',coalesce((select jsonb_agg(row_data) from (select jsonb_build_object('id',s.id,'name',s.name,'detail','학생 연락처·학부모 모두 미등록') row_data from public.students s where s.status in ('active','재원') and nullif(trim(s.phone),'') is null and not exists(select 1 from public.student_guardians sg where sg.student_id=s.id) order by s.name limit 12) rows),'[]'::jsonb)),
    jsonb_build_object('key','recent_attendance','title','최근 출결이 없는 학생','description','수강 중인 재원생의 최근 30일 출결 기록을 확인합니다.','severity','warning','actionLabel','출결 입력','actionView','attendance','count',(select count(*) from public.students s where s.status in ('active','재원') and exists(select 1 from public.enrollments e where e.student_id=s.id and e.status='active') and not exists(select 1 from public.attendance a join public.lessons l on l.id=a.lesson_id where a.student_id=s.id and l.lesson_date>=current_date-30)),'items',coalesce((select jsonb_agg(row_data) from (select jsonb_build_object('id',s.id,'name',s.name,'detail','최근 30일 출결 기록 없음') row_data from public.students s where s.status in ('active','재원') and exists(select 1 from public.enrollments e where e.student_id=s.id and e.status='active') and not exists(select 1 from public.attendance a join public.lessons l on l.id=a.lesson_id where a.student_id=s.id and l.lesson_date>=current_date-30) order by s.name limit 12) rows),'[]'::jsonb)),
    jsonb_build_object('key','recent_assignments','title','최근 과제가 없는 학생','description','수강 클래스에 최근 30일 과제가 등록되었는지 확인합니다.','severity','info','actionLabel','과제·첨삭','actionView','assignments','count',(select count(*) from public.students s where s.status in ('active','재원') and exists(select 1 from public.enrollments e where e.student_id=s.id and e.status='active') and not exists(select 1 from public.enrollments e join public.assignments a on a.class_id=e.class_id where e.student_id=s.id and e.status='active' and a.created_at>=now()-interval '30 days')),'items',coalesce((select jsonb_agg(row_data) from (select jsonb_build_object('id',s.id,'name',s.name,'detail','수강 클래스 최근 30일 과제 없음') row_data from public.students s where s.status in ('active','재원') and exists(select 1 from public.enrollments e where e.student_id=s.id and e.status='active') and not exists(select 1 from public.enrollments e join public.assignments a on a.class_id=e.class_id where e.student_id=s.id and e.status='active' and a.created_at>=now()-interval '30 days') order by s.name limit 12) rows),'[]'::jsonb))
  )) into result;
  return result;
end
$$;

revoke all on function public.admin_operations_audit() from public;
grant execute on function public.admin_operations_audit() to authenticated;
