-- 반복 수강료 기준, 미납 알림과 영수증용 조회 정보를 추가합니다.
create table public.tuition_recurring_adjustments(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,kind text not null check(kind in ('discount','additional')),label text not null,amount integer not null default 0 check(amount>=0),active boolean not null default true,updated_at timestamptz not null default now(),unique(student_id,kind));
alter table public.tuition_recurring_adjustments enable row level security;
create policy "staff_manage_tuition_recurring_adjustments" on public.tuition_recurring_adjustments for all to authenticated using(public.is_staff()) with check(public.is_staff());
grant select,insert,update,delete on public.tuition_recurring_adjustments to authenticated;
alter table public.family_notifications drop constraint family_notifications_source_type_check;
alter table public.family_notifications add constraint family_notifications_source_type_check check(source_type in ('attendance','makeup','tuition'));

create or replace function public.staff_generate_monthly_tuition(p_month date) returns integer language plpgsql security definer set search_path=public as $$
declare month_start date:=date_trunc('month',p_month)::date;generated integer;begin
if not public.is_staff() then raise exception '교직원만 월 청구서를 생성할 수 있습니다.';end if;
with base as(select s.id,coalesce(sum(e.monthly_fee),0)::integer base_amount from public.students s join public.enrollments e on e.student_id=s.id where s.status in ('active','재원') and e.started_on<(month_start+interval '1 month')::date and (e.ended_on is null or e.ended_on>=month_start) and e.status in ('active','paused') group by s.id),rules as(select b.*,coalesce(d.amount,0) discount_amount,coalesce(a.amount,0) additional_amount,nullif(concat_ws(' · ',d.label,a.label),'') memo from base b left join public.tuition_recurring_adjustments d on d.student_id=b.id and d.kind='discount' and d.active left join public.tuition_recurring_adjustments a on a.student_id=b.id and a.kind='additional' and a.active)
insert into public.tuition_charges(student_id,billing_month,base_amount,discount_amount,additional_amount,memo) select id,month_start,base_amount,least(discount_amount,base_amount+additional_amount),additional_amount,memo from rules on conflict(student_id,billing_month) do nothing;
get diagnostics generated=row_count;return generated;end $$;

create or replace function public.tuition_billing_settings() returns jsonb language sql stable security definer set search_path=public as $$
select case when public.is_staff() then coalesce(jsonb_agg(jsonb_build_object('id',s.id,'name',s.name,'enrollments',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'className',c.name,'monthlyFee',coalesce(e.monthly_fee,0)) order by c.name) from public.enrollments e join public.classes c on c.id=e.class_id where e.student_id=s.id and e.status='active'),'[]'::jsonb),'discount',coalesce((select jsonb_build_object('label',a.label,'amount',a.amount,'active',a.active) from public.tuition_recurring_adjustments a where a.student_id=s.id and a.kind='discount'),jsonb_build_object('label','고정 할인','amount',0,'active',true)),'additional',coalesce((select jsonb_build_object('label',a.label,'amount',a.amount,'active',a.active) from public.tuition_recurring_adjustments a where a.student_id=s.id and a.kind='additional'),jsonb_build_object('label','차량·교재비','amount',0,'active',true))) order by s.name),'[]'::jsonb) else '[]'::jsonb end from public.students s where s.status in ('active','재원') $$;

create or replace function public.staff_save_enrollment_fee(p_enrollment_id uuid,p_monthly_fee integer) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_staff() then raise exception '교직원만 수강료를 설정할 수 있습니다.';end if;if p_monthly_fee<0 then raise exception '월 수강료를 확인해 주세요.';end if;update public.enrollments set monthly_fee=p_monthly_fee where id=p_enrollment_id;if not found then raise exception '수강 정보를 찾을 수 없습니다.';end if;end $$;
create or replace function public.staff_save_tuition_recurring_rule(p_student_id uuid,p_kind text,p_label text,p_amount integer,p_active boolean) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_staff() then raise exception '교직원만 수강료 기준을 설정할 수 있습니다.';end if;if p_kind not in ('discount','additional') or p_amount<0 then raise exception '반복 금액을 확인해 주세요.';end if;insert into public.tuition_recurring_adjustments(student_id,kind,label,amount,active) values(p_student_id,p_kind,coalesce(nullif(trim(p_label),''),case when p_kind='discount' then '고정 할인' else '추가 비용' end),p_amount,p_active) on conflict(student_id,kind) do update set label=excluded.label,amount=excluded.amount,active=excluded.active,updated_at=now();end $$;
create or replace function public.staff_queue_tuition_reminders(p_month date) returns integer language plpgsql security definer set search_path=public as $$ declare r record;queued integer:=0;begin if not public.is_staff() then raise exception '교직원만 미납 알림을 만들 수 있습니다.';end if;for r in select tc.id,tc.student_id,(tc.base_amount-tc.discount_amount+tc.additional_amount-coalesce((select sum(tp.amount) from public.tuition_payments tp where tp.charge_id=tc.id),0))::integer balance from public.tuition_charges tc where tc.billing_month=date_trunc('month',p_month)::date and tc.status in ('open','partial') loop if r.balance>0 then perform public.enqueue_family_notification(r.student_id,'balance-reminder','수강료 미납 안내',to_char(p_month,'YYYY년 MM월')||' 수강료 미납 잔액은 '||to_char(r.balance,'FM999,999,999')||'원입니다.','tuition',r.id);queued:=queued+1;end if;end loop;return queued;end $$;
revoke all on function public.tuition_billing_settings(),public.staff_save_enrollment_fee(uuid,integer),public.staff_save_tuition_recurring_rule(uuid,text,text,integer,boolean),public.staff_queue_tuition_reminders(date) from public;
grant execute on function public.tuition_billing_settings(),public.staff_save_enrollment_fee(uuid,integer),public.staff_save_tuition_recurring_rule(uuid,text,text,integer,boolean),public.staff_queue_tuition_reminders(date) to authenticated;
