-- 관리자용 기간별 운영 통계와 CSV 원천 데이터를 제공합니다.
create or replace function public.admin_operations_analytics(p_from date,p_to date)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare result jsonb;
begin
if public.current_user_role()<>'admin' then raise exception '관리자만 운영 통계를 확인할 수 있습니다.';end if;
if p_from>p_to or p_to-p_from>366 then raise exception '조회 기간은 1년 이내로 선택해 주세요.';end if;
select jsonb_build_object(
'students',jsonb_build_object('active',(select count(*) from public.students where status in ('active','재원')),'paused',(select count(*) from public.students where status in ('paused','휴원')),'completed',(select count(*) from public.students where status in ('completed','퇴원')),'new',(select count(*) from public.students where created_at::date between p_from and p_to),'pausedInPeriod',(select count(*) from public.student_status_history where new_status='paused' and effective_on between p_from and p_to),'completedInPeriod',(select count(*) from public.student_status_history where new_status='completed' and effective_on between p_from and p_to)),
'billing',jsonb_build_object('charged',coalesce((select sum(base_amount-discount_amount+additional_amount) from public.tuition_charges where billing_month between date_trunc('month',p_from)::date and date_trunc('month',p_to)::date),0),'paid',coalesce((select sum(tp.amount) from public.tuition_payments tp join public.tuition_charges tc on tc.id=tp.charge_id where tp.paid_at::date between p_from and p_to),0),'outstanding',coalesce((select sum(greatest(tc.base_amount-tc.discount_amount+tc.additional_amount-coalesce((select sum(tp.amount) from public.tuition_payments tp where tp.charge_id=tc.id),0),0)) from public.tuition_charges tc where tc.billing_month between date_trunc('month',p_from)::date and date_trunc('month',p_to)::date and tc.status<>'waived'),0)),
'attendance',jsonb_build_object('total',(select count(*) from public.attendance a join public.lessons l on l.id=a.lesson_id where l.lesson_date between p_from and p_to),'present',(select count(*) from public.attendance a join public.lessons l on l.id=a.lesson_id where l.lesson_date between p_from and p_to and a.status='present'),'late',(select count(*) from public.attendance a join public.lessons l on l.id=a.lesson_id where l.lesson_date between p_from and p_to and a.status='late'),'absent',(select count(*) from public.attendance a join public.lessons l on l.id=a.lesson_id where l.lesson_date between p_from and p_to and a.status='absent'),'makeupNeeded',(select count(*) from public.attendance a join public.lessons l on l.id=a.lesson_id where l.lesson_date between p_from and p_to and a.makeup_required),'makeupCompleted',(select count(*) from public.makeup_sessions ms where ms.status='completed' and ms.scheduled_at::date between p_from and p_to)),
'operations',jsonb_build_object('activeClasses',(select count(*) from public.classes where active),'teachers',(select count(*) from public.profiles where role in ('admin','teacher') and is_active),'correctionStudents',(select count(distinct student_id) from public.correction_assignments where valid_from<=p_to and (valid_until is null or valid_until>=p_from)),'vehicleStudents',(select count(distinct vb.student_id) from public.vehicle_boardings vb join public.vehicle_runs vr on vr.id=vb.run_id where vr.active)),
'classes',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'subject',c.subject,'enrolled',(select count(*) from public.enrollments e where e.class_id=c.id and e.status='active'),'teachers',(select count(*) from public.class_teachers ct where ct.class_id=c.id),'attendanceRate',coalesce((select round(100.0*count(*)filter(where a.status='present')/nullif(count(*),0)) from public.lessons l join public.attendance a on a.lesson_id=l.id where l.class_id=c.id and l.lesson_date between p_from and p_to),0)) order by c.name) from public.classes c where c.active),'[]'::jsonb),
'teachers',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'name',p.display_name,'classes',(select count(*) from public.class_teachers ct where ct.profile_id=p.id),'correctionStudents',(select count(distinct ca.student_id) from public.correction_assignments ca where ca.teacher_profile_id=p.id and ca.valid_from<=p_to and (ca.valid_until is null or ca.valid_until>=p_from)),'consultations',(select count(*) from public.consultations c where c.consultant_profile_id=p.id and c.consulted_at::date between p_from and p_to)) order by p.display_name) from public.profiles p where p.role in ('admin','teacher') and p.is_active),'[]'::jsonb),
'monthly',coalesce((select jsonb_agg(jsonb_build_object('month',m.month_start,'newStudents',(select count(*) from public.students s where s.created_at::date>=m.month_start and s.created_at::date<(m.month_start+interval '1 month')::date),'charged',coalesce((select sum(base_amount-discount_amount+additional_amount) from public.tuition_charges tc where tc.billing_month=m.month_start),0),'paid',coalesce((select sum(tp.amount) from public.tuition_payments tp where tp.paid_at::date>=m.month_start and tp.paid_at::date<(m.month_start+interval '1 month')::date),0)) order by m.month_start) from (select generate_series(date_trunc('month',p_from),date_trunc('month',p_to),interval '1 month')::date month_start)m),'[]'::jsonb)
) into result;return result;end $$;
revoke all on function public.admin_operations_analytics(date,date) from public;
grant execute on function public.admin_operations_analytics(date,date) to authenticated;
