// Real SQL, synthetic in-memory PostgreSQL only. No messages are sent.
const {PGlite}=require('../family-database/node_modules/@electric-sql/pglite');
const fs=require('node:fs'),assert=require('node:assert/strict');
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
(async()=>{
 const db=new PGlite();
 await db.exec(fs.readFileSync('tests/class-participants/schema.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20260924151450_class_day_participants.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20260924151643_participant_preview_compatibility.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/20260924155505_academy_closure_days.sql','utf8'));
 await db.exec(`set test.uid='${id(1)}';set test.role='admin';`);
 await db.exec(`insert into profiles(id,display_name,role,is_active) values('${id(1)}','테스트 선생님','admin',true);
 insert into students(id,name,status,profile_id) values('${id(3)}','참여 학생','active','${id(30)}'),('${id(4)}','연휴 학생','active','${id(40)}');
 insert into classes(id,name,subject,room,active) values('${id(2)}','테스트 영어','영어','101',true),('${id(5)}','테스트 수학','수학','102',true);
 insert into class_teachers(class_id,profile_id) values('${id(2)}','${id(1)}'),('${id(5)}','${id(1)}');
 insert into class_schedules(class_id,weekday,start_time,end_time) values('${id(2)}',extract(isodow from current_date),'10:00','11:30'),('${id(5)}',extract(isodow from current_date),'12:00','13:30');
 insert into enrollments(class_id,student_id,status,started_on) values('${id(2)}','${id(3)}','active',current_date-30),('${id(2)}','${id(4)}','active',current_date-30),('${id(5)}','${id(4)}','active',current_date-30);`);
 const query=async(sql,args=[])=> (await db.query(sql,args)).rows;
 const today=(await query("select current_date::text d"))[0].d;
 const snap=async(cid=id(2))=>(await query('select staff_class_edit_snapshot($1,$2) v',[cid,today]))[0].v;
 const change=(sid,field,before,value)=>({path:['students',sid,field],before,value});
 const patch=async(changes,state,mode,cid=id(2),version)=>{
  const v=version??(await snap(cid)).day.rosterVersion;
  return (await query('select staff_patch_class_record_with_roster($1,$2,$3,$4,$5,$6) v',[cid,today,JSON.stringify(changes),state,mode,v]))[0].v;
 };
 const participants=async(changes,version)=> (await query('select staff_set_class_lesson_participants($1,$2,$3,$4) v',[id(2),today,JSON.stringify(changes),version??(await snap()).day.rosterVersion]))[0].v;
 const exclude=(sid,value)=>({studentId:sid,excluded:value,reason:'추석 연휴'});
 const source=async()=> (await query('select lessons from internal_alimtalk_report_sources(array[$1::uuid],$2,$2)',[id(4),today]))[0]?.lessons??[];
 let s=await snap();const initialVersion=s.day.rosterVersion;
 s=await participants([exclude(id(4),true)]);
 assert.equal(s.day.students.find(x=>x.id===id(4)).excluded,true);
 assert.equal(s.day.students.find(x=>x.id===id(4)).exclusionReason,'추석 연휴');
 await assert.rejects(participants([exclude(id(3),true)],initialVersion),/수업 대상을 변경/);
 await assert.rejects(patch([], 'draft','complete',id(2),initialVersion),/수업 대상이 변경/);
 s=await patch([change(id(3),'status',null,'present'),change(id(3),'lessonContent','','정규 수업')],'draft','complete');
 assert.equal(s.state,'completed','excluded null attendance must not block completion');
 assert.equal((await query('select count(*)::int n from attendance where student_id=$1',[id(4)]))[0].n,0);
 await assert.rejects(query('select staff_save_class_attendance($1,$2,$3,$4)',[id(2),today,id(4),'present']),/제외된 학생/);
 let ready=(await query('select staff_alimtalk_ready_students($1,$1) v',[today]))[0].v;
 let r=ready.find(x=>x.studentId===id(4));
 assert.equal(r.expectedCount,1,'only this student’s mathematics remains expected');
 assert.equal(r.missingItems.some(x=>x.title==='테스트 영어'),false);
 assert.deepEqual(await source(),[]);
 let coverage=(await query('select staff_monthly_lesson_coverage($1) v',[today]))[0].v;
 assert.equal(coverage.items.find(x=>x.studentId===id(4)).events.some(x=>x.date===today),false);
 await patch([change(id(4),'status',null,'present'),change(id(4),'lessonContent','','수학 참여')],'draft','complete',id(5));
 assert.equal((await source()).length,1,'other class is still delivered');
 const oldSource=(await query("select md5(lessons::text) v from internal_alimtalk_report_sources(array[$1::uuid],$2,$2)",[id(4),today]))[0].v;
 await participants([exclude(id(4),false)]);
 s=await patch([change(id(4),'status',null,'present'),change(id(4),'exam_examType','','영단어'),change(id(4),'exam_score','','95'),change(id(4),'assignedHomework','','보존할 숙제')],'completed','publish');
 const examId=s.values.students[id(4)].exam_id;
 assert.equal(Number(s.values.students[id(4)].exam_score),95);assert.equal((await source()).length,2);
 await assert.rejects(query('select * from staff_claim_learning_alimtalk_current($1,$2,$3,$3,$4,$5,$6,$7)',[id(4),'daily',today,'수업','출석','학습',oldSource]),/변경됐습니다/);
 await participants([exclude(id(4),true)]);
 assert.equal((await source()).length,1);
 assert.equal(Number((await query('select score from lesson_exam_results where id=$1',[examId]))[0].score),95,'raw exam is retained');
 assert.equal((await query('select count(*)::int n from internal_participating_exams where id=$1',[examId]))[0].n,0);
 await db.exec(`set test.uid='${id(40)}';set test.role='student';`);
 let family=(await query('select family_completed_learning_reports($1,30) v',[id(4)]))[0].v;
 assert.equal(family.length,1);assert.equal(family[0].subject,'수학');
 const familyAll=(await query('select family_learning_reports($1,30) v',[id(4)]))[0].v;
 assert.equal(familyAll.some(x=>x.subject==='영어'),false);
 const calendar=(await query('select family_learning_calendar_schedule($1,$2) v',[id(4),today]))[0].v;
 assert.equal(calendar.some(x=>x.date===today&&x.subject==='영어'),false);
 const familyToday=(await query('select family_today_lessons($1) v',[id(4)]))[0].v;
 assert.equal(familyToday.some(x=>x.subject==='영어'),false);
 await assert.rejects(participants([exclude(id(4),false)]),/담당 클래스/);
 await db.exec(`set test.uid='${id(1)}';set test.role='admin';`);
 await participants([exclude(id(4),false)]);
 s=await snap();assert.equal(s.values.students[id(4)].exam_id,examId);assert.equal(s.values.students[id(4)].assignedHomework,'보존할 숙제');assert.equal((await source()).length,2);
 const tomorrow=(await query('select staff_class_day($1,current_date+7) v',[id(2)]))[0].v;
 assert.equal(tomorrow.students.some(x=>x.excluded),false,'next lesson keeps normal roster');
 await assert.rejects(participants([{studentId:id(90),excluded:true}]),/명단에 없는 학생/);
 await assert.rejects(participants([{studentId:id(4),excluded:true,reason:'가'.repeat(121)}]),/120자/);
 // A privately saved edit on an excluded student survives publishing other students.
 s=await snap();
 await patch([change(id(4),'assignedHomework',s.values.students[id(4)].assignedHomework,'임시본도 보존')],'completed','revision');
 await participants([exclude(id(4),true),exclude(id(3),true)]);
 await patch([],'completed','publish');
 s=await snap();assert.equal(s.values.students[id(4)].assignedHomework,'임시본도 보존');
 ready=(await query('select staff_alimtalk_ready_students($1,$1) v',[today]))[0].v;
 assert.equal(ready.some(x=>x.studentId===id(3)),false,'all-excluded student is not a send target');
 const schedule=(await query('select id from class_schedules where class_id=$1',[id(2)]))[0].id;
 await query('select staff_mark_class_present($1,$2)',[schedule,today]);
 assert.equal((await snap()).day.students.every(x=>x.excluded),true);
 await db.exec(`set test.uid='${id(40)}';set test.role='student';`);
 const englishLesson=(await query('select id from lessons where class_id=$1',[id(2)]))[0].id;
 assert.equal((await query('select family_can_read_class_attendance($1,$2) v',[englishLesson,id(4)]))[0].v,false);
 await db.exec(`set test.uid='${id(1)}';set test.role='admin';`);
 const staffSource=(await query('select staff_learning_report_source($1,$2,$2) v',[id(4),today]))[0].v;
 assert.equal(staffSource.some(x=>x.subject==='영어'),false);
 await participants([exclude(id(4),false),exclude(id(3),false)]);
 assert.equal((await snap()).values.students[id(4)].assignedHomework,'임시본도 보존');
 await db.exec(`set test.uid='${id(90)}';set test.role='teacher';`);
 await assert.rejects(query('select staff_set_class_lesson_participants($1,$2,$3,$4)',[id(2),today,'[]','x']),/담당 클래스/);
 for(const object of ['class_lesson_participation','internal_participating_attendance','internal_participating_exams','internal_participating_homework'])assert.equal((await query("select has_table_privilege('authenticated',$1,'select') allowed",[object]))[0].allowed,false);
 console.log('PASS: excluded attendance saves, per-student/per-class/date scope, restoration preserves exam IDs and homework, family calendar/reports hidden, Alimtalk source/stale preview protection, monthly coverage, conflict and permission guards.');
 await db.close();
})().catch(e=>{console.error(e.message,e.detail??'',e.where??'');process.exit(1)});
